#!/usr/bin/env python3
"""Static regression checks for conversation-thread UI routing and debug IDs."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
APP = (ROOT / 'src/ui/components/App.tsx').read_text(encoding='utf-8')
AGENTS = (ROOT / 'AGENTS.md').read_text(encoding='utf-8')
SETTINGS = (ROOT / 'src/ui/components/SettingsPage.tsx').read_text(encoding='utf-8')
UPLOAD = (ROOT / 'src/ui/components/ArtifactUpload.tsx').read_text(encoding='utf-8')

checks = [
    ('conversation sidebar section exists', all(snippet in APP for snippet in [
        'function SidebarConversationSection',
        'data-debug-id="sidebar-conversations"',
        'data-debug-id="sidebar-new-conversation-btn"',
        'data-debug-id={`conversation-thread-${agent.id}`}',
        'data-debug-id={`conversation-thread-open-btn-${agent.id}`}',
    ])),
    ('conversation agents are excluded from generic sidebar agents list', ".filter((agent: any) => !isConversationAgent(agent))" in APP),
    ('app keeps concrete conversation id generation for first-message minting', all(snippet in APP for snippet in [
        'function createConversationInstanceId(): string',
        'return `conversation@s-${token}`;',
        'const requestedId = createConversationInstanceId();',
        'agentInstanceId: requestedId',
        "templateId: 'conversation'",
        "agentRole: 'conversation'",
        'setNewConversationBusy(true);',
    ])),
    ('conversation threads route to dedicated page instead of agent detail page', all(snippet in APP for snippet in [
        'return isConversationAgent(selectedPageAgent) ? (',
        '<ConversationThreadPage',
        '<AgentDetailPage',
    ])),
    ('new conversation CTA opens empty-state page before minting an instance', all(snippet in APP for snippet in [
        "updateUrlParams({ view: 'new-conversation'",
        "urlParams.view === 'new-conversation'",
        '<NewConversationPage',
        'data-debug-id="new-conversation-page"',
        'What should we work on?',
    ])),
    ('first new-conversation message mints exact conversation instance then sends body', all(snippet in APP for snippet in [
        'const startFirstMessageConversation = useCallback(async ({ body, projectId, provider, modelTier }',
        'const requestedId = createConversationInstanceId();',
        'await daemonApi.createAgent({ daemonUrl: session?.daemonUrl || \'\', agentInstanceId: requestedId',
        "templateId: 'conversation'",
        "agentRole: 'conversation'",
        'await daemonApi.sendToAgent({ daemonUrl: session.daemonUrl, clientInstanceId: session.clientInstanceId, clientToken: session.clientToken, agentInstanceId: resolvedId, body, interrupt: false });',
        "includes('unknown agent')",
        "updateUrlParams({ view: 'agent', agentId: resolvedId",
    ])),
    ('new conversation page exposes mock option cards and integrated selectors', all(snippet in APP for snippet in [
        'data-debug-id="new-convo-project-select"',
        'data-debug-id={`new-convo-option-${card.id}-btn`}',
        'data-debug-id="new-convo-agent-select"',
        'data-debug-id="new-convo-provider-select"',
        'data-debug-id="new-convo-tier-select"',
        'data-debug-id="new-convo-input"',
        'data-debug-id="new-convo-send-btn"',
        'data-debug-id="new-convo-progress"',
    ])),
    ('agent detail links to durable identity instances page', all(snippet in APP for snippet in [
        'const openAgentIdentityPage = useCallback',
        "updateUrlParams({ view: 'agent-identity'",
        'data-debug-id="agent-detail-all-instances-btn"',
        'data-debug-id="nav-agents-btn"',
        'onOpenIdentity={openAgentIdentityPage}',
    ])),
    ('durable agent identity page separates identity defaults from concrete instances', all(snippet in APP for snippet in [
        'function AgentIdentityPage',
        'data-debug-id="agent-identity-page"',
        'Durable identity · <code>agent_id = {durableId || \'—\'}</code>',
        'data-debug-id="agent-identity-provider-tier"',
        'data-debug-id="agent-identity-memory-summary"',
        'Every concrete instance below inherits these defaults',
    ])),
    ('agent identity page groups instances and exposes exact open/resume actions', all(snippet in APP for snippet in [
        'function AgentInstanceGroup',
        'data-debug-id={`agent-instance-group-${group}`}',
        'group="running"',
        'group="recent"',
        'group="stopped"',
        'data-debug-id={`agent-instance-open-btn-${slug}`}',
        'data-debug-id={`agent-instance-resume-btn-${slug}`}',
        'onResumeInstance={async (instance: any) =>',
        'agentInstanceId: instanceId',
    ])),
    ('conversation-style sidebar is the shared app sidebar on all surfaces', all(snippet in APP for snippet in [
        '<aside className={`${sidebarCollapsed ? \'w-0 border-r-0\' : \'w-[296px] border-r\'} shrink-0 border-white/10 bg-[#090909] transition-[width] duration-200`}>',
        'data-debug-id="conversation-focused-sidebar"',
        '<ConversationFocusedSidebar',
        'data-debug-id="conversation-active-chains"',
        'onNewChain={() => dispatch(openNewChainModal({}))}',
        'selectedChainId={home.selectedChainId}',
    ]) and 'conversationPageActive' not in APP),
    ('shared conversation-style sidebar removes completed task-chain rows', all(snippet in APP for snippet in [
        'const sidebarChains = chains;',
        'const activeChains = sortedChains.filter((chain: any) => !isChainCompleted(chain)).slice(0, 4);',
        'data-debug-id="conversation-active-chains"',
        'data-debug-id={`conversation-sidebar-chain-${chain.chainId}`}',
    ]) and 'data-debug-id="conversation-completed-chains"' not in APP and 'conversation-sidebar-completed-chain' not in APP),
    ('active-chain sidebar rows are first-class navigation controls into ChainView', all(snippet in APP for snippet in [
        'selectedChainId = \'\'',
        'data-debug-id={`conversation-sidebar-chain-${chain.chainId}`}',
        'onClick={() => onOpenChain?.(chain.chainId)}',
        "aria-current={isCurrent ? 'page' : undefined}",
        "title={`${chain.title || chain.chainId}${project?.name ? ` · ${project.name}` : ''} · open task chain`}",
        "isCurrent ? 'bg-[#1c1c1c] text-zinc-100 ring-1 ring-sky-400/25'",
    ])),
    ('global sidebar exposes task chains/projects nav and durable-agent groups', all(snippet in APP for snippet in [
        'data-debug-id="nav-task-chains-btn"',
        'data-debug-id="nav-projects-btn"',
        'data-debug-id="sidebar-durable-agents"',
        'data-debug-id={`sidebar-agent-group-${group.agentId}`}',
        'data-debug-id={`sidebar-agent-group-open-btn-${group.agentId}`}',
        'data-debug-id={`sidebar-agent-new-instance-btn-${group.agentId}`}',
        'const agentGroups = durableAgentGroups(agents);',
        'onStartAgent={onStartAgentInstance}',
        'data-debug-id={`sidebar-agent-live-instances-${group.agentId}`}',
        'data-debug-id={`sidebar-agent-live-instance-row-${id}`}',
        'data-debug-id={`sidebar-agent-live-instance-status-${id}`}',
        "{launching ? '…' : '›'}",
    ]) and 'data-debug-id="nav-attention-btn"' not in APP),
    ('global sidebar collapse keeps default single icon and exposes usable collapsed nav popover', all(snippet in APP for snippet in [
        'const [sidebarCollapsed, setSidebarCollapsed] = useState(false);',
        "${sidebarCollapsed ? 'w-0 border-r-0' : 'w-[296px] border-r'}",
        'const [collapsedMenuOpen, setCollapsedMenuOpen] = useState(false);',
        'data-debug-id="conversation-sidebar-collapse-btn"',
        'data-debug-id="conversation-sidebar-expand-btn"',
        'data-debug-id="conversation-collapsed-nav"',
        'data-debug-id="conversation-sidebar-expand-full-btn"',
        'data-debug-id={`nav-${item.id}-collapsed-btn`}',
        'pointer-events-none h-full w-0 overflow-visible bg-transparent',
        'fixed left-3 top-3 z-50',
        'fixed left-3 top-14 z-50',
        'data-sidebar-collapsed="true"',
        'data-sidebar-collapsed="false"',
        'onToggleCollapsed={() => setSidebarCollapsed((current) => !current)}',
    ]) and 'sidebar-new-conversation-collapsed-btn' not in APP),
    ('global sidebar shows conversations before agents and expands show-more in place', all(snippet in APP for snippet in [
        'const visibleConversations = sortedConversations.slice(0, conversationLimit);',
        'data-debug-id="sidebar-conversations-paged-list"',
        'data-debug-id="sidebar-conversations-show-more-btn"',
        'data-debug-id="sidebar-conversations-loading"',
        'onScroll={(event) => { if (shouldLoadMoreFromScroll(event)) loadMoreConversations(); }}',
        'onClick={loadMoreConversations}',
        "await onFetchAgentPage?.({ offset: visibleConversations.length, limit: SIDEBAR_PAGE_SIZE, kind: 'conversation' });",
        'const visibleGroups = (groups || []).slice(0, agentLimit);',
        'data-debug-id="sidebar-agents-paged-list"',
        'data-debug-id="sidebar-agents-show-more-btn"',
        'data-debug-id="sidebar-agents-loading"',
        'onScroll={(event) => { if (shouldLoadMoreFromScroll(event)) loadMoreAgents(); }}',
        'onClick={loadMoreAgents}',
        "await onFetchAgentPage?.({ offset: visibleGroups.length, limit: SIDEBAR_PAGE_SIZE, kind: 'durable-agent' });",
    ]) and APP[APP.index('function ConversationFocusedSidebar'):].index('<SidebarConversationSection') < APP[APP.index('function ConversationFocusedSidebar'):].index('<SidebarDurableAgentsSection')),
    ('secondary sidebar lists live non-conversation instances only', all(snippet in APP for snippet in [
        'function SidebarAgentInstancesPanel',
        'data-debug-id="sidebar-agent-instances-panel"',
        'data-debug-id={`sidebar-agent-instances-launch-row-${agentId}`}',
        'onStartInstance={startSidebarAgentInstance}',
        '.filter((agent: any) => durableAgentId(agent) === agentId && !isConversationAgent(agent))',
        '.filter((agent: any) => agentHasLiveSession(agent))',
        'data-debug-id={`sidebar-agent-instance-row-${id}`}',
        'Stopped non-conversation instances are hidden here',
    ]) and 'data-debug-id={`sidebar-agent-instances-new-instance-btn-${agentId}`}' not in APP),
    ('sidebar agent rows and instances expose working idle last-seen indicators', all(snippet in APP for snippet in [
        'function agentStatusIndicator',
        "return { key: 'working', label: 'Working'",
        "return { key: 'idle', label: 'Idle'",
        "return { key: 'last-seen', label: last > 0 ? 'Last seen' : 'Unknown'",
        'data-debug-id={`sidebar-agent-status-${group.agentId}`}',
        'aria-label={`${group.agentId} status: ${status.label}`}',
        'data-debug-id={`sidebar-agent-status-label-${group.agentId}`}',
        'data-debug-id={`sidebar-agent-instance-status-${id}`}',
        'aria-label={`${id} status: ${status.label}`}',
        'data-debug-id={`sidebar-agent-instance-status-label-${id}`}',
        'data-debug-id={`conversation-thread-status-${agent.id}`}',
        'data-debug-id={`conversation-thread-status-label-${agent.id}`}',
        'className={`h-2 w-2 shrink-0 rounded-full ${status.color} ${status.pulse}`}',
        'title={status.title}',
    ])),
    ('sidebar pagination uses daemon agents limit offset API', all(snippet in APP + (ROOT / 'src/ui/api/daemonApi.ts').read_text(encoding='utf-8') + (ROOT / 'src/daemon/agents_start.odin').read_text(encoding='utf-8') for snippet in [
        'export async function listKnownAgentsPage',
        'const params = new URLSearchParams({ limit: String(limit), offset: String(offset) });',
        'daemonApi.listKnownAgentsPage({ daemonUrl: session?.daemonUrl || \'\', offset, limit });',
        'limit_str := query_param(request, "limit")',
        'offset_str := query_param(request, "offset")',
        '` ,"next_offset":`'.replace(' ', ''),
        '` ,"has_more":`'.replace(' ', ''),
    ])),
    ('global task chains/projects/agents surfaces expose create flows', all(snippet in APP for snippet in [
        'function AgentsManagementSurface',
        'data-debug-id="agents-management-surface"',
        'data-debug-id="agents-management-create-card"',
        'function TaskChainsSurface',
        'data-debug-id="task-chains-surface"',
        'data-debug-id="task-chains-new-btn"',
        'data-debug-id="task-chains-completed-list"',
        "data-debug-id={`${completedRow ? 'task-chains-completed-row' : 'task-chains-active-row'}-${chain.chainId}`}",
        'function ProjectsSurface',
        'data-debug-id="projects-surface"',
        'data-debug-id="projects-new-btn"',
        'data-debug-id={`projects-new-chain-btn-${projectId}`}',
    ])),
    ('exact non-conversation instance chat starts/resumes selected instance before send', all(snippet in APP for snippet in [
        'const exactAgent = (agents || []).find((agent: any) => agentInstanceId(agent) === agentId) || selectedPageAgent;',
        'if (agentId && !agentHasLiveSession(exactAgent)) {',
        'agentInstanceId: agentId,',
        'await dispatch(refreshAgents()).unwrap().catch(() => undefined);',
        'await daemonApi.sendToAgent({ daemonUrl: session.daemonUrl, clientInstanceId: session.clientInstanceId, clientToken: session.clientToken, agentInstanceId: agentId, body, interrupt });',
    ])),
    ('task chain view keeps mock split layout with toggleable right task/workspace pane', all(snippet in APP for snippet in [
        'data-debug-id="chain-view"',
        'data-debug-id="chain-split-view"',
        'const [tasksPaneOpen, setTasksPaneOpen] = useState(true);',
        'const rightPaneOpen = diffOpen || tasksPaneOpen;',
        'data-workspace-open={diffOpen ? \'true\' : \'false\'}',
        'data-debug-id="chain-tasks-toggle-btn"',
        'data-debug-id="chain-open-editor-btn"',
        'grid-cols-[minmax(0,1fr)_460px]',
        'data-debug-id="chain-coordinator-panel"',
        'data-debug-id="chain-task-surface"',
        'data-debug-id="chain-workspace-sidebar"',
        'data-debug-id="chain-workspace-close-btn"',
    ]) and 'data-debug-id="chain-workspace-row"' not in APP),
    ('task chain pane uses progress card and dependency ordered todo list, not kanban', all(snippet in APP for snippet in [
        'const orderedTasks = useMemo(() => dependencyOrderedTasks(tasks, tasksById || {})',
        'data-debug-id="chain-progress-panel"',
        'data-debug-id="chain-progress-bar"',
        'data-debug-id="chain-progress-complete-count"',
        'data-debug-id="chain-task-count"',
        '<TaskTodoList',
        'title="Active"',
        'title="Completed"',
    ]) and 'chain-task-column-' not in APP),
    ('settings uses mock-like two-pane daemon/provider layout', all(snippet in SETTINGS for snippet in [
        'data-debug-id="settings-modal"',
        'data-debug-id="settings-rail"',
        'data-debug-id="settings-body"',
        'settingsGroups = [',
        "{ title: 'Connections', items: [{ key: 'daemon', label: 'Daemons' }, { key: 'providers', label: 'Providers' }] }",
        'data-debug-id="settings-close-btn"',
    ])),
    ('settings daemons pane exposes single-active daemon rows and add daemon controls', all(snippet in SETTINGS for snippet in [
        'data-debug-id="settings-daemon-single-active-banner"',
        'Single active daemon mode',
        'data-debug-id="settings-daemon-list"',
        'data-debug-id={`settings-daemon-row-${slug}`}',
        'data-debug-id={`settings-daemon-reconnect-btn-${slug}`}',
        'data-debug-id={`settings-daemon-remove-btn-${slug}`}',
        'data-debug-id="settings-daemon-url-input"',
        'data-debug-id="settings-daemon-label-input"',
        'data-debug-id="settings-daemon-user-input"',
        'data-debug-id="settings-daemon-add-btn"',
        'onAddProfile?.({ daemonUrl: nextUrl, url: nextUrl, label: label.trim() || daemonDisplay(nextUrl) })',
        'onRemoveProfile?.({ daemonUrl: url, url })',
    ])),
    ('settings providers pane exposes daemon selector, provider cards, and defaults', all(snippet in SETTINGS for snippet in [
        'data-debug-id="settings-providers-single-daemon-banner"',
        'data-debug-id="settings-providers-daemon-select"',
        'data-debug-id="settings-providers-list"',
        'data-debug-id={`settings-provider-card-${item.name}`}',
        'data-debug-id={`settings-provider-default-btn-${item.name}`}',
        'data-debug-id="settings-default-agent-provider-select"',
        'data-debug-id="settings-default-agent-tier-select"',
        'data-debug-id="settings-default-agent-save-btn"',
        'Merged multi-daemon provider views are deferred.',
    ])),
    ('first-run daemon modal is skipped when daemon config already exists in localStorage', all(snippet in APP for snippet in [
        "window.localStorage.getItem('odin.daemonUrl')",
        "hasStoredDaemon = Boolean((rawProfiles && rawProfiles !== '[]') || rawDaemonUrl || sessionRef.current?.daemonUrl);",
    ])),
    ('sending to a stopped conversation starts the exact thread with a visible affordance', all(snippet in APP for snippet in [
        'const [sendPhase, setSendPhase] = useState',
        'const shouldRestartForSend = !live;',
        "setSendPhase(shouldRestartForSend ? 'starting' : 'sending');",
        'await daemonApi.startAgent({ daemonUrl: session?.daemonUrl || \'\', agentInstanceId: agent.id',
        'data-debug-id="conversation-composer-starting-indicator"',
    ])),
    ('global attention bell is always available outside the sidebar with badge support', all(snippet in APP for snippet in [
        'data-debug-id="attention-bell-btn"',
        'data-debug-id="attention-bell-badge"',
        "onClick={() => selectSurfaceWithUrl('attention')}",
        '{badgeCount > 99 ? \'99+\' : badgeCount}',
    ])),
    ('dedicated conversation thread page exposes mock-aligned debug ids', all(snippet in APP for snippet in [
        'function ConversationThreadPage',
        'data-debug-id="conversation-thread-page"',
        'data-debug-id="conversation-thread-breadcrumb"',
        'data-debug-id="conversation-thread-project-chip"',
        'data-debug-id="conversation-thread-status-chip"',
        'data-debug-id="conversation-thread-worked-status"',
        'data-debug-id="conversation-composer-shell"',
        'data-debug-id="conversation-composer-input"',
        'data-debug-id="conversation-composer-starting-indicator"',
        'data-debug-id="conversation-provider-select"',
        'data-debug-id="conversation-tier-select"',
        'data-debug-id="conversation-composer-send-btn"',
    ])),
    ('conversation thread page renders only actionable message actions for assistant replies', all(snippet in APP for snippet in [
        'data-debug-id={`conversation-thread-message-actions-${msg.messageId}`}',
        'data-debug-id={`conversation-thread-message-copy-btn-${msg.messageId}`}',
        'group-hover:opacity-100 focus:opacity-100',
    ]) and 'conversation-thread-message-like-btn' not in APP and 'conversation-thread-message-dislike-btn' not in APP),
    ('other chat surfaces use conversation-style transcript and composer patterns', all(snippet in APP + SETTINGS for snippet in [
        'className="chat-scrollbar h-full min-h-0 space-y-[22px] overflow-y-auto rounded-[18px] bg-[#090909] p-5 scroll-smooth"',
        'data-debug-id="agent-detail-chat-composer-shell" className="mt-3 shrink-0 rounded-[15px] border border-white/10 bg-[#141414] p-0 focus-within:border-white/35"',
        'data-debug-id="home-running-agent-chat-composer-shell" className="mt-3 shrink-0 rounded-[15px] border border-white/10 bg-[#141414] p-0 focus-within:border-white/35"',
        'data-debug-id="chain-coordinator-composer-shell" className="mx-auto max-w-[760px] rounded-[15px] border border-white/10 bg-[#141414] p-0 focus-within:border-white/35"',
        'data-debug-id="settings-direct-chat-composer-shell"',
        'data-debug-id="guide-chat-send-btn"',
        'Enter to send · Shift+Enter for newline',
    ])),
    ('global shell does not ship no-op buttons', all(snippet not in APP for snippet in [
        'onClick={() => undefined}',
        'conversation-sidebar-settings-footer-btn',
        'chain-pause-btn',
        'chain-complete-btn',
    ]) and 'data-debug-id="conversation-sidebar-collapse-btn"' in APP and 'onClick={onToggleCollapsed}' in APP),
    ('app scrollbars and chat composer focus borders are neutral gray/white', all(snippet in (ROOT / 'src/ui/styles.css').read_text(encoding='utf-8') for snippet in [
        'scrollbar-color: #525252 var(--fd-surface-1);',
        'scrollbar-color: #525252 #090909;',
        '.chat-scrollbar::-webkit-scrollbar-track',
        'background: #090909;',
        '#737373',
        '#4a4a4a',
        'background: #8a8a8a;',
    ]) and 'focus-within:border-sky-400/70' not in APP + SETTINGS and 'focus-within:border-white/35' in APP and 'focus-within:border-white/35' in SETTINGS),
    ('agent and conversation chat expose toggleable artifact side panels', all(snippet in APP for snippet in [
        'function ChatArtifactsSidePanel',
        'data-debug-id={`${debugPrefix}-artifacts-panel`}',
        'debugIdPrefix={`${debugPrefix}-artifacts-upload`}',
        'data-debug-id={`${debugPrefix}-artifacts-close-btn`}',
        'data-debug-id={`${debugPrefix}-artifact-row-${artifactId}`}',
        'debugId="agent-detail-chat-artifacts-toggle-btn"',
        'debugPrefix="agent-detail-chat"',
        'data-debug-id="conversation-thread-artifacts-toggle-btn"',
        'debugPrefix="conversation-thread"',
        'className="chat-scrollbar min-h-0 flex-1 space-y-2 overflow-y-auto p-3"',
        'className="chat-scrollbar min-w-0 flex-1 overflow-y-auto"',
    ]) and all(snippet in UPLOAD for snippet in [
        'aria-label="Uploading artifact"',
        'inline-block animate-bounce',
    ])),
    ('debug id registry includes conversation sidebar and page ids', all(snippet in AGENTS for snippet in [
        '`sidebar-conversations`',
        '`conversation-focused-sidebar`',
        '`attention-bell-btn`',
        '`attention-bell-badge`',
        '`nav-task-chains-btn`',
        '`nav-projects-btn`',
        '`conversation-sidebar-collapse-btn`',
        '`conversation-sidebar-expand-btn`',
        '`conversation-sidebar-expand-full-btn`',
        '`conversation-collapsed-nav`',
        '`nav-${itemId}-collapsed-btn`',
        '`sidebar-durable-agents`',
        '`sidebar-agent-group-${agentId}`',
        '`sidebar-agent-new-instance-btn-${agentId}`',
        '`sidebar-agent-status-${agentId}`',
        '`sidebar-agent-status-label-${agentId}`',
        '`sidebar-agent-live-instances-${agentId}`',
        '`sidebar-agent-live-instance-row-${agentInstanceId}`',
        '`sidebar-agent-live-instance-status-${agentInstanceId}`',
        '`sidebar-agent-instance-status-${agentInstanceId}`',
        '`sidebar-agent-instance-status-label-${agentInstanceId}`',
        '`sidebar-conversations-paged-list`',
        '`sidebar-conversations-show-more-btn`',
        '`sidebar-conversations-loading`',
        '`sidebar-agents-paged-list`',
        '`sidebar-agents-show-more-btn`',
        '`sidebar-agents-loading`',
        '`sidebar-agent-instances-panel`',
        '`sidebar-agent-instances-launch-row-${agentId}`',
        '`sidebar-agent-instance-row-${agentInstanceId}`',
        '`task-chains-surface`',
        '`task-chains-new-btn`',
        '`task-chains-completed-list`',
        '`projects-surface`',
        '`projects-new-btn`',
        '`sidebar-new-conversation-btn`',
        '`conversation-thread-${agentId}`',
        '`conversation-thread-open-btn-${agentId}`',
        '`AgentIdentityPage`',
        '`agent-identity-page`',
        '`agent-instance-list`',
        '`agent-instance-open-btn-${agentInstanceId}`',
        '`agent-instance-resume-btn-${agentInstanceId}`',
        '`NewConversationPage`',
        '`new-conversation-page`',
        '`new-convo-option-ask-btn`',
        '`new-convo-send-btn`',
        '`chain-view`',
        '`chain-tasks-toggle-btn`',
        '`chain-open-editor-btn`',
        '`chain-workspace-sidebar`',
        '`chain-workspace-close-btn`',
        '`chain-split-view`',
        '`chain-progress-panel`',
        '`settings-modal`',
        '`settings-daemon-add-btn`',
        '`settings-providers-daemon-select`',
        '`settings-provider-default-btn-${providerName}`',
        '`home-running-agent-chat-composer-shell`',
        '`home-running-agent-chat-send-error`',
        '`home-running-agent-chat-upload-error`',
        '`ConversationThreadPage`',
        '`conversation-thread-page`',
        '`agent-detail-chat-artifacts-toggle-btn`',
        '`agent-detail-chat-artifacts-panel`',
        '`agent-detail-chat-artifacts-upload-btn`',
        '`agent-detail-chat-artifacts-close-btn`',
        '`conversation-thread-artifacts-toggle-btn`',
        '`conversation-thread-artifacts-panel`',
        '`conversation-thread-artifacts-upload-btn`',
        '`conversation-thread-artifacts-close-btn`',
        '`conversation-provider-select`',
        '`conversation-composer-input`',
        '`conversation-composer-starting-indicator`',
        '`conversation-composer-send-btn`',
    ])),
]

failed = [name for name, ok in checks if not ok]
if failed:
    for name in failed:
        print(f'FAIL: {name}')
    sys.exit(1)

print(f'PASS: {len(checks)} conversation UI static checks')
