import { Icon } from '@ui';
import ProviderIcon from '../providers/ProviderIcon';
import { normalizeBridgeCapabilities } from '../../api/endpoints/bridgeSupport';
export type RuntimeSelection = { bridgeId: string; provider: string; model: string };
export default function RuntimeConfigurationOptions({ bridges, selection, onChange, disabled, debugPrefix, requireReconfiguration = false }: { bridges: any[]; selection: RuntimeSelection; onChange: (next: RuntimeSelection) => void; disabled?: boolean; debugPrefix: string; requireReconfiguration?: boolean }) {
  const bridge = bridges.find(b => String(b.bridge_id || b.id) === selection.bridgeId);
  const caps = normalizeBridgeCapabilities(bridge);
  const providers = Array.from(new Set([...caps.map(c => c.provider), selection.provider].filter(Boolean)));
  const models = Array.from(new Set([...(caps.find(c => c.provider === selection.provider)?.models || []), selection.model].filter(Boolean)));
  return <div className="space-y-4">
    <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Bridge</h3><div className="grid gap-2 sm:grid-cols-2">{bridges.map(b => {
      const id = String(b.bridge_id || b.id); const selected = id === selection.bridgeId;
      const connected = b.status === 'online' && b.runtime_connected === true;
      const supported = !requireReconfiguration || b.reconfiguration_supported;
      return <button type="button" key={id} data-debug-id={`${debugPrefix}-destination-bridge-option-${id}`} aria-pressed={selected} disabled={disabled || !connected || !supported} onClick={() => onChange({ ...selection, bridgeId: id })} className={`flex min-h-14 items-center justify-between gap-3 rounded-xl border px-3 py-3 text-left disabled:opacity-50 ${selected ? 'border-accent bg-accent/10' : 'border-subtle hover:bg-neutral-soft'}`}><span className="min-w-0"><span className="block break-words text-sm font-medium text-primary">{b.label || b.machine_hostname || id}</span><span className="block text-xs text-muted">{!connected ? 'Disconnected' : !supported ? 'Update required' : 'Connected'}</span></span>{selected ? <Icon name="check" size={18} className="shrink-0 text-accent" /> : null}</button>;
    })}</div>{!bridge && selection.bridgeId ? <p className="mt-2 text-xs text-danger">Selected bridge is unavailable. Choose a connected bridge.</p> : null}</section>
    <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Provider</h3><div className="grid gap-2 sm:grid-cols-2">{providers.map(p => { const available = caps.some(c => c.provider === p); return <button key={p} type="button" data-debug-id={`${debugPrefix}-provider-option-${p}`} aria-pressed={p === selection.provider} disabled={disabled || !available} onClick={() => onChange({ ...selection, provider: p })} className={`flex min-h-14 items-center gap-3 rounded-xl border px-3 py-3 text-left disabled:opacity-50 ${p === selection.provider ? 'border-accent bg-accent/10' : 'border-subtle hover:bg-neutral-soft'}`}><ProviderIcon provider={p} size={18} /><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-primary">{p}</span>{!available ? <span className="text-xs text-muted">Unavailable on selected bridge</span> : null}</span>{p === selection.provider ? <Icon name="check" size={18} className="text-accent" /> : null}</button>; })}</div></section>
    <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Model / tier</h3><div className="grid gap-2 sm:grid-cols-2">{models.map(m => { const available = caps.find(c => c.provider === selection.provider)?.models.includes(m); return <button key={m} type="button" data-debug-id={`${debugPrefix}-model-option-${m}`} aria-pressed={m === selection.model} disabled={disabled || !available} onClick={() => onChange({ ...selection, model: m })} className={`flex min-h-14 items-center justify-between gap-3 rounded-xl border px-3 py-3 text-left disabled:opacity-50 ${m === selection.model ? 'border-accent bg-accent/10' : 'border-subtle hover:bg-neutral-soft'}`}><span className="min-w-0"><span className="block break-words text-sm font-medium text-primary">{m}</span>{!available ? <span className="text-xs text-muted">Unavailable for selected provider</span> : null}</span>{m === selection.model ? <Icon name="check" size={18} className="text-accent" /> : null}</button>; })}</div></section>
  </div>;
}
