package content

import "core:strings"
import contracts "odin_test:contracts"
import domain "odin_test:hub/domain"
import iface "odin_test:hub/repository/iface"
import ownership "odin_test:hub/service/ownership"
import platform "odin_test:hub/platform"

Content_Service :: struct { content: ^iface.Content_Repository, agents: ^iface.Agent_Repository, projects: ^iface.Project_Repository, taskchains: ^iface.Taskchain_Repository, clock: ^platform.Clock, ids: ^platform.ID_Generator }
Memory_Input :: struct { agent_id,type,title,body,evidence,status: string }
Chat_Input :: struct { agent_id,agent_instance_id,chain_id,title,initial_body,artifact_ids_json,bridge_id,provider,tier: string, project_id: domain.Project_ID }
Message_Input :: struct { body,artifact_ids_json: string }
Artifact_Input :: struct { kind,name,description,content_type,content,filename,agent_id,agent_instance_id,chain_id,task_id: string, project_id: domain.Project_ID }
Template_Input :: struct { name,description,persona,instructions: string }

new_content_service :: proc(content: ^iface.Content_Repository, agents: ^iface.Agent_Repository, projects: ^iface.Project_Repository, taskchains: ^iface.Taskchain_Repository, clock: ^platform.Clock, ids: ^platform.ID_Generator) -> Content_Service { return Content_Service{content=content, agents=agents, projects=projects, taskchains=taskchains, clock=clock, ids=ids} }

create_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Memory_Input)->(domain.Memory,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if strings.trim_space(input.body)=="" do return {},false,domain.domain_error(.Validation_Failed,"memory body is required"); if input.agent_id!="" { if !agent_owned(s, owner, input.agent_id) do return {},false,domain.domain_error(.Not_Found,"agent not found") }; now:=platform.clock_now(s.clock); status:=input.status; if status=="" do status="pending"; typ:=input.type; if typ=="" do typ="fact"; m:=domain.Memory{memory_id=platform.generate_id(s.ids,"mem_"),owner_user_id=owner,agent_id=input.agent_id,type=typ,status=status,title=input.title,body=input.body,evidence=input.evidence,created_at=now,updated_at=now}; return iface.content_save_memory(s.content,m) }
list_memories :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Memory,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_memories(s.content,owner) }
get_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context, id:string)->(domain.Memory,bool,domain.Domain_Error){ m,ok,err:=iface.content_get_memory(s.content,id); if !ok do return {},false,err; if ok2,e:=ownership.require_owner(auth,m.owner_user_id); !ok2 do return {},false,e; return m,true,{} }
update_memory_status :: proc(s:^Content_Service, auth:contracts.Auth_Context, id,status:string)->(domain.Memory,bool,domain.Domain_Error){ m,ok,err:=get_memory(s,auth,id); if !ok do return {},false,err; m.status=status; m.updated_at=platform.clock_now(s.clock); return iface.content_save_memory(s.content,m) }
archive_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"archived") }
approve_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"active") }
reject_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"rejected") }

create_conversation :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Chat_Input)->(domain.Chat_Conversation,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if input.agent_id=="" do return {},false,domain.domain_error(.Validation_Failed,"agent_id is required"); if input.agent_instance_id=="" do return {},false,domain.domain_error(.Validation_Failed,"agent_instance_id is required"); if !agent_owned(s,owner,input.agent_id) do return {},false,domain.domain_error(.Not_Found,"agent not found"); if bind_ok,bind_err:=conversation_instance_binding_valid(s,owner,input); !bind_ok do return {},false,bind_err; initial:=Message_Input{body=input.initial_body,artifact_ids_json=input.artifact_ids_json}; if strings.trim_space(input.initial_body)!="" { if msg_ok,msg_err:=validate_initial_message(s,auth,initial); !msg_ok do return {},false,msg_err }; now:=platform.clock_now(s.clock); title:=input.title; if title=="" do title=input.agent_id; c:=domain.Chat_Conversation{conversation_id=platform.generate_id(s.ids,"chat_"),owner_user_id=owner,agent_id=input.agent_id,agent_instance_id=input.agent_instance_id,project_id=input.project_id,chain_id=input.chain_id,title=title,created_at=now,updated_at=now}; saved,save_ok,save_err:=iface.content_save_conversation(s.content,c); if !save_ok do return {},false,save_err; if strings.trim_space(input.initial_body)!="" { _,sent,send_err := send_message(s,auth,saved.conversation_id,initial); if !sent do return {},false,send_err; updated,got,_:=iface.content_get_conversation(s.content,saved.conversation_id); if got do saved=updated }; return saved,true,{} }
list_conversations :: proc(s:^Content_Service, auth:contracts.Auth_Context, limit:int, cursor:string)->([]domain.Chat_Conversation,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_conversations(s.content,owner,limit,cursor) }
get_conversation :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ c,ok,err:=iface.content_get_conversation(s.content,id); if !ok do return {},false,err; if ok2,e:=ownership.require_owner(auth,c.owner_user_id); !ok2 do return {},false,e; return c,true,{} }
get_conversation_by_instance :: proc(s:^Content_Service, auth:contracts.Auth_Context, instance_id:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; rows,list_err:=iface.content_list_conversations(s.content,owner,512,""); if list_err.code!=.None do return {},false,list_err; for c in rows { if c.agent_instance_id==instance_id do return c,true,{} }; return {},false,domain.domain_error(.Not_Found,"conversation not found") }
list_messages :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string,limit:int,cursor:string)->([]domain.Chat_Message,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return nil,err; return iface.content_list_messages(s.content,c.conversation_id,c.owner_user_id,limit,cursor) }
send_message :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string,input:Message_Input)->(domain.Chat_Message,bool,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return {},false,err; if msg_ok,msg_err:=validate_initial_message_for_owner(s,c.owner_user_id,input); !msg_ok do return {},false,msg_err; now:=platform.clock_now(s.clock); m:=domain.Chat_Message{message_id=platform.generate_id(s.ids,"msg_"),conversation_id=c.conversation_id,owner_user_id=c.owner_user_id,direction="user_to_agent",sender_agent_id=c.agent_id,sender_agent_instance_id=c.agent_instance_id,body=input.body,artifact_ids_json=artifact_json_or_empty(input.artifact_ids_json),created_at=now}; saved,save_ok,save_err:=iface.content_save_message(s.content,m); if !save_ok do return {},false,save_err; c.last_message_preview=input.body; c.last_message_at=now; c.updated_at=now; _,_,_=iface.content_save_conversation(s.content,c); return saved,true,{} }
send_agent_message :: proc(s:^Content_Service, auth:contracts.Auth_Context, instance_id:string, input:Message_Input)->(domain.Chat_Message,bool,domain.Domain_Error){ if auth.kind!=.Instance_Token || auth.agent_instance_id=="" || auth.agent_instance_id!=instance_id do return {},false,domain.domain_error(.Forbidden,"instance token is required"); c,ok,err:=get_conversation_by_instance(s,auth,instance_id); if !ok do return {},false,err; if msg_ok,msg_err:=validate_initial_message_for_owner(s,c.owner_user_id,input); !msg_ok do return {},false,msg_err; now:=platform.clock_now(s.clock); m:=domain.Chat_Message{message_id=platform.generate_id(s.ids,"msg_"),conversation_id=c.conversation_id,owner_user_id=c.owner_user_id,direction="agent_to_user",sender_agent_id=c.agent_id,sender_agent_instance_id=c.agent_instance_id,body=input.body,artifact_ids_json=artifact_json_or_empty(input.artifact_ids_json),created_at=now}; saved,save_ok,save_err:=iface.content_save_message(s.content,m); if !save_ok do return {},false,save_err; c.last_message_preview=input.body; c.last_message_at=now; c.unread_count+=1; c.updated_at=now; _,_,_=iface.content_save_conversation(s.content,c); return saved,true,{} }
mark_read :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return {},false,err; c.unread_count=0; c.updated_at=platform.clock_now(s.clock); return iface.content_save_conversation(s.content,c) }
message_body_for_response :: proc(s:^Content_Service, m:domain.Chat_Message)->string{ if artifact_refs_have_missing(s,m.owner_user_id,m.artifact_ids_json) do return strings.concatenate({m.body,"\n[artifact unavailable/deleted]"}); return m.body }

create_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,input:Artifact_Input)->(domain.Artifact,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if ok_ctx,ctx_err:=artifact_context_owned(s,owner,input); !ok_ctx do return {},false,ctx_err; name:=input.name; if name=="" do name=input.filename; if name=="" do name="artifact"; kind:=input.kind; if kind=="" do kind="file"; now:=platform.clock_now(s.clock); a:=domain.Artifact{artifact_id=platform.generate_id(s.ids,"art_"),owner_user_id=owner,kind=kind,name=name,description=input.description,content_type=input.content_type,size_bytes=len(input.content),content=input.content,agent_id=input.agent_id,agent_instance_id=input.agent_instance_id,chain_id=input.chain_id,task_id=input.task_id,project_id=input.project_id,created_at=now,updated_at=now}; return iface.content_save_artifact(s.content,a) }
list_artifacts :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Artifact,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_artifacts(s.content,owner) }
get_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Artifact,bool,domain.Domain_Error){ a,ok,err:=iface.content_get_artifact(s.content,id); if !ok do return {},false,err; if ok2,e:=ownership.require_owner(auth,a.owner_user_id); !ok2 do return {},false,e; return a,true,{} }
update_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id,name,description:string)->(domain.Artifact,bool,domain.Domain_Error){ a,ok,err:=get_artifact(s,auth,id); if !ok do return {},false,err; if name!="" do a.name=name; if description!="" do a.description=description; a.updated_at=platform.clock_now(s.clock); return iface.content_save_artifact(s.content,a) }
delete_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(bool,domain.Domain_Error){ a,ok,err:=get_artifact(s,auth,id); if !ok do return false,err; return iface.content_delete_artifact(s.content,a.artifact_id,a.owner_user_id) }

create_template :: proc(s:^Content_Service, auth:contracts.Auth_Context,input:Template_Input)->(domain.Template,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if input.name=="" do return {},false,domain.domain_error(.Validation_Failed,"template name is required"); now:=platform.clock_now(s.clock); t:=domain.Template{template_id=platform.generate_id(s.ids,"tmpl_"),owner_user_id=owner,name=input.name,description=input.description,persona=input.persona,instructions=input.instructions,created_at=now,updated_at=now}; return iface.content_save_template(s.content,t) }
list_templates :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Template,domain.Domain_Error){
	owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err
	rows, list_err := iface.content_list_templates(s.content,owner)
	if list_err.code != .None do return nil, list_err
	out := make([dynamic]domain.Template)
	append(&out, ..rows)
	append(&out, domain.Template{template_id="tmpl_system_reviewer", is_system=true, name="System Reviewer", description="Built-in read-only reviewer template", persona="You review code for correctness.", instructions="Focus on tests, edge cases, and maintainability."})
	return out[:], {}
}

validate_initial_message :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Message_Input)->(bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return false,err; return validate_initial_message_for_owner(s,owner,input) }
validate_initial_message_for_owner :: proc(s:^Content_Service, owner:domain.User_ID, input:Message_Input)->(bool,domain.Domain_Error){ if strings.trim_space(input.body)=="" do return false,domain.domain_error(.Validation_Failed,"message body is required"); if !artifacts_owned_json(s,owner,input.artifact_ids_json) do return false,domain.domain_error(.Not_Found,"artifact not found"); return true,{} }
agent_owned :: proc(s:^Content_Service, owner:domain.User_ID, agent_id:string)->bool{ if s.agents==nil || agent_id=="" do return false; a,ok,_:=iface.agent_get(s.agents,agent_id); return ok && a.owner_user_id==owner }
conversation_instance_binding_valid :: proc(s:^Content_Service, owner:domain.User_ID, input:Chat_Input)->(bool,domain.Domain_Error){
	if input.agent_instance_id=="" do return true,{}
	if s.agents==nil do return false,domain.domain_error(.Internal_Error,"agent repository is not configured")
	inst,inst_ok,_:=iface.agent_get_instance(s.agents,input.agent_instance_id)
	if !inst_ok || inst.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"agent instance not found")
	if inst.agent_id!=input.agent_id do return false,domain.domain_error(.Conflict,"conversation agent_id must match agent instance")
	if input.chain_id!="" && inst.chain_id!=input.chain_id do return false,domain.domain_error(.Conflict,"conversation chain_id must match agent instance")
	if string(input.project_id)!="" && inst.project_id!=input.project_id do return false,domain.domain_error(.Conflict,"conversation project_id must match agent instance")
	existing,list_err:=iface.content_list_conversations(s.content,owner,256,"")
	if list_err.code!=.None do return false,list_err
	for c in existing { if c.agent_instance_id==input.agent_instance_id do return false,domain.domain_error(.Conflict,"agent instance already has a conversation") }
	return true,{}
}
artifact_context_owned :: proc(s:^Content_Service, owner:domain.User_ID, input:Artifact_Input)->(bool,domain.Domain_Error){
	if input.agent_id!="" && !agent_owned(s,owner,input.agent_id) do return false,domain.domain_error(.Not_Found,"artifact context not found")
	if input.agent_instance_id!="" { if s.agents==nil do return false,domain.domain_error(.Internal_Error,"agent repository is not configured"); inst,ok,_:=iface.agent_get_instance(s.agents,input.agent_instance_id); if !ok || inst.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found"); if input.agent_id!="" && inst.agent_id!=input.agent_id do return false,domain.domain_error(.Conflict,"artifact context is inconsistent"); if string(input.project_id)!="" && inst.project_id!=input.project_id do return false,domain.domain_error(.Conflict,"artifact context is inconsistent") }
	if string(input.project_id)!="" { if s.projects==nil do return false,domain.domain_error(.Internal_Error,"project repository is not configured"); p,ok,_:=iface.project_get(s.projects,input.project_id); if !ok || p.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found") }
	if input.chain_id!="" { if s.taskchains==nil do return false,domain.domain_error(.Internal_Error,"taskchain repository is not configured"); c,ok,_:=iface.taskchain_get_chain(s.taskchains,domain.Task_Chain_ID(input.chain_id)); if !ok || c.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found") }
	if input.task_id!="" { if s.taskchains==nil do return false,domain.domain_error(.Internal_Error,"taskchain repository is not configured"); t,ok,_:=iface.taskchain_get_task(s.taskchains,domain.Task_ID(input.task_id)); if !ok || t.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found"); if input.chain_id!="" && t.chain_id!=domain.Task_Chain_ID(input.chain_id) do return false,domain.domain_error(.Conflict,"artifact context is inconsistent") }
	return true,{}
}
artifact_json_or_empty :: proc(v:string)->string{ if strings.trim_space(v)=="" do return "[]"; return v }
artifacts_owned_json :: proc(s:^Content_Service, owner:domain.User_ID, ids_json:string)->bool{ return !artifact_refs_have_missing(s,owner,ids_json) }
artifact_refs_have_missing :: proc(s:^Content_Service, owner:domain.User_ID, ids_json:string)->bool{ if strings.trim_space(ids_json)=="" || ids_json=="[]" do return false; search:=0; for search<len(ids_json){ rel:=strings.index(ids_json[search:],"\""); if rel<0 do break; start:=search+rel+1; end:=start; for end<len(ids_json)&&ids_json[end]!='"' do end+=1; if end>start { a,ok,_:=iface.content_get_artifact(s.content,ids_json[start:end]); if !ok || a.owner_user_id!=owner do return true }; search=end+1 }; return false }
