package content

import "core:fmt"
import "core:strings"
import contracts "odin_test:contracts"
import domain "odin_test:hub/domain"
import iface "odin_test:hub/repository/iface"
import ownership "odin_test:hub/service/ownership"
import platform "odin_test:hub/platform"
import project_service "odin_test:hub/service/project"

ARTIFACT_MAX_BYTES :: 50 * 1024 * 1024

Content_Service :: struct { content: ^iface.Content_Repository, agents: ^iface.Agent_Repository, bridges: ^iface.Bridge_Repository, projects: ^iface.Project_Repository, taskchains: ^iface.Taskchain_Repository, bridge_command_sink: project_service.Bridge_Command_Sink, clock: ^platform.Clock, ids: ^platform.ID_Generator }
Memory_Input :: struct { agent_id,template_id,bridge_id,title,body,evidence,status: string, project_id: domain.Project_ID, type: domain.Memory_Type }
Chat_Input :: struct { agent_id,agent_instance_id,chain_id,title,initial_body,artifact_ids_json,bridge_id,provider,tier: string, project_id: domain.Project_ID }
Message_Input :: struct { body,artifact_ids_json: string }
Artifact_Input :: struct { kind,name,description,content_type,content,mime,ext,sha256,origin_kind,origin_ref,filename,agent_id,agent_instance_id,chain_id,task_id: string, project_id: domain.Project_ID }
Template_Input :: struct { name,description,persona,instructions: string }

new_content_service :: proc(content: ^iface.Content_Repository, agents: ^iface.Agent_Repository, bridges: ^iface.Bridge_Repository, projects: ^iface.Project_Repository, taskchains: ^iface.Taskchain_Repository, clock: ^platform.Clock, ids: ^platform.ID_Generator) -> Content_Service { return Content_Service{content=content, agents=agents, bridges=bridges, projects=projects, taskchains=taskchains, clock=clock, ids=ids} }
new_content_service_with_runtime :: proc(content: ^iface.Content_Repository, agents: ^iface.Agent_Repository, bridges: ^iface.Bridge_Repository, projects: ^iface.Project_Repository, taskchains: ^iface.Taskchain_Repository, sink: project_service.Bridge_Command_Sink, clock: ^platform.Clock, ids: ^platform.ID_Generator) -> Content_Service { return Content_Service{content=content, agents=agents, bridges=bridges, projects=projects, taskchains=taskchains, bridge_command_sink=sink, clock=clock, ids=ids} }

create_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Memory_Input)->(domain.Memory,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if strings.trim_space(input.body)=="" do return {},false,domain.domain_error(.Validation_Failed,"memory body is required"); if input.type==.Unknown do return {},false,domain.domain_error(.Validation_Failed,"memory type is invalid"); if input.agent_id!="" { if !agent_owned(s, owner, input.agent_id) do return {},false,domain.domain_error(.Not_Found,"agent not found") }; if string(input.project_id)!="" { if !project_owned(s, owner, input.project_id) do return {},false,domain.domain_error(.Not_Found,"project not found") }; if input.template_id!="" { if !template_available(s, owner, input.template_id) do return {},false,domain.domain_error(.Not_Found,"template not found") }; if input.bridge_id!="" { if !bridge_owned(s, owner, input.bridge_id) do return {},false,domain.domain_error(.Not_Found,"bridge not found") }; now:=platform.clock_now(s.clock); status:=input.status; if status=="" do status="pending"; typ:=input.type; if typ==.Unknown do typ=.Fact; m:=domain.Memory{memory_id=platform.generate_id(s.ids,"mem_"),owner_user_id=owner,agent_id=input.agent_id,project_id=input.project_id,template_id=input.template_id,bridge_id=input.bridge_id,type=typ,status=status,title=input.title,body=input.body,evidence=input.evidence,created_at=now,updated_at=now}; return iface.content_save_memory(s.content,m) }
list_memories :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Memory,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_memories(s.content,owner) }
get_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context, id:string)->(domain.Memory,bool,domain.Domain_Error){ m,ok,err:=iface.content_get_memory(s.content,id); if !ok do return {},false,err; if m.owner_user_id=="system" do return m,true,{}; if ok2,e:=ownership.require_owner(auth,m.owner_user_id); !ok2 do return {},false,e; return m,true,{} }
update_memory_status :: proc(s:^Content_Service, auth:contracts.Auth_Context, id,status:string)->(domain.Memory,bool,domain.Domain_Error){ m,ok,err:=iface.content_get_memory(s.content,id); if !ok do return {},false,err; if m.owner_user_id=="system" do return {},false,domain.domain_error(.Forbidden,"system memories are read-only"); if ok2,e:=ownership.require_owner(auth,m.owner_user_id); !ok2 do return {},false,e; m.status=status; m.updated_at=platform.clock_now(s.clock); return iface.content_save_memory(s.content,m) }
archive_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"archived") }
approve_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"active") }
reject_memory :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Memory,bool,domain.Domain_Error){ return update_memory_status(s,auth,id,"rejected") }

create_conversation :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Chat_Input)->(domain.Chat_Conversation,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if input.agent_id=="" do return {},false,domain.domain_error(.Validation_Failed,"agent_id is required"); if input.agent_instance_id=="" do return {},false,domain.domain_error(.Validation_Failed,"agent_instance_id is required"); if !agent_owned(s,owner,input.agent_id) do return {},false,domain.domain_error(.Not_Found,"agent not found"); if bind_ok,bind_err:=conversation_instance_binding_valid(s,owner,input); !bind_ok do return {},false,bind_err; initial:=Message_Input{body=input.initial_body,artifact_ids_json=input.artifact_ids_json}; if strings.trim_space(input.initial_body)!="" { if msg_ok,msg_err:=validate_initial_message(s,auth,initial); !msg_ok do return {},false,msg_err }; now:=platform.clock_now(s.clock); title:=conversation_title_from_input(input.title,input.initial_body,input.agent_id); c:=domain.Chat_Conversation{conversation_id=platform.generate_id(s.ids,"chat_"),owner_user_id=owner,agent_id=input.agent_id,agent_instance_id=input.agent_instance_id,project_id=input.project_id,chain_id=input.chain_id,title=title,created_at=now,updated_at=now}; saved,save_ok,save_err:=iface.content_save_conversation(s.content,c); if !save_ok do return {},false,save_err; if strings.trim_space(input.initial_body)!="" { _,sent,send_err := send_message(s,auth,saved.conversation_id,initial); if !sent do return {},false,send_err; updated,got,_:=iface.content_get_conversation(s.content,saved.conversation_id); if got do saved=updated }; return saved,true,{} }
list_conversations :: proc(s:^Content_Service, auth:contracts.Auth_Context, limit:int, cursor:string)->([]domain.Chat_Conversation,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_conversations(s.content,owner,limit,cursor) }
get_conversation :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ c,ok,err:=iface.content_get_conversation(s.content,id); if !ok do return {},false,err; if ok2,e:=ownership.require_owner(auth,c.owner_user_id); !ok2 do return {},false,e; return c,true,{} }
update_conversation_title :: proc(s:^Content_Service, auth:contracts.Auth_Context,id,title:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,id); if !ok do return {},false,err; next_title:=strings.trim_space(title); if next_title=="" do return {},false,domain.domain_error(.Validation_Failed,"conversation title is required"); if len(next_title)>120 do return {},false,domain.domain_error(.Validation_Failed,"conversation title is too long"); c.title=next_title; c.updated_at=platform.clock_now(s.clock); return iface.content_save_conversation(s.content,c) }
get_conversation_by_instance :: proc(s:^Content_Service, auth:contracts.Auth_Context, instance_id:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; rows,list_err:=iface.content_list_conversations(s.content,owner,512,""); if list_err.code!=.None do return {},false,list_err; for c in rows { if c.agent_instance_id==instance_id do return c,true,{} }; return {},false,domain.domain_error(.Not_Found,"conversation not found") }
list_messages :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string,limit:int,cursor:string)->([]domain.Chat_Message,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return nil,err; return iface.content_list_messages(s.content,c.conversation_id,c.owner_user_id,limit,cursor) }
list_user_visible_messages :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string,limit:int,cursor:string)->([]domain.Chat_Message,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return nil,err; return iface.content_list_user_visible_messages(s.content,c.conversation_id,c.owner_user_id,limit,cursor) }
send_message :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string,input:Message_Input)->(domain.Chat_Message,bool,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return {},false,err; if msg_ok,msg_err:=validate_initial_message_for_owner(s,c.owner_user_id,input); !msg_ok do return {},false,msg_err; now:=platform.clock_now(s.clock); m:=domain.Chat_Message{message_id=platform.generate_id(s.ids,"msg_"),conversation_id=c.conversation_id,owner_user_id=c.owner_user_id,direction="user_to_agent",sender_agent_id=c.agent_id,sender_agent_instance_id=c.agent_instance_id,body=input.body,artifact_ids_json=artifact_json_or_empty(input.artifact_ids_json),created_at=now}; saved,save_ok,save_err:=iface.content_save_message(s.content,m); if !save_ok do return {},false,save_err; c.last_message_preview=input.body; c.last_message_at=now; c.updated_at=now; _,_,_=iface.content_save_conversation(s.content,c); notify_agent_message(s,c,"user_to_agent","user",saved.message_id); return saved,true,{} }
send_agent_message :: proc(s:^Content_Service, auth:contracts.Auth_Context, instance_id:string, input:Message_Input)->(domain.Chat_Message,bool,domain.Domain_Error){ if auth.kind!=.Instance_Token || auth.agent_instance_id=="" || auth.agent_instance_id!=instance_id do return {},false,domain.domain_error(.Forbidden,"instance token is required"); c,ok,err:=get_conversation_by_instance(s,auth,instance_id); if !ok do return {},false,err; if msg_ok,msg_err:=validate_initial_message_for_owner(s,c.owner_user_id,input); !msg_ok do return {},false,msg_err; now:=platform.clock_now(s.clock); m:=domain.Chat_Message{message_id=platform.generate_id(s.ids,"msg_"),conversation_id=c.conversation_id,owner_user_id=c.owner_user_id,direction="agent_to_user",sender_agent_id=c.agent_id,sender_agent_instance_id=c.agent_instance_id,body=input.body,artifact_ids_json=artifact_json_or_empty(input.artifact_ids_json),created_at=now}; saved,save_ok,save_err:=iface.content_save_message(s.content,m); if !save_ok do return {},false,save_err; c.last_message_preview=input.body; c.last_message_at=now; c.unread_count+=1; c.updated_at=now; _,_,_=iface.content_save_conversation(s.content,c); return saved,true,{} }
send_agent_to_agent :: proc(s:^Content_Service, auth:contracts.Auth_Context, target_instance_id:string, input:Message_Input)->(domain.Chat_Message,bool,domain.Domain_Error){ if auth.kind!=.Instance_Token || auth.agent_instance_id=="" do return {},false,domain.domain_error(.Forbidden,"instance token is required"); if strings.trim_space(target_instance_id)=="" do return {},false,domain.domain_error(.Validation_Failed,"to_instance is required"); if s.agents==nil do return {},false,domain.domain_error(.Internal_Error,"agent repository is not configured"); sender, sender_ok, _ := iface.agent_get_instance(s.agents, auth.agent_instance_id); if !sender_ok do return {},false,domain.domain_error(.Not_Found,"sender instance not found"); target, target_ok, _ := iface.agent_get_instance(s.agents, target_instance_id); if !target_ok || target.owner_user_id!=sender.owner_user_id do return {},false,domain.domain_error(.Not_Found,"target instance not found"); c,conv_ok,conv_err:=get_conversation_by_instance(s,contracts.Auth_Context{kind=.User_Token,user_id=string(target.owner_user_id)},target.agent_instance_id); if !conv_ok do return {},false,conv_err; if msg_ok,msg_err:=validate_initial_message_for_owner(s,c.owner_user_id,input); !msg_ok do return {},false,msg_err; now:=platform.clock_now(s.clock); m:=domain.Chat_Message{message_id=platform.generate_id(s.ids,"msg_"),conversation_id=c.conversation_id,owner_user_id=c.owner_user_id,direction="agent_to_agent",sender_agent_id=sender.agent_id,sender_agent_instance_id=sender.agent_instance_id,body=input.body,artifact_ids_json=artifact_json_or_empty(input.artifact_ids_json),created_at=now}; saved,save_ok,save_err:=iface.content_save_message(s.content,m); if !save_ok do return {},false,save_err; notify_agent_message(s,c,"agent_to_agent",sender.agent_instance_id,saved.message_id); return saved,true,{} }
mark_read :: proc(s:^Content_Service, auth:contracts.Auth_Context,cid:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ c,ok,err:=get_conversation(s,auth,cid); if !ok do return {},false,err; c.unread_count=0; c.updated_at=platform.clock_now(s.clock); return iface.content_save_conversation(s.content,c) }
message_body_for_response :: proc(s:^Content_Service, m:domain.Chat_Message)->string{ if artifact_refs_have_missing(s,m.owner_user_id,m.artifact_ids_json) do return strings.concatenate({m.body,"\n[artifact unavailable/deleted]"}); return m.body }

create_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,input:Artifact_Input)->(domain.Artifact,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if len(input.content)>ARTIFACT_MAX_BYTES do return {},false,domain.domain_error(.Validation_Failed,fmt.tprintf("artifact is too large; maximum size is %d MB", ARTIFACT_MAX_BYTES/(1024*1024))); if ok_ctx,ctx_err:=artifact_context_owned(s,owner,input); !ok_ctx do return {},false,ctx_err; name:=input.name; if name=="" do name=input.filename; if name=="" do name="artifact"; kind:=input.kind; if kind=="" do kind="file"; now:=platform.clock_now(s.clock); a:=domain.Artifact{artifact_id=platform.generate_id(s.ids,"art_"),owner_user_id=owner,kind=kind,name=name,description=input.description,content_type=input.content_type,size_bytes=len(input.content),content=input.content,mime=input.mime,ext=input.ext,sha256=input.sha256,origin_kind=input.origin_kind,origin_ref=input.origin_ref,agent_id=input.agent_id,agent_instance_id=input.agent_instance_id,chain_id=input.chain_id,task_id=input.task_id,project_id=input.project_id,created_at=now,updated_at=now}; return iface.content_save_artifact(s.content,a) }
list_artifacts :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Artifact,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err; return iface.content_list_artifacts(s.content,owner) }
get_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(domain.Artifact,bool,domain.Domain_Error){ a,ok,err:=iface.content_get_artifact(s.content,id); if !ok do return {},false,err; if ok2,e:=ownership.require_owner(auth,a.owner_user_id); !ok2 do return {},false,e; return a,true,{} }
update_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id,name,description:string)->(domain.Artifact,bool,domain.Domain_Error){ a,ok,err:=get_artifact(s,auth,id); if !ok do return {},false,err; if name!="" do a.name=name; if description!="" do a.description=description; a.updated_at=platform.clock_now(s.clock); return iface.content_save_artifact(s.content,a) }
delete_artifact :: proc(s:^Content_Service, auth:contracts.Auth_Context,id:string)->(bool,domain.Domain_Error){ a,ok,err:=get_artifact(s,auth,id); if !ok do return false,err; return iface.content_delete_artifact(s.content,a.artifact_id,a.owner_user_id) }

create_template :: proc(s:^Content_Service, auth:contracts.Auth_Context,input:Template_Input)->(domain.Template,bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return {},false,err; if input.name=="" do return {},false,domain.domain_error(.Validation_Failed,"template name is required"); now:=platform.clock_now(s.clock); t:=domain.Template{template_id=platform.generate_id(s.ids,"tmpl_"),owner_user_id=owner,name=input.name,description=input.description,persona=input.persona,instructions=input.instructions,created_at=now,updated_at=now}; return iface.content_save_template(s.content,t) }
list_templates :: proc(s:^Content_Service, auth:contracts.Auth_Context)->([]domain.Template,domain.Domain_Error){
	owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return nil,err
	rows, list_err := iface.content_list_templates(s.content,owner)
	if list_err.code != .None do return nil, list_err
	out := make([dynamic]domain.Template)
	append(&out, ..rows)
	append(&out, domain.Template{template_id="tmpl_system_reviewer", is_system=true, name="System Reviewer", description="Built-in read-only reviewer template", persona="You review code for correctness.", instructions="Focus on tests, edge cases, and maintainability."})
	return out[:], {}
}

validate_initial_message :: proc(s:^Content_Service, auth:contracts.Auth_Context, input:Message_Input)->(bool,domain.Domain_Error){ owner,ok,err:=ownership.owner_from_auth(auth); if !ok do return false,err; return validate_initial_message_for_owner(s,owner,input) }
validate_initial_message_for_owner :: proc(s:^Content_Service, owner:domain.User_ID, input:Message_Input)->(bool,domain.Domain_Error){ if strings.trim_space(input.body)=="" do return false,domain.domain_error(.Validation_Failed,"message body is required"); if !artifacts_owned_json(s,owner,input.artifact_ids_json) do return false,domain.domain_error(.Not_Found,"artifact not found"); return true,{} }
agent_owned :: proc(s:^Content_Service, owner:domain.User_ID, agent_id:string)->bool{ if s.agents==nil || agent_id=="" do return false; a,ok,_:=iface.agent_get(s.agents,agent_id); return ok && a.owner_user_id==owner }
project_owned :: proc(s:^Content_Service, owner:domain.User_ID, project_id:domain.Project_ID)->bool{ if s.projects==nil || string(project_id)=="" do return false; p,ok,_:=iface.project_get(s.projects,project_id); return ok && p.owner_user_id==owner }
template_available :: proc(s:^Content_Service, owner:domain.User_ID, template_id:string)->bool{ if s.content==nil || template_id=="" do return false; if template_id=="tmpl_system_reviewer" do return true; t,ok,_:=iface.content_get_template(s.content,template_id); return ok && (t.is_system || t.owner_user_id==owner) }
bridge_owned :: proc(s:^Content_Service, owner:domain.User_ID, bridge_id:string)->bool{ if s.bridges==nil || bridge_id=="" do return false; b,ok,_:=iface.bridge_get_bridge(s.bridges,bridge_id); return ok && b.owner_user_id==owner }
conversation_instance_binding_valid :: proc(s:^Content_Service, owner:domain.User_ID, input:Chat_Input)->(bool,domain.Domain_Error){
	if input.agent_instance_id=="" do return true,{}
	if s.agents==nil do return false,domain.domain_error(.Internal_Error,"agent repository is not configured")
	inst,inst_ok,_:=iface.agent_get_instance(s.agents,input.agent_instance_id)
	if !inst_ok || inst.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"agent instance not found")
	if inst.agent_id!=input.agent_id do return false,domain.domain_error(.Conflict,"conversation agent_id must match agent instance")
	if input.chain_id!="" && inst.chain_id!=input.chain_id do return false,domain.domain_error(.Conflict,"conversation chain_id must match agent instance")
	if string(input.project_id)!="" && inst.project_id!=input.project_id do return false,domain.domain_error(.Conflict,"conversation project_id must match agent instance")
	existing,list_err:=iface.content_list_conversations(s.content,owner,256,"")
	if list_err.code!=.None do return false,list_err
	for c in existing { if c.agent_instance_id==input.agent_instance_id do return false,domain.domain_error(.Conflict,"agent instance already has a conversation") }
	return true,{}
}
artifact_context_owned :: proc(s:^Content_Service, owner:domain.User_ID, input:Artifact_Input)->(bool,domain.Domain_Error){
	if input.agent_id!="" && !agent_owned(s,owner,input.agent_id) do return false,domain.domain_error(.Not_Found,"artifact context not found")
	if input.agent_instance_id!="" { if s.agents==nil do return false,domain.domain_error(.Internal_Error,"agent repository is not configured"); inst,ok,_:=iface.agent_get_instance(s.agents,input.agent_instance_id); if !ok || inst.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found"); if input.agent_id!="" && inst.agent_id!=input.agent_id do return false,domain.domain_error(.Conflict,"artifact context is inconsistent"); if string(input.project_id)!="" && inst.project_id!=input.project_id do return false,domain.domain_error(.Conflict,"artifact context is inconsistent") }
	if string(input.project_id)!="" { if s.projects==nil do return false,domain.domain_error(.Internal_Error,"project repository is not configured"); p,ok,_:=iface.project_get(s.projects,input.project_id); if !ok || p.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found") }
	if input.chain_id!="" { if s.taskchains==nil do return false,domain.domain_error(.Internal_Error,"taskchain repository is not configured"); c,ok,_:=iface.taskchain_get_chain(s.taskchains,domain.Task_Chain_ID(input.chain_id)); if !ok || c.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found") }
	if input.task_id!="" { if s.taskchains==nil do return false,domain.domain_error(.Internal_Error,"taskchain repository is not configured"); t,ok,_:=iface.taskchain_get_task(s.taskchains,domain.Task_ID(input.task_id)); if !ok || t.owner_user_id!=owner do return false,domain.domain_error(.Not_Found,"artifact context not found"); if input.chain_id!="" && t.chain_id!=domain.Task_Chain_ID(input.chain_id) do return false,domain.domain_error(.Conflict,"artifact context is inconsistent") }
	return true,{}
}
conversation_title_from_input :: proc(explicit_title, initial_body, fallback: string) -> string {
	seed := strings.trim_space(explicit_title)
	if seed == "" do seed = strings.trim_space(initial_body)
	if seed == "" do seed = fallback
	b := strings.builder_make()
	last_space := false
	written := 0
	for i := 0; i < len(seed) && written < 120; i += 1 {
		ch := seed[i]
		is_space := ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r'
		if is_space {
			if !last_space { strings.write_byte(&b, ' '); last_space = true; written += 1 }
		} else {
			strings.write_byte(&b, ch); last_space = false; written += 1
		}
	}
	return strings.trim_space(strings.to_string(b))
}
artifact_json_or_empty :: proc(v:string)->string{ if strings.trim_space(v)=="" do return "[]"; return v }
artifacts_owned_json :: proc(s:^Content_Service, owner:domain.User_ID, ids_json:string)->bool{ return !artifact_refs_have_missing(s,owner,ids_json) }
artifact_refs_have_missing :: proc(s:^Content_Service, owner:domain.User_ID, ids_json:string)->bool{ if strings.trim_space(ids_json)=="" || ids_json=="[]" do return false; search:=0; for search<len(ids_json){ rel:=strings.index(ids_json[search:],"\""); if rel<0 do break; start:=search+rel+1; end:=start; for end<len(ids_json)&&ids_json[end]!='"' do end+=1; if end>start { a,ok,_:=iface.content_get_artifact(s.content,ids_json[start:end]); if !ok || a.owner_user_id!=owner do return true }; search=end+1 }; return false }

notify_agent_message :: proc(s:^Content_Service, c:domain.Chat_Conversation, direction,sender_instance_id,message_id:string){ if s==nil || s.agents==nil || s.bridge_command_sink.send_runtime_command==nil do return; inst,ok,_:=iface.agent_get_instance(s.agents,c.agent_instance_id); if !ok || inst.bridge_id=="" do return; command_id:=platform.generate_id(s.ids,"cmd_"); b:=strings.builder_make(); strings.write_string(&b,"{\"type\":\"notify_agent_message\",\"command_id\":\""); content_json_write(&b,command_id); strings.write_string(&b,"\",\"bridge_id\":\""); content_json_write(&b,inst.bridge_id); strings.write_string(&b,"\",\"agent_instance_id\":\""); content_json_write(&b,c.agent_instance_id); strings.write_string(&b,"\",\"conversation_id\":\""); content_json_write(&b,c.conversation_id); strings.write_string(&b,"\",\"message_id\":\""); content_json_write(&b,message_id); strings.write_string(&b,"\",\"direction\":\""); content_json_write(&b,direction); strings.write_string(&b,"\",\"sender\":\""); content_json_write(&b,sender_instance_id); strings.write_string(&b,"\",\"sender_agent_instance_id\":\""); content_json_write(&b,sender_instance_id); strings.write_string(&b,"\",\"unread_count\":"); strings.write_string(&b,fmt.tprintf("%d",c.unread_count)); strings.write_string(&b,"}"); _,_=project_service.bridge_command_send_runtime(s.bridge_command_sink,project_service.Runtime_Command{bridge_id=inst.bridge_id,command_id=command_id,body_json=strings.to_string(b)}) }
content_json_write :: proc(b:^strings.Builder, v:string){ for ch in v { switch ch { case '\\': strings.write_string(b,"\\\\"); case '"': strings.write_string(b,"\\\""); case '\n': strings.write_string(b,"\\n"); case '\r': strings.write_string(b,"\\r"); case '\t': strings.write_string(b,"\\t"); case: strings.write_rune(b,ch) } } }
