ALTER TABLE artifacts ADD COLUMN mime TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN ext TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN sha256 TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN origin_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN origin_ref TEXT NOT NULL DEFAULT '';
ALTER TABLE artifacts ADD COLUMN deleted_at TEXT;
