ALTER TABLE memories ADD COLUMN project_id TEXT NOT NULL DEFAULT '';
ALTER TABLE memories ADD COLUMN template_id TEXT NOT NULL DEFAULT '';
ALTER TABLE memories ADD COLUMN bridge_id TEXT NOT NULL DEFAULT '';
