ALTER TABLE bridges ADD COLUMN version TEXT NOT NULL DEFAULT '';
ALTER TABLE bridges ADD COLUMN commit_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE bridges ADD COLUMN build_timestamp TEXT NOT NULL DEFAULT '';
ALTER TABLE bridges ADD COLUMN update_status TEXT NOT NULL DEFAULT 'idle';
ALTER TABLE bridges ADD COLUMN update_error TEXT NOT NULL DEFAULT '';
