package main

import "core:fmt"
import "core:strings"
import vcs "odin_test:lib/vcs"

TASK_CHAIN_BEST_PRACTICES :: `## Task Chain Best Practices

When coordinating a task chain, you must adhere to the following workflow upon task completion:

1. **Verify All Tasks:** Review the outputs of all individual tasks in this chain to ensure they are fully complete, correct, and work together.
2. **Submit Verifiable Evidence:** When moving the task chain to 'completed' (using the 'ham-ctl task-chains status --status completed --final-summary "..."' command), you must provide a comprehensive, high-fidelity final summary. This summary MUST include:
   - **Verifiable Results/Evidence:** Specific outputs, behavior descriptions, or test logs proving correctness.
   - **Git Commits:** The hashes of all commits created or reviewed as part of this task chain.
   - **File Paths:** Precise relative or absolute paths of the files modified or created.
   - **Result Summary:** A concise overview of the accomplishments.
3. **Propose Quality Rating:** Propose a quality rating status of 'good' or 'bad' for this task chain.
4. **Reasoning:** Provide clear, objective engineering rationale explaining why the chain succeeded ('good') or if there were critical defects or difficulties encountered ('bad').`

Task_Service_Result :: struct {
	ok:          bool,
	status_code: int,
	message:     string,
}

task_service_create_task :: proc(cmd: Task_Create_Command) -> Task_Service_Result {
	if cmd.task_id != "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task_id is generated by daemon; omit task_id on create"}`}
	}
	if cmd.title == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task create requires title"}`}
	}
	if cmd.assignee_agent_instance_id != "" && cmd.assignee_agent_instance_id == cmd.reviewer_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the reviewer"}`}
	}
	if cmd.assignee_agent_instance_id != "" && cmd.reviewer_agent_instance_id == "" && cmd.chain_id != "" && task_chain_default_reviewer_agent_instance_id(cmd.chain_id) == cmd.assignee_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	task_id := task_generate_id()
	status := cmd.status
	if status == "" do status = "planning"
	if !task_status_allowed(status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if status == "ready" || status == "in_progress" {
		if dep_blockers := task_dependency_blocking_ids(cmd.depends_on); dep_blockers != "" {
			return task_gating_error("dependency", "unmet task dependencies", dep_blockers)
		}
		if cmd.assignee_agent_instance_id != "" {
			if active := task_active_slot_blocker(cmd.assignee_agent_instance_id, ""); active != "" {
				return task_gating_error("assignee_active_task", "assignee already has an active task", active)
			}
		}
	}
	chain_id      := cmd.chain_id
	created_chain := false
	if chain_id == "" && !cmd.standalone {
		chain_id = task_chain_id_for_root(task_id)
		chain_event := Task_Event{
			kind                        = .Chain_Created,
			chain_id                    = chain_id,
			project_id                  = cmd.project_id,
			title                       = cmd.title,
			description                 = cmd.description,
			status                      = "planning",
			coordinator_agent_instance_id = cmd.created_by,
			author_agent_instance_id    = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(chain_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task chain create failed"}`}
		}
		created_chain = true
	}
	priority := cmd.priority
	if priority == "" do priority = "normal"
	event := Task_Event{
		kind                          = .Task_Created,
		task_id                       = task_id,
		chain_id                      = chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		acceptance_criteria           = cmd.acceptance_criteria,
		priority                      = priority,
		status                        = status,
		assignee_agent_instance_id    = cmd.assignee_agent_instance_id,
		reviewer_agent_instance_id    = cmd.reviewer_agent_instance_id,
		depends_on                    = cmd.depends_on,
		created_by                    = cmd.created_by,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task create failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`);    json_write_string(&b, task_id)
	strings.write_string(&b, `","chain_id":"`);            json_write_string(&b, chain_id)
	strings.write_string(&b, `","root_task_id":"`);        json_write_string(&b, task_root_id_for_response(chain_id, task_id, created_chain))
	strings.write_string(&b, `","created_chain":`);        strings.write_string(&b, "true" if created_chain else "false")
	strings.write_string(&b, `,"standalone":`);            strings.write_string(&b, "true" if cmd.standalone else "false")
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_create_chain :: proc(cmd: Task_Chain_Create_Command) -> Task_Service_Result {
	if cmd.title == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain create requires title"}`}
	}
	if cmd.coordinator_agent_instance_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain create requires coordinator_agent_instance_id"}`}
	}
	if cmd.default_reviewer_agent_instance_id != "" && cmd.default_reviewer_agent_instance_id == cmd.coordinator_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	if cmd.kind == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain create requires kind"}`}
	}
	chain_id := cmd.chain_id
	if chain_id == "" do chain_id = task_generate_chain_id()
	team_id := team_service_create_for_chain(cmd.project_id, chain_id, cmd.kind, "")
	if team_id == "" {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"team allocation failed"}`}
	}
	workspace_id := ""
	if cmd.wants_vcs {
		if workspace, workspace_ok, workspace_msg := task_service_maybe_provision_workspace(cmd.project_id, chain_id, team_id, cmd.title); workspace_ok {
			workspace_id = workspace.workspace_id
		} else if workspace_msg != "no vcs" {
			_ = team_service_archive(team_id, "workspace_provision_failed")
			return Task_Service_Result{ok = false, status_code = 500, message = task_service_error_json(workspace_msg)}
		}
	}
	event := Task_Event{
		kind                          = .Chain_Created,
		chain_id                      = chain_id,
		project_id                    = cmd.project_id,
		team_id                       = team_id,
		vcs_workspace_id              = workspace_id,
		title                         = cmd.title,
		description                   = cmd.description,
		status                        = "planning",
		coordinator_agent_instance_id = cmd.coordinator_agent_instance_id,
		reviewer_agent_instance_id    = cmd.default_reviewer_agent_instance_id,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		if workspace_id != "" do task_service_cleanup_workspace(chain_id)
		_ = team_service_archive(team_id, "chain_create_failed")
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain create failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"chain_id":"`); json_write_string(&b, chain_id)
	strings.write_string(&b, `","team_id":"`); json_write_string(&b, team_id)
	strings.write_string(&b, `","vcs_workspace_id":"`); json_write_string(&b, workspace_id)
	strings.write_string(&b, `","status":"planning"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_cleanup_workspace :: proc(chain_id: string) {
	if rec, ok := vcs_db_workspace_for_chain(chain_id); ok {
		backend := vcs.vcs_backend_for(vcs_handle_from_record(rec).kind)
		_, _ = backend.workspace_remove(vcs_handle_from_record(rec), true)
		_ = vcs_db_delete_workspace(chain_id)
	}
}

task_service_error_json :: proc(message: string) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message); strings.write_string(&b, `"}`)
	return strings.to_string(b)
}

task_service_maybe_provision_workspace :: proc(project_id, chain_id, team_id, title: string) -> (Vcs_Workspace_Record, bool, string) {
	project_idx := project_index(project_id)
	if project_idx < 0 do return Vcs_Workspace_Record{}, false, "no vcs"
	project := project_records[project_idx]
	kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "git_repo", "")
	if kind == "none" || repo == "" do return Vcs_Workspace_Record{}, false, "no vcs"
	backend_kind := vcs.Vcs_Kind.Git
	if kind == "jj" do backend_kind = .Jj
	if kind == "auto" {
		jj_detected := vcs.vcs_backend_for(.Jj).detect(repo)
		if jj_detected.ok do backend_kind = .Jj
		else do backend_kind = .Git
	}
	backend := vcs.vcs_backend_for(backend_kind)
	detected := backend.detect(repo)
	if !detected.ok do return Vcs_Workspace_Record{}, false, detected.message
	base_ref := project_anchor_value(project, "base_ref", detected.base_ref)
	if base_ref == "" do base_ref = detected.base_ref
	root := project_anchor_value(project, "worktree_root", fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id))
	name := fmt.tprintf("team/%s/%s", team_id, task_chain_slug(title, chain_id))
	handle, ok, msg := backend.workspace_add(detected.repo_root, name, base_ref, root)
	if !ok do return Vcs_Workspace_Record{}, false, msg
	now := router_now_unix_ms()
	rec := Vcs_Workspace_Record{workspace_id=fmt.tprintf("ws_%s", chain_id), chain_id=chain_id, project_id=project_id, vcs_kind="git", path=handle.path, branch_or_change=handle.branch_or_change, base_ref=handle.base_ref, status="clean", created_unix_ms=now, updated_unix_ms=now}
	if backend_kind == .Jj do rec.vcs_kind = "jj"
	if !vcs_db_insert_workspace(rec) {
		_, _ = backend.workspace_remove(handle, true)
		return Vcs_Workspace_Record{}, false, "persist workspace failed"
	}
	return rec, true, "ok"
}

project_anchor_value :: proc(project: Project_Record, anchor_type, default_value: string) -> string {
	for i in 0..<project.anchor_count { if project.anchors[i].type == anchor_type do return project.anchors[i].value }
	return default_value
}

task_chain_slug :: proc(title, chain_id: string) -> string {
	b := strings.builder_make()
	for r in strings.to_lower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') do strings.write_rune(&b, r)
		else if r == '-' || r == '_' || r == ' ' do strings.write_byte(&b, '-')
		if len(strings.to_string(b)) >= 40 do break
	}
	out := strings.trim(strings.to_string(b), "-")
	if out == "" {
		if len(chain_id) > 8 do return chain_id[len(chain_id)-8:]
		return chain_id
	}
	return strings.clone(out)
}

task_service_activate_chain :: proc(cmd: Task_Chain_Activate_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"activate requires chain_id"}`}
	}
	chain_idx, found := task_existing_chain_index(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	chain := task_chains[chain_idx]
	if chain.status != "planning" {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"only planning chains can be activated"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = cmd.chain_id,
		status                   = "in_progress",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain activate failed"}`}
	}
	task_notify_event(event)
	task_recompute_promotions(cmd.author_agent_instance_id)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_comment :: proc(task_id, chain_id, body, author: string) -> Task_Service_Result {
	return task_service_comment_command(Task_Comment_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author})
}

task_service_comment_command :: proc(cmd: Task_Comment_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.body == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task comment requires task_id and body"}`}
	}
	comment_id := fmt.tprintf("cmt_%d", router_now_unix_ms())
	event := Task_Event{
		kind                     = .Task_Comment,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = comment_id,
		body                     = cmd.body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task comment failed"}`}
	}
	task_notify_event(event)

	if idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id); found {
		state := task_states[idx]
		if state.status == .Approved {
			back_event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = cmd.task_id,
				chain_id                 = state.chain_id,
				status                   = "queued",
				body                     = fmt.tprintf("reverted to ready due to unresolved comment: %s", cmd.body),
				author_agent_instance_id = "system-comment-revert",
			}
			if task_store_append_event(back_event) {
				task_notify_event(back_event)
				if state.chain_id != "" {
					if c_idx, c_found := task_existing_chain_index(state.chain_id); c_found {
						if task_chains[c_idx].status == "reviewing" {
							chain_event := Task_Event{
								kind                     = .Chain_Status_Changed,
								chain_id                 = state.chain_id,
								status                   = "in_progress",
								body                     = "reverted chain to in_progress due to task comment revert",
								author_agent_instance_id = "system-comment-revert",
							}
							if task_store_append_event(chain_event) {
								task_notify_event(chain_event)
							}
						}
					}
				}
				task_recompute_promotions("system-comment-revert")
				task_service_auto_claim(cmd.task_id)
			}
		}
	}

	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"comment_id":"`); json_write_string(&b, comment_id); strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_comment_resolve :: proc(cmd: Task_Comment_Resolve_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"comment resolve requires task_id and comment_id"}`}
	}
	found := false
	for i in 0..<task_comment_count {
		if task_comments[i].task_id == cmd.task_id && task_comments[i].comment_id == cmd.comment_id {
			found = true
			break
		}
	}
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"comment not found"}`}
	}
	event := Task_Event{
		kind                     = .Task_Comment_Resolved,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = cmd.comment_id,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append comment resolve failed"}`}
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_assign :: proc(task_id, chain_id, agent_instance_id, author: string) -> Task_Service_Result {
	return task_service_assign_command(Task_Assign_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, author_agent_instance_id = author})
}

task_service_assign_command :: proc(cmd: Task_Assign_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task assignment requires task_id and agent_instance_id"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	state := task_states[idx]
	if task_actor_has_role(state, cmd.agent_instance_id, "lgtm_required") || task_actor_has_role(state, cmd.agent_instance_id, "lgtm_optional") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is already a reviewer"}`}
	}
	if task_chain_default_reviewer_agent_instance_id(state.chain_id) == cmd.agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	if task_status_active_for_assignee(state) {
		if active := task_active_slot_blocker(cmd.agent_instance_id, state.task_id); active != "" {
			return task_gating_error("assignee_active_task", "assignee already has an active task", active)
		}
	}
	event := Task_Event{
		kind                     = .Task_Assigned,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = cmd.agent_instance_id,
		role                     = "assignee",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task assignment failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_add_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant requires task_id, agent_instance_id, and role"}`}
	}
	switch cmd.role {
	case "assignee", "lgtm_required", "lgtm_optional", "coordinator", "subscriber":
	case:
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"role must be assignee, lgtm_required, lgtm_optional, coordinator, or subscriber"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	state := task_states[idx]
	if (cmd.role == "lgtm_required" || cmd.role == "lgtm_optional") && state.assignee_agent_instance_id == cmd.agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be a reviewer"}`}
	}
	if cmd.role == "assignee" && (task_actor_has_role(state, cmd.agent_instance_id, "lgtm_required") || task_actor_has_role(state, cmd.agent_instance_id, "lgtm_optional")) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer cannot be the assignee"}`}
	}
	if cmd.role == "assignee" && task_chain_default_reviewer_agent_instance_id(state.chain_id) == cmd.agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee"}`}
	}
	event := Task_Event{
		kind                     = .Task_Participant_Added,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = cmd.agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_remove_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_remove_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_remove_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant removal requires task_id, agent_instance_id, and role"}`}
	}
	event := Task_Event{
		kind                     = .Task_Participant_Removed,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = cmd.agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant removal failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_update_task :: proc(cmd: Task_Update_Command) -> Task_Service_Result {
	if cmd.task_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task update requires task_id"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	current := task_states[idx]
	title := cmd.title
	if title == "" do title = current.title
	description := current.description
	if cmd.description_present do description = cmd.description
	audit_body := fmt.tprintf("metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, current.description, description)
	event := Task_Event{
		kind                     = .Task_Metadata_Updated,
		task_id                  = cmd.task_id,
		chain_id                 = current.chain_id,
		title                    = title,
		description              = description,
		body                     = audit_body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task update failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","description":"`); json_write_string(&b, description)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_set_status :: proc(task_id, chain_id, status, body, author: string) -> Task_Service_Result {
	return task_service_status_command(Task_Status_Command{task_id = task_id, chain_id = chain_id, status = status, body = body, author_agent_instance_id = author})
}

task_service_status_command :: proc(cmd: Task_Status_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.status == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task status change requires task_id, status, and non-empty body"}`}
	}
	if !task_status_allowed(cmd.status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	state := task_states[idx]
	status_val, ok := task_status_from_string(cmd.status)
	if !ok {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if status_val == .Review_Ready || status_val == .Approved {
		unresolved := task_unresolved_comments(cmd.task_id)
		defer delete(unresolved)
		if len(unresolved) > 0 {
			return Task_Service_Result{
				ok = false,
				status_code = 400,
				message = fmt.tprintf(`{{"ok":false,"message":"task has %d unresolved comments"}}`, len(unresolved)),
			}
		}
	}
	if !task_status_change_authorized(state, status_val, cmd.author_agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not authorized for task status transition"}`}
	}
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		status                   = cmd.status,
		body                     = cmd.body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task status failed"}`}
	}
	task_notify_event(event)
	if cmd.status == "review_ready" || cmd.status == "blocked" || cmd.status == "queued" || cmd.status == "ready" || cmd.status == "approved" {
		_ = agent_store_clear_current_task(cmd.author_agent_instance_id)
	}

	manual_defer := (cmd.status == "queued" || cmd.status == "ready") && state.status == .In_Progress && task_actor_has_role(state, cmd.author_agent_instance_id, "assignee")
	defer_assignee := state.assignee_agent_instance_id

	task_recompute_promotions(cmd.author_agent_instance_id)
	if cmd.status == "queued" || cmd.status == "ready" {
		if manual_defer {
			if next_task := task_best_ready_task_for_assignee_excluding(defer_assignee, cmd.task_id); next_task != "" {
				task_service_auto_claim(next_task)
			}
		} else {
			task_service_auto_claim(cmd.task_id)
		}
	}
	task_service_try_auto_complete_chain(cmd.chain_id)
	if cmd.status == "review_ready" {
		task_notify_all_lgtm_required(cmd.task_id, cmd.chain_id)
		task_notify_user_proxy_review_requests(cmd.task_id, cmd.chain_id)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, cmd.status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_review_vote :: proc(cmd: Task_Review_Vote_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"review vote requires task_id and comment"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	state := task_states[idx]
	if state.status != .Review_Ready {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"can only vote on review_ready tasks"}`}
	}
	vote_author := cmd.author_agent_instance_id
	if proxy_reviewer, proxy_ok := task_user_proxy_reviewer_for(state, cmd.author_agent_instance_id); proxy_ok {
		vote_author = proxy_reviewer
	}
	is_required  := task_actor_has_role(state, vote_author, "lgtm_required")
	if !is_required && vote_author == task_reviewer_agent_instance_id(state) {
		is_required = true
	}
	is_optional  := task_actor_has_role(state, vote_author, "lgtm_optional")
	can_override := task_actor_can_override(state, cmd.author_agent_instance_id)
	if !is_required && !is_optional && !can_override {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not a reviewer for this task"}`}
	}
	role := "lgtm_optional"
	if is_required do role = "lgtm_required"
	vote_approved_str := "true" if cmd.approved else "false"
	event := Task_Event{
		kind                     = .Task_Review_Vote,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		vote_approved            = vote_approved_str,
		role                     = role,
		body                     = cmd.comment,
		author_agent_instance_id = vote_author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append review vote failed"}`}
	}
	task_notify_event(event)
	_ = agent_store_clear_current_task(cmd.author_agent_instance_id)
	if !cmd.approved {
		back_event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = cmd.task_id,
			chain_id                 = cmd.chain_id,
			status                   = "in_progress",
			body                     = fmt.tprintf("ngtm by %s: %s", vote_author, cmd.comment),
			author_agent_instance_id = "system-review-vote",
		}
		if task_store_append_event(back_event) {
			task_notify_event(back_event)
		}
	} else if task_all_required_lgtms_approved(cmd.task_id) {
		task_service_auto_approve(cmd.task_id, cmd.chain_id)
	}
	task_recompute_promotions(vote_author)
	task_notify_reviewer_rotation(vote_author)
	result_status := "review_ready"
	if updated_idx, updated_found := task_existing_state_index(cmd.task_id, cmd.chain_id); updated_found {
		result_status = task_status_to_string(task_states[updated_idx].status)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, result_status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_user_proxy_reviewer_for :: proc(state: Task_State, user_id: string) -> (string, bool) {
	if user_id == "" do return "", false
	chain_idx, chain_found := task_existing_chain_index(state.chain_id)
	if !chain_found do return "", false
	team_id := task_chains[chain_idx].team_id
	if team_id == "" {
		team, ok := team_db_get_team_by_chain_id(team_service_db, state.chain_id)
		if !ok do return "", false
		team_id = team.team_id
	}
	members := team_db_list_members(team_service_db, team_id)
	for member in members {
		if !member.is_user_proxy do continue
		if member.route_to != user_id do continue
		for i in 0..<task_participant_count {
			p := task_participants[i]
			if p.task_id != state.task_id do continue
			if p.role != "lgtm_required" && p.role != "lgtm_optional" do continue
			if p.agent_instance_id == member.role_key || p.agent_instance_id == member.route_to || (member.agent_record_id != "" && p.agent_instance_id == member.agent_record_id) {
				return p.agent_instance_id, true
			}
		}
	}
	return "", false
}

task_notify_user_proxy_review_requests :: proc(task_id, chain_id: string) {
	idx, found := task_existing_state_index(task_id, chain_id)
	if !found do return
	state := task_states[idx]
	chain_idx, chain_found := task_existing_chain_index(state.chain_id)
	if !chain_found do return
	chain := task_chains[chain_idx]
	team_id := chain.team_id
	if team_id == "" {
		team, ok := team_db_get_team_by_chain_id(team_service_db, state.chain_id)
		if !ok do return
		team_id = team.team_id
	}
	members := team_db_list_members(team_service_db, team_id)
	for member in members {
		if !member.is_user_proxy || member.route_to == "" do continue
		if !task_actor_has_role(state, member.role_key, "lgtm_required") && !task_actor_has_role(state, member.route_to, "lgtm_required") do continue
		sender := chain.coordinator_agent_instance_id
		if sender == "" do sender = "user_proxy"
		body := task_user_proxy_review_card_json(state)
		message_id, ok := chat_store_append_message(member.route_to, sender, "agent_to_user", body, true)
		if ok do chat_event_fanout(member.route_to, sender, message_id, "agent_to_user")
	}
}

task_user_proxy_review_card_json :: proc(state: Task_State) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"type":"smart_answer","body":"Review task `)
	json_write_string(&b, state.task_id)
	strings.write_string(&b, `: `)
	json_write_string(&b, state.title)
	strings.write_string(&b, `","suggested_replies":[`)
	strings.write_string(&b, `"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"lgtm\"}"`)
	strings.write_string(&b, `,"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"ngtm\"}"`)
	strings.write_string(&b, `]}`)
	return strings.to_string(b)
}

task_service_user_proxy_review_reply :: proc(user_id, coordinator_agent_instance_id, reply: string) -> Task_Service_Result {
	if extract_json_string(reply, "action", "") != "user_proxy_review" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"not a user_proxy review reply"}`}
	}
	task_id := extract_json_string(reply, "task_id", "")
	result := extract_json_string(reply, "result", "")
	approved := result == "lgtm"
	rejected := result == "ngtm"
	if task_id == "" || (!approved && !rejected) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid user_proxy review reply"}`}
	}
	idx, found := task_existing_state_index(task_id, "")
	if !found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	state := task_states[idx]
	if state.status != .Review_Ready do return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task is not pending review"}`}
	chain_idx, chain_found := task_existing_chain_index(state.chain_id)
	if !chain_found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	if coordinator_agent_instance_id != "" && task_chains[chain_idx].coordinator_agent_instance_id != coordinator_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"reply coordinator mismatch"}`}
	}
	if _, ok := task_user_proxy_reviewer_for(state, user_id); !ok {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"user is not the user_proxy reviewer"}`}
	}
	comment := "operator user_proxy LGTM"
	if rejected do comment = "operator user_proxy NGTM"
	return task_service_review_vote(Task_Review_Vote_Command{task_id = state.task_id, chain_id = state.chain_id, approved = approved, comment = comment, author_agent_instance_id = user_id})
}

task_service_auto_approve :: proc(task_id, chain_id: string) {
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = chain_id,
		status                   = "approved",
		body                     = "system_auto:all_lgtm_required_approved",
		author_agent_instance_id = "system-auto-approve",
	}
	if task_store_append_event(event) {
		task_notify_event(event)
		task_recompute_promotions("system-auto-approve")
		task_service_try_auto_complete_chain(chain_id)
	}
}

task_service_auto_claim :: proc(task_id: string) {
	idx, found := task_existing_state_index(task_id, "")
	if !found do return
	state := task_states[idx]
	if state.status != .Queued do return
	if !task_dependencies_satisfied(state.depends_on) do return
	if !task_ready_allows_auto_claim(state) do return
	if !task_chain_allows_execution(state.chain_id) do return
	assignee := state.assignee_agent_instance_id
	if assignee == "" do return
	if best_ready := task_best_ready_task_for_assignee(assignee); best_ready != "" && best_ready != task_id do return
	if task_active_slot_blocker(assignee, task_id) != "" do return
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = state.chain_id,
		status                   = "in_progress",
		body                     = "system_auto:auto_claimed",
		author_agent_instance_id = "system-auto-claim",
	}
	if task_store_append_event(event) {
		task_notify_event(event)
	}
}

task_service_try_auto_complete_chain :: proc(chain_id: string) {
	if chain_id == "" do return
	chain_idx, found := task_existing_chain_index(chain_id)
	if !found do return
	if task_chains[chain_idx].status == "reviewing" || task_chains[chain_idx].status == "paused" || task_chains[chain_idx].status == "completed" || task_chains[chain_idx].status == "archived" do return
	if !task_all_chain_tasks_terminal(chain_id) do return
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = chain_id,
		status                   = "reviewing",
		body                     = "system_auto:all_tasks_terminal_review_required",
		author_agent_instance_id = "system-auto-complete",
	}
	if task_store_append_event(event) {
		task_notify_event(event)
		task_service_ping_coordinator_for_chain_completion(chain_id)
	}
}

task_service_ping_coordinator_for_chain_completion :: proc(chain_id: string) {
	chain_idx, found := task_existing_chain_index(chain_id)
	if !found do return
	chain := task_chains[chain_idx]
	if chain.coordinator_agent_instance_id == "" do return

	message_body := fmt.tprintf(
		"All tasks in your task chain '%s' (ID: %s) have been completed!\n\n" +
		"As the designated coordinator, you must now review the results and move the task chain to 'completed' using the 'ham-ctl task-chains status --status completed --final-summary \"...\"' command.\n\n" +
		"Your final summary must strictly comply with the Task Chain Best Practices below:\n\n%s",
		chain.title,
		chain.chain_id,
		TASK_CHAIN_BEST_PRACTICES,
	)

	_, ok := chat_store_append_message("operator@local", chain.coordinator_agent_instance_id, "user_to_agent", message_body, false)
	if !ok {
		fmt.println("WARNING: Failed to append completion ping message to coordinator agent:", chain.coordinator_agent_instance_id)
	} else {
		fmt.println("INFO: Successfully pinged coordinator agent", chain.coordinator_agent_instance_id, "for chain completion of", chain_id)
	}
}

task_service_nudge :: proc(task_id, chain_id, body, author: string, interrupt: bool) -> Task_Service_Result {
	return task_service_nudge_command(Task_Nudge_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author, interrupt = interrupt})
}

task_service_nudge_command :: proc(cmd: Task_Nudge_Command) -> Task_Service_Result {
	if cmd.task_id == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"nudge requires task_id and non-empty body"}`}
	}
	idx, found := task_existing_state_index(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	state := task_states[idx]
	if task_status_terminal(state.status) {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"terminal task cannot be nudged"}`}
	}
	target := task_nudge_target_for_status(state, state.status)
	if target == "" {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"no nudge target for task status"}`}
	}
	event := Task_Event{
		kind                     = .Task_Nudged,
		task_id                  = state.task_id,
		chain_id                 = state.chain_id,
		status                   = task_status_to_string(state.status),
		body                     = cmd.body,
		agent_instance_id        = target,
		author_agent_instance_id = cmd.author_agent_instance_id,
		interrupt                = cmd.interrupt,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task nudge failed"}`}
	}
	delivery := task_notify_nudge_delivery(event)
	delivery_state := "skipped"
	if delivery.live_delivered {
		delivery_state = "delivered"
	} else if delivery.durable_queued {
		delivery_state = "queued"
	} else if delivery.failed {
		delivery_state = "failed"
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":`); strings.write_string(&b, "false" if delivery.failed else "true")
	strings.write_string(&b, `,"target_agent_instance_id":"`); json_write_string(&b, target)
	strings.write_string(&b, `","sent":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"live_delivered":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"durable_queued":`); strings.write_string(&b, "true" if delivery.durable_queued else "false")
	strings.write_string(&b, `,"failed":`); strings.write_string(&b, "true" if delivery.failed else "false")
	strings.write_string(&b, `,"delivery_state":"`); json_write_string(&b, delivery_state)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = !delivery.failed, status_code = 200 if !delivery.failed else 500, message = strings.to_string(b)}
}

task_service_update_chain :: proc(cmd: Task_Chain_Update_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain update requires chain_id"}`}
	}
	chain_idx, found := task_existing_chain_index(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	new_coordinator := cmd.coordinator_agent_instance_id
	if new_coordinator == "" do new_coordinator = task_chains[chain_idx].coordinator_agent_instance_id
	new_default_reviewer := cmd.default_reviewer_agent_instance_id
	if new_default_reviewer == "" do new_default_reviewer = task_chains[chain_idx].default_reviewer_agent_instance_id
	if new_default_reviewer != "" && new_default_reviewer == new_coordinator {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	if new_default_reviewer != "" {
		for i in 0..<task_state_count {
			state := task_states[i]
			if state.chain_id != cmd.chain_id do continue
			if task_status_terminal(state.status) do continue
			if state.assignee_agent_instance_id == new_default_reviewer {
				return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee of an active task in the chain"}`}
			}
		}
	}
	audit_body := fmt.tprintf("chain metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, task_chains[chain_idx].description, cmd.description)
	event := Task_Event{
		kind                          = .Chain_Metadata_Updated,
		chain_id                      = cmd.chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		body                          = audit_body,
		coordinator_agent_instance_id = cmd.coordinator_agent_instance_id,
		reviewer_agent_instance_id    = cmd.default_reviewer_agent_instance_id,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain update failed"}`}
	}
	task_notify_event(event)
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(summary_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain summary failed"}`}
		}
		task_notify_event(summary_event)
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_set_chain_status :: proc(chain_id, status, final_summary, author: string) -> Task_Service_Result {
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = status, final_summary = final_summary, author_agent_instance_id = author})
}

task_service_chain_status_command :: proc(cmd: Task_Chain_Status_Command) -> Task_Service_Result {
	if cmd.chain_id == "" || cmd.status == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain status requires chain_id and status"}`}
	}
	chain_idx, found := task_existing_chain_index(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	stored_summary := task_chains[chain_idx].final_summary
	if cmd.status == "completed" && strings.trim_space(cmd.final_summary) == "" && stored_summary == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"final_summary required for completed status"}`}
	}
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		task_store_append_event(summary_event)
		task_notify_event(summary_event)
	}
	kind := Task_Event_Kind.Chain_Status_Changed
	if cmd.status == "completed" do kind = .Chain_Completed
	status_event := Task_Event{
		kind                     = kind,
		chain_id                 = cmd.chain_id,
		status                   = cmd.status,
		body                     = cmd.final_summary,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(status_event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain status failed"}`}
	}
	task_notify_event(status_event)

	// Orchestrate member tasks based on the new chain status
	if cmd.status == "completed" || cmd.status == "archived" || cmd.status == "planning" || cmd.status == "paused" {
		for i in 0..<task_state_count {
			state := task_states[i]
			if state.chain_id != cmd.chain_id do continue
			if task_status_terminal(state.status) do continue

			next_status := ""
			body_text := ""
			if cmd.status == "completed" || cmd.status == "archived" {
				next_status = "cancelled"
				body_text = "system_auto:chain_completed"
			} else if cmd.status == "planning" || cmd.status == "paused" {
				if state.status == .In_Progress {
					next_status = "queued"
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				} else if state.status == .Queued {
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				}
			}
			if next_status == "" do continue
			next_status_val, _ := task_status_from_string(next_status)
			if state.status == next_status_val && body_text == "" do continue

			event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = state.task_id,
				chain_id                 = state.chain_id,
				status                   = next_status,
				body                     = body_text,
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if task_store_append_event(event) {
				task_notify_event(event)
			}
		}
		task_recompute_promotions(cmd.author_agent_instance_id)
	} else if cmd.status == "in_progress" || cmd.status == "queued" || cmd.status == "ready" {
		task_recompute_promotions(cmd.author_agent_instance_id)
	}

	archive_ok := true
	if cmd.status == "completed" || cmd.status == "archived" {
		archive_ok = task_archive_chain_to_hub(cmd.chain_id)
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true,"archive_ok":true}` if archive_ok else `{"ok":true,"archive_ok":false,"archive_pending":true}`}
}

task_service_complete_chain :: proc(chain_id, final_summary, author: string) -> Task_Service_Result {
	if chain_id == "" || strings.trim_space(final_summary) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain complete requires chain_id and non-empty summary"}`}
	}
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = "completed", final_summary = final_summary, author_agent_instance_id = author})
}

task_service_retry_pending_archives :: proc() -> Task_Service_Result {
	retried := task_store_retry_pending_archives()
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"retried":`)
	strings.write_string(&b, fmt.tprintf("%d", retried))
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_gating_error :: proc(error_kind, message, blocking_task_ids: string) -> Task_Service_Result {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message)
	strings.write_string(&b, `","error":"`);             json_write_string(&b, error_kind)
	strings.write_string(&b, `","blocking_task_ids":[`)
	ids   := strings.split(blocking_task_ids, ",")
	first := true
	for id_raw in ids {
		id := strings.trim_space(id_raw)
		if id == "" do continue
		if !first do strings.write_string(&b, `,`)
		first = false
		strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
	}
	strings.write_string(&b, `]}`)
	return Task_Service_Result{ok = false, status_code = 409, message = strings.to_string(b)}
}

task_service_evaluate_chain :: proc(chain_id, evaluation, author: string) -> Task_Service_Result {
	if chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain evaluation requires chain_id"}`}
	}
	if evaluation != "good" && evaluation != "bad" && evaluation != "unreviewed" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid evaluation value. Expected: good, bad, unreviewed"}`}
	}
	_, found := task_existing_chain_index(chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Evaluated,
		chain_id                 = chain_id,
		body                     = evaluation,
		author_agent_instance_id = author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain evaluation failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_halt_active_tasks_for_agent :: proc(agent_id: string) {
	if agent_id == "" do return
	for i in 0..<task_state_count {
		state := task_states[i]
		if state.assignee_agent_instance_id != agent_id do continue
		if state.status != .In_Progress do continue
		
		event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = state.task_id,
			chain_id                 = state.chain_id,
			status                   = "blocked",
			body                     = "system_block:assignee_active_task:pending_reviews_exist",
			author_agent_instance_id = "system-reviewer-gate",
		}
		if task_store_append_event(event) {
			task_notify_event(event)
		}
	}
}

