package main

import "core:fmt"
import "core:strings"
import vcs "odin_test:lib/vcs"

TASK_CHAIN_BEST_PRACTICES :: `## Task Chain Best Practices

When coordinating a task chain, you must adhere to the following workflow upon task completion:

1. **Verify All Tasks:** Review the outputs of all individual tasks in this chain to ensure they are fully complete, correct, and work together.
2. **Submit Verifiable Evidence:** When moving the task chain to 'completed' (using the 'ham-ctl task-chains status --status completed --final-summary "..."' command), you must provide a comprehensive, high-fidelity final summary. This summary MUST include:
   - **Verifiable Results/Evidence:** Specific outputs, behavior descriptions, or test logs proving correctness.
   - **Git Commits:** The hashes of all commits created or reviewed as part of this task chain.
   - **File Paths:** Precise relative or absolute paths of the files modified or created.
   - **Result Summary:** A concise overview of the accomplishments.
3. **Propose Quality Rating:** Propose a quality rating status of 'good' or 'bad' for this task chain.
4. **Reasoning:** Provide clear, objective engineering rationale explaining why the chain succeeded ('good') or if there were critical defects or difficulties encountered ('bad').`

Task_Service_Result :: struct {
	ok:          bool,
	status_code: int,
	message:     string,
}

USER_PROXY_REVIEWER_WARNING :: "operator@local reviewer normalized to user_proxy; prefer user_proxy for user-facing task reviews"

task_reviewer_ref_is_user_proxy :: proc(agent_instance_id: string) -> (bool, bool) {
	if agent_instance_id == "" do return false, false
	if task_actor_is_user_proxy(agent_instance_id) do return true, false
	if task_actor_is_human_recipient(agent_instance_id) {
		if task_actor_is_user(agent_instance_id) do return true, true
	}
	return false, false
}

task_normalize_user_reviewer :: proc(agent_instance_id: string) -> (string, bool) {
	if is_proxy, normalized := task_reviewer_ref_is_user_proxy(agent_instance_id); is_proxy {
		return USER_PROXY_AGENT_INSTANCE_ID, normalized
	}
	return agent_instance_id, false
}

task_write_user_proxy_warning_if_needed :: proc(b: ^strings.Builder, normalized: bool) {
	if !normalized do return
	strings.write_string(b, `,"warning":"`)
	json_write_string(b, USER_PROXY_REVIEWER_WARNING)
	strings.write_string(b, `"`)
}

task_service_create_task :: proc(cmd: Task_Create_Command) -> Task_Service_Result {
	if cmd.task_id != "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task_id is generated by daemon; omit task_id on create"}`}
	}
	if cmd.title == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task create requires title"}`}
	}
	assignee_agent_instance_id := cmd.assignee_agent_instance_id
	reviewer_agent_instance_id, reviewer_normalized := task_normalize_user_reviewer(cmd.reviewer_agent_instance_id)
	task_id := task_generate_id()
	status := cmd.status
	if status == "" do status = "planning"
	if !task_status_allowed(status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if cmd.depends_on != "" {
		if cmd.chain_id == "" {
			return task_dependency_validation_error("depends_on requires chain_id", "missing_chain", cmd.depends_on)
		}
		if dep_error, dep_error_kind, dep_ids, dep_ok := task_validate_dependency_ids(cmd.depends_on, cmd.chain_id, task_id); !dep_ok {
			return task_dependency_validation_error(dep_error, dep_error_kind, dep_ids)
		}
	}
	if status == "ready" || status == "in_progress" {
		if dep_blockers := task_dependency_blocking_ids(cmd.depends_on); dep_blockers != "" {
			return task_gating_error("dependency", "unmet task dependencies", dep_blockers)
		}
	}
	chain_id      := cmd.chain_id
	created_chain := false
	if chain_id == "" && !cmd.standalone {
		chain_id = task_chain_id_for_root(task_id)
		chain_event := Task_Event{
			kind                        = .Chain_Created,
			chain_id                    = chain_id,
			project_id                  = cmd.project_id,
			title                       = cmd.title,
			description                 = cmd.description,
			status                      = "planning",
			coordinator_agent_instance_id = cmd.created_by,
			author_agent_instance_id    = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(chain_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task chain create failed"}`}
		}
		created_chain = true
	}
	if assignee_agent_instance_id != "" {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(chain_id, cmd.project_id, assignee_agent_instance_id, "assignee", cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		assignee_agent_instance_id = resolved
	}
	if reviewer_agent_instance_id != "" && reviewer_agent_instance_id != "user_proxy" {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(chain_id, cmd.project_id, reviewer_agent_instance_id, "lgtm_required", cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		reviewer_agent_instance_id = resolved
	}
	if assignee_agent_instance_id != "" && assignee_agent_instance_id == reviewer_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the reviewer"}`}
	}
	if assignee_agent_instance_id != "" && reviewer_agent_instance_id == "" && chain_id != "" && task_chain_default_reviewer_agent_instance_id(chain_id) == assignee_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	if status == "ready" || status == "in_progress" {
		if assignee_agent_instance_id != "" {
			if active := task_active_slot_blocker(assignee_agent_instance_id, ""); active != "" {
				return task_gating_error("assignee_active_task", "assignee already has an active task", active)
			}
		}
	}
	if assignee_agent_instance_id != "" && !task_agent_instance_allowed_for_chain(chain_id, assignee_agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee is not an eligible agent (unknown or archived)"}`}
	}
	if assignee_agent_instance_id != "" && task_agent_instance_has_chain_role(chain_id, assignee_agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if reviewer_agent_instance_id != "" && !task_agent_instance_allowed_for_chain(chain_id, reviewer_agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer is not an eligible agent (unknown or archived)"}`}
	}
	priority := cmd.priority
	if priority == "" do priority = "normal"
	event := Task_Event{
		kind                          = .Task_Created,
		task_id                       = task_id,
		chain_id                      = chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		acceptance_criteria           = cmd.acceptance_criteria,
		priority                      = priority,
		status                        = status,
		assignee_agent_instance_id    = assignee_agent_instance_id,
		reviewer_agent_instance_id    = reviewer_agent_instance_id,
		depends_on                    = cmd.depends_on,
		created_by                    = cmd.created_by,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task create failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`);    json_write_string(&b, task_id)
	strings.write_string(&b, `","chain_id":"`);            json_write_string(&b, chain_id)
	strings.write_string(&b, `","root_task_id":"`);        json_write_string(&b, task_root_id_for_response(chain_id, task_id, created_chain))
	strings.write_string(&b, `","created_chain":`);        strings.write_string(&b, "true" if created_chain else "false")
	strings.write_string(&b, `,"standalone":`);            strings.write_string(&b, "true" if cmd.standalone else "false")
	task_write_user_proxy_warning_if_needed(&b, reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_create_chain :: proc(cmd: Task_Chain_Create_Command) -> Task_Service_Result {
	// A chain binds its coordinator to this project; reject a non-existent one so
	// we never generate a coordinator pinned to a project that will fail wrapper
	// project validation on every launch.
	if strings.trim_space(cmd.project_id) != "" && !project_exists(cmd.project_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(fmt.tprintf("project '%s' does not exist; create it first or use a valid project_id", cmd.project_id))}
	}
	chain_title := cmd.title
	if chain_title == "" do chain_title = "New task chain"
	chain_id := cmd.chain_id
	if chain_id == "" do chain_id = task_generate_chain_id()
	coordinator_ref := cmd.coordinator_agent_instance_id
	if coordinator_ref == "" do coordinator_ref = agent_default_id_for_use("coordinator")
	if coordinator_ref == "" do coordinator_ref = "coordinator"
	coordinator_agent_instance_id, coordinator_ok, coordinator_msg := task_service_resolve_agent_reference_for_new_chain(chain_id, cmd.project_id, coordinator_ref, "coordinator", cmd.author_agent_instance_id)
	if !coordinator_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(coordinator_msg)}
	if coordinator_agent_instance_id == "user_proxy" || coordinator_agent_instance_id == HUMAN_RECIPIENT_ID {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"coordinator cannot be user_proxy"}`}
	}
	default_reviewer_agent_instance_id, default_reviewer_normalized := task_normalize_user_reviewer(cmd.default_reviewer_agent_instance_id)
	if default_reviewer_agent_instance_id == "" {
		default_reviewer_agent_instance_id = agent_default_id_for_use("reviewer")
	}
	if default_reviewer_agent_instance_id != "" && default_reviewer_agent_instance_id != "user_proxy" && default_reviewer_agent_instance_id != HUMAN_RECIPIENT_ID {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_new_chain(chain_id, cmd.project_id, default_reviewer_agent_instance_id, "lgtm_required", cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		default_reviewer_agent_instance_id = resolved
	}
	if default_reviewer_agent_instance_id == coordinator_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	workspace_id := ""
	status := cmd.status
	if status == "" do status = "in_progress"
	event := Task_Event{
		kind                          = .Chain_Created,
		chain_id                      = chain_id,
		project_id                    = cmd.project_id,
		vcs_workspace_id              = workspace_id,
		title                         = chain_title,
		description                   = cmd.description,
		status                        = status,
		coordinator_agent_instance_id = coordinator_agent_instance_id,
		reviewer_agent_instance_id    = default_reviewer_agent_instance_id,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain create failed"}`}
	}
	_ = task_chain_maybe_record_diff_base_sha(chain_id, "chain_created")
	task_notify_event(event)
	coordinator_boot_requested := task_runtime_reconcile_chain_coordinator(chain_id, "chain_created", "high")
	coordinator_kickoff_task_id := task_service_create_coordinator_kickoff_task(chain_id, chain_title, cmd.description, coordinator_agent_instance_id, cmd.author_agent_instance_id, cmd.wants_vcs)
	if coordinator_kickoff_task_id == "" {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append coordinator kickoff task failed"}`}
	}
	workspace_setup_task_id := ""
	if cmd.wants_vcs {
		workspace_setup_task_id = task_service_create_workspace_setup_task(chain_id, cmd.project_id, chain_title, coordinator_agent_instance_id, default_reviewer_agent_instance_id, cmd.author_agent_instance_id, coordinator_kickoff_task_id)
		if workspace_setup_task_id == "" {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append workspace setup task failed"}`}
		}
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"chain_id":"`); json_write_string(&b, chain_id)
	strings.write_string(&b, `","vcs_workspace_id":"`); json_write_string(&b, workspace_id)
	strings.write_string(&b, `","workspace_setup_task_id":"`); json_write_string(&b, workspace_setup_task_id)
	strings.write_string(&b, `","coordinator_kickoff_task_id":"`); json_write_string(&b, coordinator_kickoff_task_id)
	strings.write_string(&b, `","discovery_task_id":"`); json_write_string(&b, coordinator_kickoff_task_id)
	strings.write_string(&b, `","coordinator_agent_instance_id":"`); json_write_string(&b, coordinator_agent_instance_id)
	strings.write_string(&b, `","coordinator_boot_requested":`); strings.write_string(&b, "true" if coordinator_boot_requested else "false")
	strings.write_string(&b, `,"status":"`); json_write_string(&b, status); strings.write_string(&b, `"`)
	task_write_user_proxy_warning_if_needed(&b, default_reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_create_workspace_setup_task :: proc(chain_id, project_id, chain_title, coordinator_agent_instance_id, reviewer_agent_instance_id, author, depends_on: string) -> string {
	task_id := task_generate_id()
	description := task_service_workspace_setup_description(project_id, chain_id, chain_title)
	event := Task_Event{
		kind                       = .Task_Created,
		task_id                    = task_id,
		chain_id                   = chain_id,
		title                      = "Prepare chain workspace",
		description                = description,
		priority                   = "normal",
		status                     = "planning" if depends_on != "" else "ready",
		assignee_agent_instance_id = coordinator_agent_instance_id,
		reviewer_agent_instance_id  = reviewer_agent_instance_id,
		depends_on                 = depends_on,
		created_by                 = author,
		author_agent_instance_id   = author,
	}
	if !task_store_append_event(event) do return ""
	task_notify_event(event)
	return task_id
}

task_service_workspace_setup_description :: proc(project_id, chain_id, chain_title: string) -> string {
	repo := ""
	base_ref := task_service_project_base_ref(project_id)
	worktree_root := fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id)
	vcs_kind := "auto"
	if pidx := project_index(project_id); pidx >= 0 {
		project := project_records[pidx]
		repo = project_anchor_value(project, "directory", "")
		base_ref = project_anchor_value(project, "base_ref", base_ref)
		worktree_root = project_anchor_value(project, "worktree_root", worktree_root)
		vcs_kind = project_anchor_value(project, "vcs_kind", vcs_kind)
	}
	slug := task_chain_slug(chain_title, chain_id)
	path := fmt.tprintf("%s/chain/%s/%s", strings.trim_right(worktree_root, "/"), chain_id, slug)
	branch := vcs_git_safe_branch_name(fmt.tprintf("chain-%s-%s", chain_id, slug))
	b := strings.builder_make()
	strings.write_string(&b, "Prepare the VCS workspace for this chain. Use the `vcs-workspace-setup` skill and do not treat this as a daemon-selected chain kind.\n\n")
	strings.write_string(&b, "## Required approval\n")
	strings.write_string(&b, "Do not run any VCS command until you have asked the user in chain chat and received explicit approval. Show the exact command(s) you plan to run.\n\n")
	strings.write_string(&b, "## Expected workspace\n")
	strings.write_string(&b, "- Project directory: "); strings.write_string(&b, repo if repo != "" else "not configured"); strings.write_string(&b, "\n")
	strings.write_string(&b, "- VCS kind: "); strings.write_string(&b, vcs_kind); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Base ref: "); strings.write_string(&b, base_ref); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Worktree path: "); strings.write_string(&b, path); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Suggested branch name, if the user approves branch creation: "); strings.write_string(&b, branch); strings.write_string(&b, "\n\n")
	strings.write_string(&b, "## Suggested Git commands\n")
	strings.write_string(&b, "First ask the user to approve these commands. After approval, prefer a detached worktree first so chain creation does not depend on branch ref creation:\n\n")
	strings.write_string(&b, "```bash\n")
	strings.write_string(&b, fmt.tprintf("mkdir -p %s\n", shell_quote(vcs.vcs_workspace_parent(path))))
	if repo != "" {
		strings.write_string(&b, fmt.tprintf("git -C %s fetch --quiet origin %s || true\n", shell_quote(repo), shell_quote(base_ref)))
		strings.write_string(&b, fmt.tprintf("git -C %s worktree add --detach %s %s\n", shell_quote(repo), shell_quote(path), shell_quote(base_ref)))
		strings.write_string(&b, fmt.tprintf("git -C %s switch -c %s\n", shell_quote(path), shell_quote(branch)))
	} else {
		strings.write_string(&b, "# Configure a project directory before running git worktree commands.\n")
	}
	strings.write_string(&b, "```\n\n")
	strings.write_string(&b, "If branch creation fails, keep the detached worktree and report the failure in a task comment instead of blocking chain creation.\n\n")
	strings.write_string(&b, "## Completion evidence\n")
	strings.write_string(&b, "Comment with the approved commands, actual workspace path, branch/detached state, base ref, and `git -C <path> status --short --branch` output. Then mark this task done. Downstream implementation tasks should depend on this task when they need the workspace.\n")
	return strings.to_string(b)
}

task_service_create_coordinator_kickoff_task :: proc(chain_id, chain_title, chain_description, coordinator_agent_instance_id, author: string, wants_vcs: bool) -> string {
	task_id := task_generate_id()
	description := task_service_coordinator_kickoff_description(chain_title, chain_description, wants_vcs)
	event := Task_Event{
		kind                       = .Task_Created,
		task_id                    = task_id,
		chain_id                   = chain_id,
		title                      = "Plan task chain from goal",
		description                = description,
		priority                   = "normal",
		status                     = "ready",
		assignee_agent_instance_id = coordinator_agent_instance_id,
		created_by                 = author,
		author_agent_instance_id   = author,
	}
	if !task_store_append_event(event) do return ""
	task_notify_event(event)
	return task_id
}

task_service_coordinator_kickoff_description :: proc(chain_title, chain_description: string, wants_vcs: bool) -> string {
	b := strings.builder_make()
	strings.write_string(&b, "Initial coordinator kickoff task for a goal-driven task chain. There is no daemon-selected chain kind, no generated team roster, and no built-in scaffold expansion.\n\n")
	strings.write_string(&b, "## Goal context\n")
	strings.write_string(&b, "- Current chain title: "); strings.write_string(&b, chain_title); strings.write_string(&b, "\n")
	if chain_description != "" {
		strings.write_string(&b, "- Initial goal/description: "); strings.write_string(&b, chain_description); strings.write_string(&b, "\n")
	} else {
		strings.write_string(&b, "- Initial goal/description: not provided yet.\n")
	}
	if wants_vcs {
		strings.write_string(&b, "- VCS requested: a separate `Prepare chain workspace` task has been scheduled. Use the `vcs-workspace-setup` skill and make implementation tasks depend on that setup task when needed.\n")
	}
	strings.write_string(&b, "\n## Instructions\n")
	strings.write_string(&b, "1. Read applicable skills, especially `coordinator-playbook` and the scaffold recipe skills (`scaffold-coding-feature`, `scaffold-coding-bugfix`, `scaffold-research`, `scaffold-solo`).\n")
	strings.write_string(&b, "2. Select the recipe that best fits the goal; do not rely on a chain `kind` field or a generated roster.\n")
	strings.write_string(&b, "3. Clarify the user goal through chain chat if the title/goal is missing or vague, then update the chain title/description.\n")
	strings.write_string(&b, "4. Create downstream tasks with dependencies, assignees, and reviewers using task/participant roles plus configured default-agent ids.\n")
	strings.write_string(&b, "5. Ensure review gates and evidence expectations are explicit on each downstream task. Mark this kickoff task done once the downstream task chain is ready to execute.\n")
	return strings.to_string(b)
}

vcs_git_safe_branch_name :: proc(name: string) -> string {
	clean, _ := strings.replace_all(name, "/", "-")
	clean, _ = strings.replace_all(clean, "@", "-")
	clean, _ = strings.replace_all(clean, " ", "-")
	clean = strings.trim(clean, "-.")
	if clean == "" do clean = "workspace"
	return strings.clone(fmt.tprintf("heimdall-%s", clean))
}

task_service_vcs_workspace_path :: proc(project_id, chain_id, chain_title: string) -> string {
	worktree_root := fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id)
	if pidx := project_index(project_id); pidx >= 0 {
		project := project_records[pidx]
		worktree_root = project_anchor_value(project, "worktree_root", worktree_root)
	}
	slug := task_chain_slug(chain_title, chain_id)
	return fmt.tprintf("%s/chain/%s/%s", strings.trim_right(worktree_root, "/"), chain_id, slug)
}

task_service_project_supports_vcs :: proc(project_id: string) -> bool {
	if project_id == "" do return false
	idx := project_index(project_id)
	if idx < 0 do return false
	project := project_records[idx]
	vcs_kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	return repo != "" && vcs_kind != "none"
}

task_service_project_base_ref :: proc(project_id: string, default_base_ref: string = "main") -> string {
	if project_id == "" do return strings.clone(default_base_ref)
	if idx := project_index(project_id); idx >= 0 {
		project := project_records[idx]
		base_ref := project_anchor_value(project, "base_ref", "")
		if base_ref != "" do return base_ref
	}
	return strings.clone(default_base_ref)
}

task_service_cleanup_workspace :: proc(chain_id: string) {
	if rec, ok := vcs_db_workspace_for_chain(chain_id); ok {
		backend := vcs.vcs_backend_for(vcs_handle_from_record(rec).kind)
		_, _ = backend.workspace_remove(vcs_handle_from_record(rec), true)
		_ = vcs_db_delete_workspace(chain_id)
	}
}

task_service_error_json :: proc(message: string) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message); strings.write_string(&b, `"}`)
	return strings.to_string(b)
}

task_service_maybe_provision_workspace :: proc(project_id, chain_id, title: string) -> (Vcs_Workspace_Record, bool, string) {
	project_idx := project_index(project_id)
	if project_idx < 0 do return Vcs_Workspace_Record{}, false, "no vcs"
	project := project_records[project_idx]
	kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	if kind == "none" || repo == "" do return Vcs_Workspace_Record{}, false, "no vcs"
	backend_kind := vcs.Vcs_Kind.Git
	if kind == "jj" do backend_kind = .Jj
	if kind == "fig" do backend_kind = .Fig
	if kind == "auto" {
		if is_google3_path(repo) {
			backend_kind = .Fig
		} else {
			jj_detected := vcs.vcs_backend_for(.Jj).detect(repo)
			fig_detected := vcs.vcs_backend_for(.Fig).detect(repo)
			if jj_detected.ok do backend_kind = .Jj
			else if fig_detected.ok do backend_kind = .Fig
			else do backend_kind = .Git
		}
	}
	backend := vcs.vcs_backend_for(backend_kind)
	detected := backend.detect(repo)
	if !detected.ok do return Vcs_Workspace_Record{}, false, detected.message
	base_ref := project_anchor_value(project, "base_ref", detected.base_ref)
	if base_ref == "" do base_ref = detected.base_ref
	root := project_anchor_value(project, "worktree_root", fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id))
	name := fmt.tprintf("chain/%s/%s", chain_id, task_chain_slug(title, chain_id))
	handle, ok, msg := backend.workspace_add(detected.repo_root, name, base_ref, root)
	if !ok do return Vcs_Workspace_Record{}, false, msg
	now := router_now_unix_ms()
	rec := Vcs_Workspace_Record{workspace_id=fmt.tprintf("ws_%s", chain_id), chain_id=chain_id, project_id=project_id, vcs_kind="git", path=handle.path, branch_or_change=handle.branch_or_change, base_ref=handle.base_ref, status="clean", created_unix_ms=now, updated_unix_ms=now}
	if backend_kind == .Jj do rec.vcs_kind = "jj"
	if backend_kind == .Fig do rec.vcs_kind = "fig"
	if !vcs_db_insert_workspace(rec) {
		_, _ = backend.workspace_remove(handle, true)
		return Vcs_Workspace_Record{}, false, "persist workspace failed"
	}
	return rec, true, "ok"
}

is_google3_path :: proc(path: string) -> bool {
	parts := strings.split(path, "/")
	defer delete(parts)
	for p in parts {
		if p == "google3" do return true
	}
	return false
}

project_anchor_value :: proc(project: Project_Record, anchor_type, default_value: string) -> string {
	for i in 0..<project.anchor_count { if project.anchors[i].type == anchor_type do return project.anchors[i].value }
	return default_value
}

task_chain_project_git_repo :: proc(chain_id: string) -> (string, bool, string) {
	chain, found := store_get_chain(chain_id)
	if !found do return "", false, "chain not found"
	if _, has_workspace := vcs_db_workspace_for_chain(chain_id); has_workspace do return "", false, "chain has dedicated workspace"
	if chain.project_id == "" do return "", false, "chain has no project"
	project_idx := project_index(chain.project_id)
	if project_idx < 0 do return "", false, "project not found"
	project := project_records[project_idx]
	kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	if repo == "" do repo = project_anchor_value(project, "git_repo", "")
	if repo == "" || kind == "none" || kind == "jj" || kind == "fig" || is_google3_path(repo) do return "", false, "project does not support git repo diff"
	detected := vcs.vcs_backend_for(.Git).detect(repo)
	if !detected.ok do return "", false, detected.message
	return detected.repo_root, true, "git repo diff supported"
}

task_chain_repo_diff_supported :: proc(chain_id: string) -> bool {
	_, ok, _ := task_chain_project_git_repo(chain_id)
	return ok
}

task_chain_maybe_record_diff_base_sha :: proc(chain_id, reason: string) -> bool {
	_ = reason
	chain, found := store_get_chain(chain_id)
	if !found do return false
	if strings.trim_space(chain.diff_base_sha) != "" do return true
	repo, repo_ok, _ := task_chain_project_git_repo(chain_id)
	if !repo_ok do return false
	sha, sha_ok, _ := vcs.vcs_backend_for(.Git).repo_head_sha(repo)
	if !sha_ok || sha == "" do return false
	chain.diff_base_sha = strings.clone(sha)
	_ = store_upsert_chain(chain)
	if task_db_ready do return task_db_save_chain(chain)
	return true
}

task_chain_slug :: proc(title, chain_id: string) -> string {
	b := strings.builder_make()
	for r in strings.to_lower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') do strings.write_rune(&b, r)
		else if r == '-' || r == '_' || r == ' ' do strings.write_byte(&b, '-')
		if len(strings.to_string(b)) >= 40 do break
	}
	out := strings.trim(strings.to_string(b), "-")
	if out == "" {
		if len(chain_id) > 8 do return chain_id[len(chain_id)-8:]
		return chain_id
	}
	return strings.clone(out)
}

task_service_activate_chain :: proc(cmd: Task_Chain_Activate_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"activate requires chain_id"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	if chain.status != "planning" {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"only planning chains can be activated"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = cmd.chain_id,
		status                   = "in_progress",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain activate failed"}`}
	}
	task_notify_event(event)
	_ = task_autoscaler_ensure_chain_coordinator(cmd.chain_id, "chain_activate", "high")
	task_recompute_promotions(cmd.author_agent_instance_id)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_comment :: proc(task_id, chain_id, body, author: string) -> Task_Service_Result {
	return task_service_comment_command(Task_Comment_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author})
}

task_service_comment_command :: proc(cmd: Task_Comment_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.body == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task comment requires task_id and body"}`}
	}
	comment_id := fmt.tprintf("cmt_%d", router_now_unix_ms())
	event := Task_Event{
		kind                     = .Task_Comment,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = comment_id,
		body                     = cmd.body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task comment failed"}`}
	}
	task_notify_event(event)

	// Ordinary comments are informational by default. Do not regress an
	// already-approved task merely because the comment is unresolved; explicit
	// changes-requested review state is represented by an NGTM vote, which moves
	// review_ready work back to in_progress in task_service_review_vote.

	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"comment_id":"`); json_write_string(&b, comment_id); strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_comment_resolve :: proc(cmd: Task_Comment_Resolve_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"comment resolve requires task_id and comment_id"}`}
	}
	if !store_comment_exists(cmd.task_id, cmd.comment_id) {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"comment not found"}`}
	}
	event := Task_Event{
		kind                     = .Task_Comment_Resolved,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = cmd.comment_id,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append comment resolve failed"}`}
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_resolve_agent_reference_for_chain :: proc(chain_id, project_id, agent_ref, participant_role, author: string) -> (string, bool, string) {
	if agent_ref == "" do return "", false, "agent reference is required"
	if agent_ref == "user_proxy" || agent_ref == HUMAN_RECIPIENT_ID do return agent_ref, true, "ok"
	// Existing instance records are exact targets, including legacy non-session ids.
	if idx := agent_record_index_by_instance(agent_ref); idx >= 0 {
		if agent_instance_records[idx].archived_at_unix_ms != 0 do return "", false, "agent is archived"
		return agent_ref, true, "ok"
	}
	resolved_ref := task_service_default_agent_ref(agent_ref)
	if resolved_ref == "user_proxy" || resolved_ref == HUMAN_RECIPIENT_ID do return resolved_ref, true, "ok"
	if idx := agent_record_index_by_instance(resolved_ref); idx >= 0 {
		if agent_instance_records[idx].archived_at_unix_ms != 0 do return "", false, "agent is archived"
		return resolved_ref, true, "ok"
	}
	// Unknown @-qualified refs look like exact instances/legacy aliases and should
	// not be reinterpreted as durable agent ids. Likewise, an unknown indexed name
	// such as coder-1 is a role-slot typo, not a new durable agent_id.
	if strings.index_byte(resolved_ref, '@') >= 0 do return "", false, "agent instance is unknown"
	if task_service_agent_ref_looks_indexed_slot(resolved_ref) do return "", false, "role slot is unknown for this chain"
	return task_service_create_concrete_instance_for_agent_id(resolved_ref, chain_id, project_id, participant_role, author)
}

task_service_default_agent_ref :: proc(agent_ref: string) -> string {
	if agent_ref == "" || strings.index_byte(agent_ref, '@') >= 0 || agent_ref == "user_proxy" || agent_ref == HUMAN_RECIPIENT_ID do return agent_ref
	if mapped := agent_default_id_for_use(agent_ref); mapped != "" do return mapped
	return agent_ref
}

task_service_agent_ref_looks_indexed_slot :: proc(agent_ref: string) -> bool {
	idx := strings.last_index_byte(agent_ref, '-')
	if idx <= 0 || idx + 1 >= len(agent_ref) do return false
	for ch in agent_ref[idx + 1:] {
		if ch < '0' || ch > '9' do return false
	}
	return true
}

task_service_resolve_agent_reference_for_new_chain :: proc(chain_id, project_id, agent_ref, participant_role, author: string) -> (string, bool, string) {
	if agent_ref == "" do return "", false, "agent reference is required"
	if agent_ref == "user_proxy" || agent_ref == HUMAN_RECIPIENT_ID do return agent_ref, true, "ok"
	if idx := agent_record_index_by_instance(agent_ref); idx >= 0 {
		if agent_instance_records[idx].archived_at_unix_ms != 0 do return "", false, "agent is archived"
		return agent_ref, true, "ok"
	}
	resolved_ref := task_service_default_agent_ref(agent_ref)
	if resolved_ref == "user_proxy" || resolved_ref == HUMAN_RECIPIENT_ID do return resolved_ref, true, "ok"
	if idx := agent_record_index_by_instance(resolved_ref); idx >= 0 {
		if agent_instance_records[idx].archived_at_unix_ms != 0 do return "", false, "agent is archived"
		return resolved_ref, true, "ok"
	}
	if strings.index_byte(resolved_ref, '@') >= 0 do return "", false, "agent instance is unknown"
	if task_service_agent_ref_looks_indexed_slot(resolved_ref) do return "", false, "role slot is unknown for this chain"
	return task_service_create_concrete_instance_for_agent_id(resolved_ref, chain_id, project_id, participant_role, author)
}

task_service_create_concrete_instance_for_agent_id :: proc(agent_id_ref, chain_id, project_id, participant_role, author: string) -> (string, bool, string) {
	durable_agent_id := safe_agent_id_part(agent_id_ref)
	if durable_agent_id == "" || durable_agent_id == "unnamed" || durable_agent_id != agent_id_ref do return "", false, "invalid agent_id"
	resolved_project_id := project_id
	template_id := agent_id_template_id(durable_agent_id)
	provider_profile := agent_resolve_provider_profile("")
	model_tier := agent_resolve_model_tier("")
	if idx := agent_id_index(durable_agent_id); idx >= 0 {
		rec := agent_id_records[idx]
		if rec.state != "" && rec.state != AGENT_ID_STATE_ACTIVE do return "", false, "agent_id is archived"
		if rec.template_id != "" do template_id = rec.template_id
		if rec.default_provider_profile != "" do provider_profile = rec.default_provider_profile
		if rec.default_model_tier != "" do model_tier = rec.default_model_tier
		if resolved_project_id == "" && rec.default_project_id != "" do resolved_project_id = rec.default_project_id
	} else {
		_ = agent_id_upsert(durable_agent_id, durable_agent_id, template_id, provider_profile, model_tier, "", author)
	}
	if resolved_project_id == "" {
		if chain, found := store_get_chain(chain_id); found do resolved_project_id = chain.project_id
	}
	instance_id := agent_instance_id_new(durable_agent_id)
	if !valid_agent_instance_id(instance_id) do return "", false, "failed to generate agent instance id"
	display_name := durable_agent_id
	if participant_role != "" && participant_role != "assignee" do display_name = fmt.tprintf("%s %s", durable_agent_id, participant_role)
	_, _, upsert_ok := agent_record_upsert(instance_id, display_name, template_id, provider_profile, resolved_project_id, "", model_tier, AGENT_IDENTITY_STATE_PROVISIONED)
	if !upsert_ok do return "", false, "failed to persist resolved agent instance"
	return instance_id, true, "ok"
}

task_service_assign :: proc(task_id, chain_id, agent_instance_id, author: string) -> Task_Service_Result {
	return task_service_assign_command(Task_Assign_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, author_agent_instance_id = author})
}

task_service_assign_command :: proc(cmd: Task_Assign_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task assignment requires task_id and agent_instance_id"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	agent_instance_id, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(state.chain_id, "", cmd.agent_instance_id, "assignee", cmd.author_agent_instance_id)
	if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
	if task_actor_has_role(state, agent_instance_id, "lgtm_required") || task_actor_has_role(state, agent_instance_id, "lgtm_optional") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is already a reviewer"}`}
	}
	if task_chain_default_reviewer_agent_instance_id(state.chain_id) == agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	if task_agent_instance_has_chain_role(state.chain_id, agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if !task_agent_instance_allowed_for_chain(state.chain_id, agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is not an eligible agent (unknown or archived)"}`}
	}
	old_assignee := state.assignee_agent_instance_id
	queued_behind_task_id := ""
	if task_status_active_for_assignee(state) {
		if active := task_active_slot_blocker(agent_instance_id, state.task_id); active != "" {
			if active == "pending_reviews_exist" {
				return task_gating_error("assignee_active_task", "assignee already has pending reviews", active)
			}
			queued_behind_task_id = active
		}
	}
	event := Task_Event{
		kind                     = .Task_Assigned,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = agent_instance_id,
		role                     = "assignee",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task assignment failed"}`}
	}
	task_notify_event(event)
	if old_assignee != "" && old_assignee != agent_instance_id {
		_ = task_notify_task_role_change_recipients(event, task_status_to_string(state.status), "assignee", old_assignee, "")
	}
	if task_status_active_for_assignee(state) {
		if state.assignee_agent_instance_id != "" && state.assignee_agent_instance_id != agent_instance_id {
			_ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, cmd.task_id)
		}
		if queued_behind_task_id != "" {
			block_event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = cmd.task_id,
				chain_id                 = state.chain_id,
				status                   = "blocked",
				body                     = strings.concatenate({"system_block:assignee_active_task:", queued_behind_task_id}),
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if task_store_append_event(block_event) {
				task_notify_event(block_event)
			}
		} else if state.status == .In_Progress {
			_ = agent_store_set_current_task(agent_instance_id, cmd.task_id)
			_ = task_runtime_reconcile_task(cmd.task_id, "assignment", "high")
		}
	}
	if queued_behind_task_id != "" {
		b := strings.builder_make()
		strings.write_string(&b, `{"ok":true,"queued_behind_task_id":"`); json_write_string(&b, queued_behind_task_id); strings.write_string(&b, `"}`)
		return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_add_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant requires task_id, agent_instance_id, and role"}`}
	}
	agent_instance_id := cmd.agent_instance_id
	reviewer_normalized := false
	if cmd.role == "lgtm_required" || cmd.role == "lgtm_optional" {
		agent_instance_id, reviewer_normalized = task_normalize_user_reviewer(cmd.agent_instance_id)
	}
	switch cmd.role {
	case "assignee", "lgtm_required", "lgtm_optional", "coordinator", "subscriber":
	case:
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"role must be assignee, lgtm_required, lgtm_optional, coordinator, or subscriber"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if agent_instance_id != "user_proxy" && agent_instance_id != HUMAN_RECIPIENT_ID {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(state.chain_id, "", agent_instance_id, cmd.role, cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		agent_instance_id = resolved
	}
	if (cmd.role == "lgtm_required" || cmd.role == "lgtm_optional") && state.assignee_agent_instance_id == agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be a reviewer"}`}
	}
	if cmd.role == "assignee" && (task_actor_has_role(state, agent_instance_id, "lgtm_required") || task_actor_has_role(state, agent_instance_id, "lgtm_optional")) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer cannot be the assignee"}`}
	}
	if cmd.role == "assignee" && task_chain_default_reviewer_agent_instance_id(state.chain_id) == agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee"}`}
	}
	if cmd.role == "assignee" && task_agent_instance_has_chain_role(state.chain_id, agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if !task_agent_instance_allowed_for_chain(state.chain_id, agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is not an eligible agent (unknown or archived)"}`}
	}
	event := Task_Event{
		kind                     = .Task_Participant_Added,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant failed"}`}
	}
	task_notify_event(event)
	if (cmd.role == "lgtm_required" || cmd.role == "lgtm_optional") && state.status == .Review_Ready {
		task_notify_review_ready_agent(state, agent_instance_id)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true`)
	task_write_user_proxy_warning_if_needed(&b, reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_agent_instance_has_chain_role :: proc(chain_id, agent_instance_id, role_key: string) -> bool {
	_ = chain_id; _ = agent_instance_id; _ = role_key
	return false
}

// Assignment is not gated by legacy chain membership stores.
// Any existing, non-archived agent instance (or an allowed user-proxy reviewer)
// may be assigned/reviewed on any chain; involvement is recorded via an
// association record instead of requiring pre-existing membership.
//
// This returns whether the agent is *eligible* at all. The surrounding conflict
// checks (assignee != reviewer, default-reviewer separation, active-slot gating)
// are enforced separately by the callers and are unchanged.
task_record_agent_chain_association :: proc(chain_id, task_id, agent_instance_id, association_kind: string) -> bool {
	if chain_id == "" || task_id == "" || agent_instance_id == "" || association_kind == "" do return true
	project_id := ""
	if chain, found := store_get_chain(chain_id); found {
		project_id = chain.project_id
	}
	now := router_now_unix_ms()
	assoc := Agent_Chain_Association{
		association_id = fmt.tprintf("assoc_%s_%s_%s_%s", chain_id, task_id, agent_instance_id, association_kind),
		agent_instance_id = agent_instance_id,
		project_id = project_id,
		chain_id = chain_id,
		task_id = task_id,
		association_kind = association_kind,
		created_unix_ms = now,
		last_active_unix_ms = now,
	}
	return task_db_save_agent_chain_association(assoc)
}

task_agent_instance_allowed_for_chain :: proc(chain_id, agent_instance_id: string) -> bool {
	if agent_instance_id == "" do return false
	chain, chain_found := store_get_chain(chain_id)
	// Coordinator / default reviewer are always allowed.
	if chain_found && (agent_instance_id == chain.coordinator_agent_instance_id || agent_instance_id == chain.default_reviewer_agent_instance_id) do return true
	// Allowed user-proxy / operator reviewer identities remain permitted.
	if agent_instance_id == "user_proxy" || agent_instance_id == HUMAN_RECIPIENT_ID do return true
	// Any known, non-archived agent identity is eligible (flexible assignment).
	if idx := agent_record_index_by_instance(agent_instance_id); idx >= 0 {
		return agent_instance_records[idx].archived_at_unix_ms == 0
	}
	_ = chain_found
	return false
}

task_service_remove_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_remove_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_remove_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant removal requires task_id, agent_instance_id, and role"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	agent_instance_id := cmd.agent_instance_id
	if cmd.role == "lgtm_required" || cmd.role == "lgtm_optional" {
		agent_instance_id, _ = task_normalize_user_reviewer(cmd.agent_instance_id)
	}
	event := Task_Event{
		kind                     = .Task_Participant_Removed,
		task_id                  = cmd.task_id,
		chain_id                 = state.chain_id,
		agent_instance_id        = agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant removal failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_update_task :: proc(cmd: Task_Update_Command) -> Task_Service_Result {
	if cmd.task_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task update requires task_id"}`}
	}
	current, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	title := cmd.title
	if title == "" do title = current.title
	description := current.description
	if cmd.description_present do description = cmd.description
	acceptance_criteria := current.acceptance_criteria
	if cmd.acceptance_criteria_present do acceptance_criteria = cmd.acceptance_criteria
	depends_on := current.depends_on
	if cmd.depends_on_present {
		depends_on = cmd.depends_on
		// Validate unknown ids and self-references (reuses create-path validation),
		// then reject cycles across the chain's current dependency graph.
		if dep_error, dep_error_kind, dep_ids, dep_ok := task_validate_dependency_ids(depends_on, current.chain_id, cmd.task_id); !dep_ok {
			return task_dependency_validation_error(dep_error, dep_error_kind, dep_ids)
		}
		if cycle_id := task_dependencies_would_cycle(current.chain_id, cmd.task_id, depends_on); cycle_id != "" {
			return task_dependency_validation_error("dependency change would create a cycle", "dependency_cycle", cycle_id)
		}
	}
	audit_body := fmt.tprintf("metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, current.description, description)
	event := Task_Event{
		kind                        = .Task_Metadata_Updated,
		task_id                     = cmd.task_id,
		chain_id                    = current.chain_id,
		title                       = title,
		description                 = description,
		acceptance_criteria         = acceptance_criteria,
		acceptance_criteria_present = cmd.acceptance_criteria_present,
		depends_on                  = depends_on,
		depends_on_present          = cmd.depends_on_present,
		body                        = audit_body,
		author_agent_instance_id    = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task update failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","description":"`); json_write_string(&b, description)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

// task_dependencies_would_cycle returns a non-empty offending task id when
// making task_id depend on the given depends_on set would create a cycle in the
// chain's dependency graph. It performs a DFS from each proposed dependency,
// following existing depends_on edges of other tasks in the same chain, and
// reports a cycle if task_id is reachable (i.e. some dependency already depends
// on task_id transitively).
task_dependencies_would_cycle :: proc(chain_id, task_id, depends_on: string) -> string {
	visited := make(map[string]bool)
	defer delete(visited)

	// Seed the DFS stack with the proposed direct dependencies.
	stack := make([dynamic]string)
	defer delete(stack)
	for dep in strings.split(depends_on, ",") {
		id := strings.trim_space(dep)
		if id == "" do continue
		append(&stack, id)
	}

	for len(stack) > 0 {
		current := stack[len(stack) - 1]
		pop(&stack)
		if current == task_id do return current // task_id reachable => cycle
		if visited[current] do continue
		visited[current] = true
		// Follow the current node's own dependencies within the same chain.
		dep_state, found := store_get_task_in_chain(current, chain_id)
		if !found do continue
		for dep in strings.split(dep_state.depends_on, ",") {
			id := strings.trim_space(dep)
			if id == "" do continue
			if id == task_id do return id
			if !visited[id] do append(&stack, id)
		}
	}
	return ""
}

// task_service_delete_task performs a first-class hard delete (distinct from the
// cancelled status, which keeps the row). It rejects the delete when any other
// task in the same chain still depends on the target, returning the blocking
// dependent ids so the UI can offer a "detach & delete" flow. On success it
// appends a Task_Deleted event; the projection removes the task and its
// participants/votes/comments from active state while the event journal keeps
// the audit trail.
task_service_delete_task :: proc(cmd: Task_Delete_Command) -> Task_Service_Result {
	if cmd.task_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task delete requires task_id"}`}
	}
	current, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}

	// Reject if other tasks in the same chain depend on this one (MVP: report ids).
	blocking := strings.builder_make()
	first := true
	for state in store_tasks_in_chain(current.chain_id) {
		if state.task_id == cmd.task_id do continue
		if task_depends_on_task(state.depends_on, cmd.task_id) {
			if !first do strings.write_string(&blocking, ",")
			first = false
			strings.write_string(&blocking, state.task_id)
		}
	}
	blocking_ids := strings.to_string(blocking)
	if blocking_ids != "" {
		b := strings.builder_make()
		strings.write_string(&b, `{"ok":false,"message":"task has dependents; detach them before deleting","error":"blocking_dependents","blocking_dependents":[`)
		bfirst := true
		for id_raw in strings.split(blocking_ids, ",") {
			id := strings.trim_space(id_raw)
			if id == "" do continue
			if !bfirst do strings.write_string(&b, ",")
			bfirst = false
			strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
		}
		strings.write_string(&b, `]}`)
		return Task_Service_Result{ok = false, status_code = 409, message = strings.to_string(b)}
	}

	// Clear any runtime current-task binding for the assignee before removal.
	if current.assignee_agent_instance_id != "" {
		_ = agent_store_clear_current_task_if_matches(current.assignee_agent_instance_id, cmd.task_id)
	}

	event := Task_Event{
		kind                     = .Task_Deleted,
		task_id                  = cmd.task_id,
		chain_id                 = current.chain_id,
		body                     = fmt.tprintf("task deleted by %s", cmd.author_agent_instance_id),
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	// Notify BEFORE appending the delete: task_notify_event resolves the task via
	// store_get_or_create_task_in_chain, which would re-materialize a placeholder
	// row if called after the projection removes the task. Notifying first lets
	// assignee/coordinator/subscribers learn of the deletion off the live row.
	task_notify_event(event)
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task delete failed"}`}
	}

	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","deleted":true}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_set_status :: proc(task_id, chain_id, status, body, author: string) -> Task_Service_Result {
	return task_service_status_command(Task_Status_Command{task_id = task_id, chain_id = chain_id, status = status, body = body, author_agent_instance_id = author})
}

task_service_status_command :: proc(cmd: Task_Status_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.status == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task status change requires task_id, status, and non-empty body"}`}
	}
	if !task_status_allowed(cmd.status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	status_val, ok := task_status_from_string(cmd.status)
	if !ok {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if !cmd.force && (state.status == .Approved || state.status == .Cancelled) && status_val != state.status {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"terminal task status cannot be changed without force","error":"terminal_status"}`}
	}
	if cmd.force {
		// A coordinator/operator force bypasses gating (dependencies, assignee
		// slot, unresolved comments, reviewer LGTM votes) for ANY valid status
		// transition, not just approved. This lets the coordinator drive the
		// control plane when they own the decision and no user gate is required.
		// Authorization stays restricted to the chain coordinator or operator,
		// and every forced transition is written as an audited
		// FORCE_REVIEW_BYPASS event below.
		if !task_force_advance_authorized(state, cmd.author_agent_instance_id) {
			return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"force requires chain coordinator or operator"}`}
		}
	} else {
		if status_val == .In_Progress {
			if dep_blockers := task_dependency_blocking_ids(state.depends_on); dep_blockers != "" {
				return task_gating_error("dependency", "unmet task dependencies", dep_blockers)
			}
			if !task_chain_allows_execution(state.chain_id) {
				return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task chain is not in_progress","error":"chain_not_active"}`}
			}
			if state.assignee_agent_instance_id == "" {
				return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task has no assignee","error":"unassigned"}`}
			}
			if active := task_active_slot_blocker(state.assignee_agent_instance_id, state.task_id); active != "" {
				return task_gating_error("assignee_active_task", "assignee already has an active task", active)
			}
		}
		if status_val == .Review_Ready || status_val == .Approved {
			unresolved := task_unresolved_comments(cmd.task_id)
			defer delete(unresolved)
			if len(unresolved) > 0 {
				return Task_Service_Result{
					ok = false,
					status_code = 400,
					message = fmt.tprintf(`{{"ok":false,"message":"task has %d unresolved comments"}}`, len(unresolved)),
				}
			}
		}
		if !task_status_change_authorized(state, status_val, cmd.author_agent_instance_id) {
			return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not authorized for task status transition"}`}
		}
	}
	event_body := cmd.body
	if cmd.force {
		event_body = fmt.tprintf("FORCE_REVIEW_BYPASS task_id=%s chain_id=%s coordinator_id=%s prior_status=%s new_status=%s reason=%s timestamp_unix_ms=%d", cmd.task_id, state.chain_id, cmd.author_agent_instance_id, task_status_to_string(state.status), cmd.status, cmd.body, router_now_unix_ms())
	}
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = cmd.task_id,
		chain_id                 = state.chain_id,
		status                   = cmd.status,
		body                     = event_body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task status failed"}`}
	}
	task_notify_event(event)
	if cmd.status == "in_progress" && state.assignee_agent_instance_id != "" {
		_ = task_chain_maybe_record_diff_base_sha(state.chain_id, "task_started")
		_ = agent_store_set_current_task(state.assignee_agent_instance_id, cmd.task_id)
	}
	if cmd.status == "in_progress" || cmd.status == "queued" || cmd.status == "review_ready" {
		_ = task_runtime_reconcile_task(cmd.task_id, "status_change", "high")
	}
	if state.status == .Review_Ready && cmd.status != "review_ready" {
		task_cancel_open_user_proxy_approvals(cmd.task_id, state.chain_id)
	}
	if cmd.status == "review_ready" || cmd.status == "blocked" || cmd.status == "queued" || cmd.status == "ready" || cmd.status == "approved" || cmd.status == "cancelled" {
		if state.assignee_agent_instance_id != "" do _ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, cmd.task_id)
		_ = agent_store_clear_current_task_if_matches(cmd.author_agent_instance_id, cmd.task_id)
	}

	manual_defer := (cmd.status == "queued" || cmd.status == "ready") && state.status == .In_Progress && task_actor_has_role(state, cmd.author_agent_instance_id, "assignee")
	defer_assignee := state.assignee_agent_instance_id

	task_recompute_promotions(cmd.author_agent_instance_id)
	if cmd.status == "queued" || cmd.status == "ready" {
		if manual_defer {
			if next_task := task_best_ready_task_for_assignee_excluding(defer_assignee, cmd.task_id); next_task != "" {
				task_service_auto_claim(next_task)
			}
		} else {
			task_service_auto_claim(cmd.task_id)
		}
	}
	task_service_try_auto_complete_chain(state.chain_id)
	if cmd.status == "review_ready" {
		task_notify_all_lgtm_required(cmd.task_id, state.chain_id)
		task_notify_user_proxy_review_requests(cmd.task_id, state.chain_id)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, cmd.status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_review_vote :: proc(cmd: Task_Review_Vote_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"review vote requires task_id and comment"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if state.status != .Review_Ready {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"can only vote on review_ready tasks"}`}
	}
	user_review_required := cmd.author_is_user && task_requires_user_review(state)
	vote_author := cmd.author_agent_instance_id
	fmt.printf("DEBUG VOTE: author=%s, is_user=%t, requires_user_review=%t\n", cmd.author_agent_instance_id, cmd.author_is_user, task_requires_user_review(state))
	if user_review_required {
		vote_author = task_reviewer_agent_instance_id(state)
		fmt.printf("DEBUG VOTE: user_review_required=true, vote_author reset to=%s\n", vote_author)
	}
	if proxy_reviewer, proxy_ok := task_user_proxy_reviewer_for(state, cmd.author_agent_instance_id); proxy_ok {
		vote_author = proxy_reviewer
		fmt.printf("DEBUG VOTE: proxy_ok=true, vote_author reset to=%s\n", vote_author)
	}
	fmt.printf("DEBUG VOTE: final vote_author=%s\n", vote_author)
	is_required  := task_actor_has_role(state, vote_author, "lgtm_required")
	if !is_required && (user_review_required || vote_author == task_reviewer_agent_instance_id(state)) {
		is_required = true
	}
	is_optional  := task_actor_has_role(state, vote_author, "lgtm_optional")
	can_override := task_actor_can_override(state, cmd.author_agent_instance_id)
	if !is_required && !is_optional && !can_override {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not a reviewer for this task"}`}
	}
	role := "lgtm_optional"
	if is_required do role = "lgtm_required"
	vote_approved_str := "true" if cmd.approved else "false"
	event := Task_Event{
		kind                     = .Task_Review_Vote,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		vote_approved            = vote_approved_str,
		role                     = role,
		body                     = cmd.comment,
		author_agent_instance_id = vote_author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append review vote failed"}`}
	}
	task_notify_event(event)
	_ = agent_store_clear_current_task(cmd.author_agent_instance_id)
	task_cancel_open_user_proxy_approvals(cmd.task_id, cmd.chain_id)
	if !cmd.approved {
		back_event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = cmd.task_id,
			chain_id                 = cmd.chain_id,
			status                   = "in_progress",
			body                     = fmt.tprintf("ngtm by %s: %s", vote_author, cmd.comment),
			author_agent_instance_id = "system-review-vote",
		}
		if task_store_append_event(back_event) {
			if state.assignee_agent_instance_id != "" do _ = agent_store_set_current_task(state.assignee_agent_instance_id, cmd.task_id)
			task_notify_event(back_event)
			_ = task_runtime_reconcile_task(cmd.task_id, "status_change", "high")
		}
	} else if task_all_required_lgtms_approved(cmd.task_id) {
		task_service_auto_approve(cmd.task_id, cmd.chain_id)
	}
	task_recompute_promotions(vote_author)
	task_notify_reviewer_rotation(vote_author)
	result_status := "review_ready"
	if updated_state, updated_found := store_get_task_in_chain(cmd.task_id, cmd.chain_id); updated_found {
		result_status = task_status_to_string(updated_state.status)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, result_status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_user_proxy_reviewer_for :: proc(state: Task_State, user_id: string) -> (string, bool) {
	if user_id == "" do return "", false
	if user_id != HUMAN_RECIPIENT_ID && user_id != "user_proxy" do return "", false
	default_rev := task_reviewer_agent_instance_id(state)
	if default_rev == "user_proxy" do return "user_proxy", true
	parts := store_participants_of(state.task_id)
	defer delete(parts)
	for p in parts {
		if p.agent_instance_id == "user_proxy" && (p.role == "lgtm_required" || p.role == "lgtm_optional") do return "user_proxy", true
	}
	return "", false
}

task_notify_user_proxy_review_requests :: proc(task_id, chain_id: string) {
	state, found := store_get_task_in_chain(task_id, chain_id)
	if !found || !task_requires_user_review(state) do return
	chain, chain_found := store_get_chain(state.chain_id)
	if !chain_found do return
	sender := chain.coordinator_agent_instance_id
	if sender == "" do sender = "user_proxy"
	body := task_user_proxy_review_card_json(state)
	message_id, ok := chat_store_append_message_with_chain(HUMAN_RECIPIENT_ID, sender, "agent_to_user", body, true, state.chain_id)
	if ok {
		chat_event_fanout(HUMAN_RECIPIENT_ID, sender, message_id, "agent_to_user", state.chain_id)
		if det := chat_approval_detect_payload(body); det.matched {
			_, _ = chat_approval_service_record(det, message_id, state.chain_id, HUMAN_RECIPIENT_ID, sender)
		}
	}
}

// Called when a task exits review_ready (approved / regressed to in_progress /
// cancelled). Any open user_proxy approvals bound to the chain that reference
// this task_id must be cancelled so the operator inbox is not stranded.
task_cancel_open_user_proxy_approvals :: proc(task_id, chain_id: string) {
	if chain_id == "" do return
	rows := chat_approval_db_list_open_for_chain(chain_id)
	for rec in rows {
		if !strings.contains(rec.options_json, task_id) do continue
		_ = chat_approval_service_terminal(rec.approval_id, "cancelled", "", "system-task-service", "task_left_review_ready", "")
	}
}

task_user_proxy_review_card_json :: proc(state: Task_State) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"type":"smart_answer","body":"Review task `)
	json_write_string(&b, state.task_id)
	strings.write_string(&b, `: `)
	json_write_string(&b, state.title)
	strings.write_string(&b, `","suggested_replies":[`)
	strings.write_string(&b, `"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"lgtm\"}"`)
	strings.write_string(&b, `,"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"ngtm\"}"`)
	strings.write_string(&b, `]}`)
	return strings.to_string(b)
}

task_service_user_proxy_review_reply :: proc(user_id, coordinator_agent_instance_id, reply: string) -> Task_Service_Result {
	if extract_json_string(reply, "action", "") != "user_proxy_review" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"not a user_proxy review reply"}`}
	}
	task_id := extract_json_string(reply, "task_id", "")
	result := extract_json_string(reply, "result", "")
	approved := result == "lgtm"
	rejected := result == "ngtm"
	if task_id == "" || (!approved && !rejected) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid user_proxy review reply"}`}
	}
	state, found := store_get_task_in_chain(task_id, "")
	if !found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	if state.status != .Review_Ready do return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task is not pending review"}`}
	chain, chain_found := store_get_chain(state.chain_id)
	if !chain_found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	if coordinator_agent_instance_id != "" && chain.coordinator_agent_instance_id != coordinator_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"reply coordinator mismatch"}`}
	}
	if _, ok := task_user_proxy_reviewer_for(state, user_id); !ok {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"user is not the user_proxy reviewer"}`}
	}
	comment := "operator user_proxy LGTM"
	if rejected do comment = "operator user_proxy NGTM"
	return task_service_review_vote(Task_Review_Vote_Command{task_id = state.task_id, chain_id = state.chain_id, approved = approved, comment = comment, author_agent_instance_id = user_id, author_is_user = true})
}

task_service_auto_approve :: proc(task_id, chain_id: string) {
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = chain_id,
		status                   = "approved",
		body                     = "system_auto:all_lgtm_required_approved",
		author_agent_instance_id = "system-auto-approve",
	}
	if task_store_append_event(event) {
		if state, found := store_get_task_in_chain(task_id, chain_id); found && state.assignee_agent_instance_id != "" {
			_ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, task_id)
		}
		task_notify_event(event)
		task_recompute_promotions("system-auto-approve")
		task_service_try_auto_complete_chain(chain_id)
	}
}

task_service_auto_claim :: proc(task_id: string) {
	state, found := store_get_task_in_chain(task_id, "")
	if !found do return
	if state.status != .Queued do return
	if !task_dependencies_satisfied(state.depends_on) do return
	if !task_ready_allows_auto_claim(state) do return
	if !task_chain_allows_execution(state.chain_id) do return
	assignee := state.assignee_agent_instance_id
	if assignee == "" do return
	if best_ready := task_best_ready_task_for_assignee(assignee); best_ready != "" && best_ready != task_id do return
	if task_active_slot_blocker(assignee, task_id) != "" do return
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = state.chain_id,
		status                   = "in_progress",
		body                     = "system_auto:auto_claimed",
		author_agent_instance_id = "system-auto-claim",
	}
	if task_store_append_event(event) {
		_ = task_chain_maybe_record_diff_base_sha(state.chain_id, "task_auto_claimed")
		_ = agent_store_set_current_task(assignee, task_id)
		task_notify_event(event)
		_ = task_runtime_reconcile_task(task_id, "auto_claim", "high")
	}
}

task_service_try_auto_complete_chain :: proc(chain_id: string) {
	if chain_id == "" do return
	chain, found := store_get_chain(chain_id)
	if !found do return
	if chain.status == "reviewing" || chain.status == "paused" || chain.status == "completed" || chain.status == "archived" do return
	if !task_all_chain_tasks_terminal(chain_id) do return
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = chain_id,
		status                   = "reviewing",
		body                     = "system_auto:all_tasks_terminal_review_required",
		author_agent_instance_id = "system-auto-complete",
	}
	if task_store_append_event(event) {
		task_notify_event(event)
		task_service_ping_coordinator_for_chain_completion(chain_id)
	}
}

task_service_ping_coordinator_for_chain_completion :: proc(chain_id: string) {
	chain, found := store_get_chain(chain_id)
	if !found do return
	if chain.coordinator_agent_instance_id == "" do return

	message_body := fmt.tprintf(
		"All tasks in your task chain '%s' (ID: %s) have been completed!\n\n" +
		"As the designated coordinator, you must now review the results and move the task chain to 'completed' using the 'ham-ctl task-chains status --status completed --final-summary \"...\"' command.\n\n" +
		"Your final summary must strictly comply with the Task Chain Best Practices below:\n\n%s",
		chain.title,
		chain.chain_id,
		TASK_CHAIN_BEST_PRACTICES,
	)

	_, ok := chat_store_append_message_with_chain(HUMAN_RECIPIENT_ID, chain.coordinator_agent_instance_id, "user_to_agent", message_body, false, chain_id)
	if !ok {
		fmt.println("WARNING: Failed to append completion ping message to coordinator agent:", chain.coordinator_agent_instance_id)
	} else {
		fmt.println("INFO: Successfully pinged coordinator agent", chain.coordinator_agent_instance_id, "for chain completion of", chain_id)
	}
}

task_service_nudge :: proc(task_id, chain_id, body, author: string, interrupt: bool) -> Task_Service_Result {
	return task_service_nudge_command(Task_Nudge_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author, interrupt = interrupt})
}

task_service_nudge_command :: proc(cmd: Task_Nudge_Command) -> Task_Service_Result {
	if cmd.task_id == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"nudge requires task_id and non-empty body"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if task_status_terminal(state.status) {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"terminal task cannot be nudged"}`}
	}
	target := task_nudge_target_for_status(state, state.status)
	if target == "" {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"no nudge target for task status"}`}
	}
	event := Task_Event{
		kind                     = .Task_Nudged,
		task_id                  = state.task_id,
		chain_id                 = state.chain_id,
		status                   = task_status_to_string(state.status),
		body                     = cmd.body,
		agent_instance_id        = target,
		author_agent_instance_id = cmd.author_agent_instance_id,
		interrupt                = cmd.interrupt,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task nudge failed"}`}
	}
	_ = task_runtime_reconcile_task(state.task_id, "manual_nudge", "high")
	delivery := task_notify_nudge_delivery(event)
	delivery_state := "skipped"
	if delivery.live_delivered {
		delivery_state = "delivered"
	} else if delivery.durable_queued {
		delivery_state = "queued"
	} else if delivery.failed {
		delivery_state = "failed"
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":`); strings.write_string(&b, "false" if delivery.failed else "true")
	strings.write_string(&b, `,"target_agent_instance_id":"`); json_write_string(&b, target)
	strings.write_string(&b, `","sent":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"live_delivered":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"durable_queued":`); strings.write_string(&b, "true" if delivery.durable_queued else "false")
	strings.write_string(&b, `,"failed":`); strings.write_string(&b, "true" if delivery.failed else "false")
	strings.write_string(&b, `,"delivery_state":"`); json_write_string(&b, delivery_state)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = !delivery.failed, status_code = 200 if !delivery.failed else 500, message = strings.to_string(b)}
}

task_service_update_chain :: proc(cmd: Task_Chain_Update_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain update requires chain_id"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	old_coordinator := chain.coordinator_agent_instance_id
	old_default_reviewer := chain.default_reviewer_agent_instance_id
	new_coordinator := cmd.coordinator_agent_instance_id
	if new_coordinator != "" {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(cmd.chain_id, chain.project_id, new_coordinator, "coordinator", cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		if resolved == "user_proxy" || resolved == HUMAN_RECIPIENT_ID {
			return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"coordinator cannot be user_proxy"}`}
		}
		new_coordinator = resolved
	} else {
		new_coordinator = old_coordinator
	}
	new_default_reviewer, default_reviewer_normalized := task_normalize_user_reviewer(cmd.default_reviewer_agent_instance_id)
	if new_default_reviewer != "" && new_default_reviewer != "user_proxy" && new_default_reviewer != HUMAN_RECIPIENT_ID {
		resolved, resolve_ok, resolve_msg := task_service_resolve_agent_reference_for_chain(cmd.chain_id, chain.project_id, new_default_reviewer, "lgtm_required", cmd.author_agent_instance_id)
		if !resolve_ok do return Task_Service_Result{ok = false, status_code = 400, message = task_service_error_json(resolve_msg)}
		new_default_reviewer = resolved
	}
	if new_default_reviewer == "" do new_default_reviewer = old_default_reviewer
	if new_default_reviewer != "" && new_default_reviewer == new_coordinator {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	if new_default_reviewer != "" {
		for state in store_tasks_in_chain(cmd.chain_id) {
			if task_status_terminal(state.status) do continue
			if state.assignee_agent_instance_id == new_default_reviewer {
				return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee of an active task in the chain"}`}
			}
		}
	}
	event_default_reviewer := ""
	if cmd.default_reviewer_agent_instance_id != "" do event_default_reviewer = new_default_reviewer
	event_coordinator := ""
	if cmd.coordinator_agent_instance_id != "" do event_coordinator = new_coordinator
	audit_body := fmt.tprintf("chain metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, chain.description, cmd.description)
	event := Task_Event{
		kind                          = .Chain_Metadata_Updated,
		chain_id                      = cmd.chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		body                          = audit_body,
		coordinator_agent_instance_id = event_coordinator,
		reviewer_agent_instance_id    = event_default_reviewer,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain update failed"}`}
	}
	task_notify_event(event)
	coordinator_changed := cmd.coordinator_agent_instance_id != "" && old_coordinator != new_coordinator
	default_reviewer_changed := cmd.default_reviewer_agent_instance_id != "" && old_default_reviewer != new_default_reviewer
	if coordinator_changed {
		_ = task_notify_chain_role_change_recipients(event, chain.status, "coordinator", old_coordinator, new_coordinator)
		_ = task_runtime_reconcile_chain_coordinator(cmd.chain_id, "coordinator_changed", "high")
	}
	if default_reviewer_changed {
		_ = task_notify_chain_role_change_recipients(event, chain.status, "default_reviewer", old_default_reviewer, new_default_reviewer)
	}
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(summary_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain summary failed"}`}
		}
		task_notify_event(summary_event)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true`)
	task_write_user_proxy_warning_if_needed(&b, default_reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_set_chain_status :: proc(chain_id, status, final_summary, author: string) -> Task_Service_Result {
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = status, final_summary = final_summary, author_agent_instance_id = author})
}

task_service_chain_status_command :: proc(cmd: Task_Chain_Status_Command) -> Task_Service_Result {
	if cmd.chain_id == "" || cmd.status == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain status requires chain_id and status"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	stored_summary := chain.final_summary
	if cmd.status == "completed" && strings.trim_space(cmd.final_summary) == "" && stored_summary == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"final_summary required for completed status"}`}
	}
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		task_store_append_event(summary_event)
		task_notify_event(summary_event)
	}
	kind := Task_Event_Kind.Chain_Status_Changed
	if cmd.status == "completed" do kind = .Chain_Completed
	status_event := Task_Event{
		kind                     = kind,
		chain_id                 = cmd.chain_id,
		status                   = cmd.status,
		body                     = cmd.final_summary,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(status_event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain status failed"}`}
	}
	task_notify_event(status_event)
	if cmd.status == "in_progress" {
		_ = task_chain_maybe_record_diff_base_sha(cmd.chain_id, "chain_status_in_progress")
		_ = task_autoscaler_ensure_chain_coordinator(cmd.chain_id, "chain_status_in_progress", "high")
	}

	// Orchestrate member tasks based on the new chain status
	if cmd.status == "completed" || cmd.status == "archived" || cmd.status == "planning" || cmd.status == "paused" {
		for state in store_tasks_in_chain(cmd.chain_id) {
			if task_status_terminal(state.status) do continue

			next_status := ""
			body_text := ""
			if cmd.status == "completed" || cmd.status == "archived" {
				next_status = "cancelled"
				body_text = "system_auto:chain_completed"
			} else if cmd.status == "planning" || cmd.status == "paused" {
				if state.status == .In_Progress {
					next_status = "queued"
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				} else if state.status == .Queued {
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				}
			}
			if next_status == "" do continue
			next_status_val, _ := task_status_from_string(next_status)
			if state.status == next_status_val && body_text == "" do continue

			event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = state.task_id,
				chain_id                 = state.chain_id,
				status                   = next_status,
				body                     = body_text,
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if task_store_append_event(event) {
				task_notify_event(event)
			}
		}
		task_recompute_promotions(cmd.author_agent_instance_id)
	} else if cmd.status == "in_progress" || cmd.status == "queued" || cmd.status == "ready" {
		task_recompute_promotions(cmd.author_agent_instance_id)
	}

	// On completion, surface a merge decision for VCS chains when needed.
	if cmd.status == "completed" {
		merge_lifecycle_on_chain_completed(cmd.chain_id, cmd.author_agent_instance_id)
	}
	if cmd.status == "completed" || cmd.status == "archived" || cmd.status == "cancelled" || cmd.status == "abandoned" {
		_ = task_autoscaler_stop_chain_agents(cmd.chain_id, strings.concatenate({"chain_status_", cmd.status}))
	}

	archive_ok := true
	if cmd.status == "completed" || cmd.status == "archived" {
		archive_ok = task_archive_chain_to_hub(cmd.chain_id)
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true,"archive_ok":true}` if archive_ok else `{"ok":true,"archive_ok":false,"archive_pending":true}`}
}

task_service_complete_chain :: proc(chain_id, final_summary, author: string) -> Task_Service_Result {
	if chain_id == "" || strings.trim_space(final_summary) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain complete requires chain_id and non-empty summary"}`}
	}
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = "completed", final_summary = final_summary, author_agent_instance_id = author})
}

task_service_retry_pending_archives :: proc() -> Task_Service_Result {
	retried := task_store_retry_pending_archives()
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"retried":`)
	strings.write_string(&b, fmt.tprintf("%d", retried))
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_gating_error :: proc(error_kind, message, blocking_task_ids: string) -> Task_Service_Result {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message)
	strings.write_string(&b, `","error":"`);             json_write_string(&b, error_kind)
	strings.write_string(&b, `","blocking_task_ids":[`)
	ids   := strings.split(blocking_task_ids, ",")
	first := true
	for id_raw in ids {
		id := strings.trim_space(id_raw)
		if id == "" do continue
		if !first do strings.write_string(&b, `,`)
		first = false
		strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
	}
	strings.write_string(&b, `]}`)
	return Task_Service_Result{ok = false, status_code = 409, message = strings.to_string(b)}
}

task_dependency_validation_error :: proc(message, error_kind, dependency_task_ids: string) -> Task_Service_Result {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message)
	strings.write_string(&b, `","error":"`);             json_write_string(&b, error_kind)
	strings.write_string(&b, `","dependency_task_ids":[`)
	ids   := strings.split(dependency_task_ids, ",")
	first := true
	for id_raw in ids {
		id := strings.trim_space(id_raw)
		if id == "" do continue
		if !first do strings.write_string(&b, `,`)
		first = false
		strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
	}
	strings.write_string(&b, `]}`)
	return Task_Service_Result{ok = false, status_code = 400, message = strings.to_string(b)}
}

task_validate_dependency_ids :: proc(depends_on, chain_id, self_task_id: string) -> (message: string, error_kind: string, dependency_task_ids: string, ok: bool) {
	deps := strings.split(depends_on, ",")
	for dep in deps {
		id := strings.trim_space(dep)
		if id == "" do continue
		if id == self_task_id {
			return "task cannot depend on itself", "self_dependency", id, false
		}
		state, found := store_get_task(id)
		if !found {
			return "dependency task not found", "dependency_not_found", id, false
		}
		if chain_id != "" && state.chain_id != chain_id {
			return "dependency task must be in the same chain", "dependency_cross_chain", id, false
		}
	}
	return "", "", "", true
}

task_service_evaluate_chain :: proc(chain_id, evaluation, author: string) -> Task_Service_Result {
	if chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain evaluation requires chain_id"}`}
	}
	if evaluation != "good" && evaluation != "bad" && evaluation != "unreviewed" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid evaluation value. Expected: good, bad, unreviewed"}`}
	}
	if !store_chain_exists(chain_id) {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Evaluated,
		chain_id                 = chain_id,
		body                     = evaluation,
		author_agent_instance_id = author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain evaluation failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_halt_active_tasks_for_agent :: proc(agent_id: string) {
	if agent_id == "" do return
	for state in store_tasks_for_assignee(agent_id) {
		if state.status != .In_Progress do continue
		
		event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = state.task_id,
			chain_id                 = state.chain_id,
			status                   = "blocked",
			body                     = "system_block:assignee_active_task:pending_reviews_exist",
			author_agent_instance_id = "system-reviewer-gate",
		}
		if task_store_append_event(event) {
			task_notify_event(event)
		}
	}
}

