package main

import "core:fmt"
import "core:strings"
import vcs "odin_test:lib/vcs"

TASK_CHAIN_BEST_PRACTICES :: `## Task Chain Best Practices

When coordinating a task chain, you must adhere to the following workflow upon task completion:

1. **Verify All Tasks:** Review the outputs of all individual tasks in this chain to ensure they are fully complete, correct, and work together.
2. **Submit Verifiable Evidence:** When moving the task chain to 'completed' (using the 'ham-ctl task-chains status --status completed --final-summary "..."' command), you must provide a comprehensive, high-fidelity final summary. This summary MUST include:
   - **Verifiable Results/Evidence:** Specific outputs, behavior descriptions, or test logs proving correctness.
   - **Git Commits:** The hashes of all commits created or reviewed as part of this task chain.
   - **File Paths:** Precise relative or absolute paths of the files modified or created.
   - **Result Summary:** A concise overview of the accomplishments.
3. **Propose Quality Rating:** Propose a quality rating status of 'good' or 'bad' for this task chain.
4. **Reasoning:** Provide clear, objective engineering rationale explaining why the chain succeeded ('good') or if there were critical defects or difficulties encountered ('bad').`

Task_Service_Result :: struct {
	ok:          bool,
	status_code: int,
	message:     string,
}

USER_PROXY_REVIEWER_WARNING :: "operator@local reviewer normalized to user_proxy; prefer user_proxy for user-facing task reviews"

task_normalize_user_reviewer :: proc(agent_instance_id: string) -> (string, bool) {
	if task_actor_is_user(agent_instance_id) {
		return "user_proxy", true
	}
	return agent_instance_id, false
}

task_write_user_proxy_warning_if_needed :: proc(b: ^strings.Builder, normalized: bool) {
	if !normalized do return
	strings.write_string(b, `,"warning":"`)
	json_write_string(b, USER_PROXY_REVIEWER_WARNING)
	strings.write_string(b, `"`)
}

task_service_create_task :: proc(cmd: Task_Create_Command) -> Task_Service_Result {
	if cmd.task_id != "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task_id is generated by daemon; omit task_id on create"}`}
	}
	if cmd.title == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task create requires title"}`}
	}
	reviewer_agent_instance_id, reviewer_normalized := task_normalize_user_reviewer(cmd.reviewer_agent_instance_id)
	if cmd.assignee_agent_instance_id != "" && cmd.assignee_agent_instance_id == reviewer_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the reviewer"}`}
	}
	if cmd.assignee_agent_instance_id != "" && reviewer_agent_instance_id == "" && cmd.chain_id != "" && task_chain_default_reviewer_agent_instance_id(cmd.chain_id) == cmd.assignee_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	task_id := task_generate_id()
	status := cmd.status
	if status == "" do status = "planning"
	if !task_status_allowed(status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if cmd.depends_on != "" {
		if cmd.chain_id == "" {
			return task_dependency_validation_error("depends_on requires chain_id", "missing_chain", cmd.depends_on)
		}
		if dep_error, dep_error_kind, dep_ids, dep_ok := task_validate_dependency_ids(cmd.depends_on, cmd.chain_id, task_id); !dep_ok {
			return task_dependency_validation_error(dep_error, dep_error_kind, dep_ids)
		}
	}
	if status == "ready" || status == "in_progress" {
		if dep_blockers := task_dependency_blocking_ids(cmd.depends_on); dep_blockers != "" {
			return task_gating_error("dependency", "unmet task dependencies", dep_blockers)
		}
		if cmd.assignee_agent_instance_id != "" {
			if active := task_active_slot_blocker(cmd.assignee_agent_instance_id, ""); active != "" {
				return task_gating_error("assignee_active_task", "assignee already has an active task", active)
			}
		}
	}
	chain_id      := cmd.chain_id
	created_chain := false
	if chain_id == "" && !cmd.standalone {
		chain_id = task_chain_id_for_root(task_id)
		chain_event := Task_Event{
			kind                        = .Chain_Created,
			chain_id                    = chain_id,
			project_id                  = cmd.project_id,
			title                       = cmd.title,
			description                 = cmd.description,
			status                      = "planning",
			coordinator_agent_instance_id = cmd.created_by,
			author_agent_instance_id    = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(chain_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task chain create failed"}`}
		}
		created_chain = true
	}
	if cmd.assignee_agent_instance_id != "" && !task_agent_instance_allowed_for_chain(chain_id, cmd.assignee_agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee is not an eligible agent (unknown or archived)"}`}
	}
	if cmd.assignee_agent_instance_id != "" && task_agent_instance_has_chain_role(chain_id, cmd.assignee_agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if reviewer_agent_instance_id != "" && !task_agent_instance_allowed_for_chain(chain_id, reviewer_agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer is not an eligible agent (unknown or archived)"}`}
	}
	priority := cmd.priority
	if priority == "" do priority = "normal"
	event := Task_Event{
		kind                          = .Task_Created,
		task_id                       = task_id,
		chain_id                      = chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		acceptance_criteria           = cmd.acceptance_criteria,
		priority                      = priority,
		status                        = status,
		assignee_agent_instance_id    = cmd.assignee_agent_instance_id,
		reviewer_agent_instance_id    = reviewer_agent_instance_id,
		depends_on                    = cmd.depends_on,
		created_by                    = cmd.created_by,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task create failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`);    json_write_string(&b, task_id)
	strings.write_string(&b, `","chain_id":"`);            json_write_string(&b, chain_id)
	strings.write_string(&b, `","root_task_id":"`);        json_write_string(&b, task_root_id_for_response(chain_id, task_id, created_chain))
	strings.write_string(&b, `","created_chain":`);        strings.write_string(&b, "true" if created_chain else "false")
	strings.write_string(&b, `,"standalone":`);            strings.write_string(&b, "true" if cmd.standalone else "false")
	task_write_user_proxy_warning_if_needed(&b, reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_create_chain :: proc(cmd: Task_Chain_Create_Command) -> Task_Service_Result {
	if cmd.kind == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain create requires kind"}`}
	}
	kind := team_kind_get(cmd.kind)
	if kind == nil {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"unknown team kind"}`}
	}
	chain_title := cmd.title
	if chain_title == "" do chain_title = task_service_default_chain_title(kind)
	chain_id := cmd.chain_id
	if chain_id == "" do chain_id = task_generate_chain_id()
	team_id := team_service_create_for_chain(cmd.project_id, chain_id, cmd.kind, "", cmd.coordinator_agent_instance_id)
	if team_id == "" {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"team allocation failed"}`}
	}
	coordinator_agent_instance_id := cmd.coordinator_agent_instance_id
	if coordinator_agent_instance_id == "" {
		coordinator_agent_instance_id = task_service_chain_member_for_role(team_id, "coordinator")
	}
	if coordinator_agent_instance_id == "" {
		_ = team_service_archive(team_id, "coordinator_missing")
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"coordinator allocation failed"}`}
	}
	default_reviewer_agent_instance_id, default_reviewer_normalized := task_normalize_user_reviewer(cmd.default_reviewer_agent_instance_id)
	if default_reviewer_agent_instance_id != "" && default_reviewer_agent_instance_id == coordinator_agent_instance_id {
		_ = team_service_archive(team_id, "invalid_default_reviewer")
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	// Do not create Git/JJ workspaces synchronously during chain creation.
	// Worktree creation can require user approval and may fail on local refs; for
	// VCS-backed chains we create an explicit coordinator task before discovery.
	workspace_id := ""
	event := Task_Event{
		kind                          = .Chain_Created,
		chain_id                      = chain_id,
		project_id                    = cmd.project_id,
		team_id                       = team_id,
		vcs_workspace_id              = workspace_id,
		title                         = chain_title,
		description                   = cmd.description,
		status                        = "in_progress",
		coordinator_agent_instance_id = coordinator_agent_instance_id,
		reviewer_agent_instance_id    = default_reviewer_agent_instance_id,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		_ = team_service_archive(team_id, "chain_create_failed")
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain create failed"}`}
	}
	_ = task_chain_maybe_record_diff_base_sha(chain_id, "chain_created")
	task_notify_event(event)
	// Request coordinator runtime immediately after the chain exists, before
	// workspace/discovery/scaffold task creation. Later task/status transitions
	// still reconcile idempotently, but this makes boot independent of those
	// follow-up events and gives the UI an immediate launch request to observe.
	coordinator_boot_requested := task_runtime_reconcile_chain_coordinator(chain_id, "chain_created", "high")
	workspace_setup_task_id := ""
	if cmd.wants_vcs {
		workspace_setup_task_id = task_service_create_workspace_setup_task(chain_id, cmd.project_id, team_id, chain_title, coordinator_agent_instance_id, cmd.author_agent_instance_id)
		if workspace_setup_task_id == "" {
			_ = team_service_archive(team_id, "workspace_setup_task_create_failed")
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append workspace setup task failed"}`}
		}
	}
	scaffold_selected := cmd.scaffold != "" && cmd.scaffold != "none" && !cmd.no_scaffold
	discovery_task_id := task_service_create_coordinator_discovery_task(chain_id, chain_title, cmd.description, kind, coordinator_agent_instance_id, cmd.author_agent_instance_id, workspace_setup_task_id, scaffold_selected)
	if discovery_task_id == "" {
		_ = team_service_archive(team_id, "discovery_task_create_failed")
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append coordinator discovery task failed"}`}
	}
	if scaffold_selected {
		legacy_cmd := cmd
		legacy_cmd.chain_id = chain_id
		legacy_cmd.title = chain_title
		legacy_cmd.coordinator_agent_instance_id = coordinator_agent_instance_id
		legacy_cmd.default_reviewer_agent_instance_id = default_reviewer_agent_instance_id
		if ok, msg := task_service_create_chain_scaffold(chain_id, team_id, legacy_cmd, kind, discovery_task_id); !ok {
			if workspace_id != "" do task_service_cleanup_workspace(chain_id)
			_ = team_service_archive(team_id, "scaffold_create_failed")
			return Task_Service_Result{ok = false, status_code = 500, message = task_service_error_json(msg)}
		}
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"chain_id":"`); json_write_string(&b, chain_id)
	strings.write_string(&b, `","team_id":"`); json_write_string(&b, team_id)
	strings.write_string(&b, `","vcs_workspace_id":"`); json_write_string(&b, workspace_id)
	strings.write_string(&b, `","workspace_setup_task_id":"`); json_write_string(&b, workspace_setup_task_id)
	strings.write_string(&b, `","discovery_task_id":"`); json_write_string(&b, discovery_task_id)
	strings.write_string(&b, `","coordinator_agent_instance_id":"`); json_write_string(&b, coordinator_agent_instance_id)
	strings.write_string(&b, `","coordinator_boot_requested":`); strings.write_string(&b, "true" if coordinator_boot_requested else "false")
	strings.write_string(&b, `,"status":"in_progress"`)
	task_write_user_proxy_warning_if_needed(&b, default_reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_default_chain_title :: proc(kind: ^Team_Kind_Def) -> string {
	if kind == nil do return "New task chain"
	if kind.display_name != "" do return fmt.tprintf("New %s chain", kind.display_name)
	if kind.key != "" do return fmt.tprintf("New %s chain", kind.key)
	return "New task chain"
}

task_service_chain_member_for_role :: proc(team_id, role_key: string) -> string {
	members := team_db_list_members(team_service_db, team_id)
	for member in members {
		if member.role_key != role_key do continue
		if member.agent_instance_id != "" do return member.agent_instance_id
		return team_service_member_agent_instance_id("", "", team_id, member.role_key, member.role_index)
	}
	return ""
}

task_service_create_workspace_setup_task :: proc(chain_id, project_id, team_id, chain_title, coordinator_agent_instance_id, author: string) -> string {
	task_id := task_generate_id()
	description := task_service_workspace_setup_description(project_id, team_id, chain_id, chain_title)
	members := team_db_list_members(team_service_db, team_id)
	defer delete(members)
	reviewer := task_service_pick_non_user_reviewer(team_id, project_id, chain_id, coordinator_agent_instance_id, members, []string{"reviewer"})
	if reviewer == "" do reviewer = task_service_pick_non_user_reviewer(team_id, project_id, chain_id, coordinator_agent_instance_id, members, []string{})
	event := Task_Event{
		kind                       = .Task_Created,
		task_id                    = task_id,
		chain_id                   = chain_id,
		title                      = "Prepare chain workspace",
		description                = description,
		priority                   = "normal",
		status                     = "ready",
		assignee_agent_instance_id = coordinator_agent_instance_id,
		reviewer_agent_instance_id  = reviewer,
		created_by                 = author,
		author_agent_instance_id   = author,
	}
	if !task_store_append_event(event) do return ""
	task_notify_event(event)
	return task_id
}

task_service_workspace_setup_description :: proc(project_id, team_id, chain_id, chain_title: string) -> string {
	repo := ""
	base_ref := task_service_project_base_ref(project_id)
	worktree_root := fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id)
	vcs_kind := "auto"
	if pidx := project_index(project_id); pidx >= 0 {
		project := project_records[pidx]
		repo = project_anchor_value(project, "directory", "")
		base_ref = project_anchor_value(project, "base_ref", base_ref)
		worktree_root = project_anchor_value(project, "worktree_root", worktree_root)
		vcs_kind = project_anchor_value(project, "vcs_kind", vcs_kind)
	}
	slug := task_chain_slug(chain_title, chain_id)
	path := fmt.tprintf("%s/team/%s/%s", strings.trim_right(worktree_root, "/"), team_id, slug)
	branch := vcs_git_safe_branch_name(fmt.tprintf("team-%s-%s", team_id, slug))
	b := strings.builder_make()
	strings.write_string(&b, "Prepare the VCS workspace for this chain before doing discovery/planning.\n\n")
	strings.write_string(&b, "## Required approval\n")
	strings.write_string(&b, "Do not run any VCS command until you have asked the user in chain chat and received explicit approval. Show the exact command(s) you plan to run.\n\n")
	strings.write_string(&b, "## Expected workspace\n")
	strings.write_string(&b, "- Project directory: "); strings.write_string(&b, repo if repo != "" else "not configured"); strings.write_string(&b, "\n")
	strings.write_string(&b, "- VCS kind: "); strings.write_string(&b, vcs_kind); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Base ref: "); strings.write_string(&b, base_ref); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Worktree path: "); strings.write_string(&b, path); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Suggested branch name, if the user approves branch creation: "); strings.write_string(&b, branch); strings.write_string(&b, "\n\n")
	strings.write_string(&b, "## Suggested Git commands\n")
	strings.write_string(&b, "First ask the user to approve these commands. After approval, prefer a detached worktree first so chain creation does not depend on branch ref creation:\n\n")
	strings.write_string(&b, "```bash\n")
	strings.write_string(&b, fmt.tprintf("mkdir -p %s\n", shell_quote(vcs.vcs_workspace_parent(path))))
	strings.write_string(&b, fmt.tprintf("git -C %s fetch --quiet origin %s || true\n", shell_quote(repo), shell_quote(base_ref)))
	strings.write_string(&b, fmt.tprintf("git -C %s worktree add --detach %s %s\n", shell_quote(repo), shell_quote(path), shell_quote(base_ref)))
	strings.write_string(&b, fmt.tprintf("git -C %s switch -c %s\n", shell_quote(path), shell_quote(branch)))
	strings.write_string(&b, "```\n\n")
	strings.write_string(&b, "If branch creation fails, keep the detached worktree and report the failure in a task comment instead of blocking chain creation.\n\n")
	strings.write_string(&b, "## Completion evidence\n")
	strings.write_string(&b, "Comment with the approved commands, actual workspace path, branch/detached state, base ref, and `git -C <path> status --short --branch` output. Then mark this task done. The discovery task is intentionally blocked on this task.\n")
	return strings.to_string(b)
}

vcs_git_safe_branch_name :: proc(name: string) -> string {
	clean, _ := strings.replace_all(name, "/", "-")
	clean, _ = strings.replace_all(clean, "@", "-")
	clean, _ = strings.replace_all(clean, " ", "-")
	clean = strings.trim(clean, "-.")
	if clean == "" do clean = "workspace"
	return strings.clone(fmt.tprintf("heimdall-%s", clean))
}

task_service_create_coordinator_discovery_task :: proc(chain_id, chain_title, chain_description: string, kind: ^Team_Kind_Def, coordinator_agent_instance_id, author: string, depends_on: string = "", scaffold_selected: bool = false) -> string {
	task_id := task_generate_id()
	kind_name := "team"
	if kind != nil && kind.display_name != "" do kind_name = kind.display_name
	description := task_service_coordinator_discovery_description(chain_title, chain_description, kind_name, scaffold_selected)
	event := Task_Event{
		kind                       = .Task_Created,
		task_id                    = task_id,
		chain_id                   = chain_id,
		title                      = "Validate task chain scaffold" if scaffold_selected else "Update task chain from user requirement",
		description                = description,
		priority                   = "normal",
		status                     = "ready" if depends_on == "" else "planning",
		assignee_agent_instance_id = coordinator_agent_instance_id,
		depends_on                 = depends_on,
		created_by                 = author,
		author_agent_instance_id   = author,
	}
	if !task_store_append_event(event) do return ""
	task_notify_event(event)
	return task_id
}

task_service_coordinator_discovery_description :: proc(chain_title, chain_description, kind_name: string, scaffold_selected: bool = false) -> string {
	b := strings.builder_make()
	if scaffold_selected {
		strings.write_string(&b, "Coordinator validation task for a newly created scaffolded task chain.\n\n")
	} else {
		strings.write_string(&b, "Initial coordinator task for a newly created task chain.\n\n")
	}
	strings.write_string(&b, "## Context\n")
	strings.write_string(&b, "- Team kind: "); strings.write_string(&b, kind_name); strings.write_string(&b, "\n")
	strings.write_string(&b, "- Current chain title: "); strings.write_string(&b, chain_title); strings.write_string(&b, "\n")
	if chain_description != "" {
		strings.write_string(&b, "- Initial goal/description: "); strings.write_string(&b, chain_description); strings.write_string(&b, "\n")
	} else {
		strings.write_string(&b, "- Initial goal/description: not provided yet.\n")
	}
	strings.write_string(&b, "\n## Instructions\n")
	strings.write_string(&b, "1. Contact the user in chain chat and explain the selected team kind and roles.\n")
	strings.write_string(&b, "2. Clarify the user's goal with concise questions if title/goal are missing or vague.\n")
	strings.write_string(&b, "3. Rename/update the chain title and description once the requirement is clear.\n")
	if scaffold_selected {
		strings.write_string(&b, "4. Validate the generated scaffold tasks before any scaffold work starts; edit/create/cancel tasks so the chain matches the user's requirement.\n")
		strings.write_string(&b, "5. Mark this validation task done only when the scaffold is safe to execute. All scaffold tasks depend on this task.\n")
		strings.write_string(&b, "6. Keep free-form user contact routed through the coordinator.\n")
	} else {
		strings.write_string(&b, "4. Create downstream tasks/dependencies or apply an appropriate task-bundle template only after understanding the user's requirement.\n")
		strings.write_string(&b, "5. Keep free-form user contact routed through the coordinator.\n")
	}
	return strings.to_string(b)
}

Task_Scaffold_Build_Task :: struct {
	key: string,
	task_id: string,
	title: string,
	description: string,
	assignee_agent_instance_id: string,
	reviewer_agent_instance_ids: []string,
	depends_on: string,
}

Task_Scaffold_Role_Counter :: struct {
	role_key: string,
	next: int,
}

task_service_create_chain_scaffold :: proc(chain_id, team_id: string, cmd: Task_Chain_Create_Command, kind: ^Team_Kind_Def, validation_task_id: string = "") -> (bool, string) {
	if kind == nil do return false, "unknown team kind"
	scaffold_idx := 0
	if cmd.scaffold != "" {
		scaffold_idx = -1
		for i in 0..<len(kind.scaffolds) {
			if kind.scaffolds[i].key == cmd.scaffold {
				scaffold_idx = i
				break
			}
		}
		if scaffold_idx < 0 do return false, fmt.tprintf("unknown scaffold %s for kind %s", cmd.scaffold, kind.key)
	}
	if len(kind.scaffolds) == 0 do return true, "ok"
	scaffold := kind.scaffolds[scaffold_idx]
	members := team_db_list_members(team_service_db, team_id)
	defer delete(members)
	role_counters := [dynamic]Task_Scaffold_Role_Counter{}
	defer delete(role_counters)
	task_id_base := router_now_unix_ms()
	built := [dynamic]Task_Scaffold_Build_Task{}
	defer delete(built)
	for i in 0..<len(scaffold.tasks) {
		def := scaffold.tasks[i]
		assignee, ok := task_service_scaffold_pick_assignee(team_id, kind.key, cmd, members, &role_counters, def.role_key)
		if !ok do return false, fmt.tprintf("missing assignee for scaffold role %s", def.role_key)
		reviewers := task_service_scaffold_reviewers(team_id, kind.key, cmd, members, def.reviewer_role)
		if def.reviewer_role != "" && len(reviewers) == 0 do return false, fmt.tprintf("missing reviewer for scaffold role %s", def.reviewer_role)
		append(&built, Task_Scaffold_Build_Task{
			key = strings.clone(def.key),
			task_id = task_service_next_scaffold_task_id(task_id_base, built[:]),
			title = task_service_scaffold_interpolate(def.title_template, cmd.title, cmd.project_id, kind.display_name),
			description = task_service_scaffold_description(def.description_key, def.key, cmd.title, kind.display_name),
			assignee_agent_instance_id = assignee,
			reviewer_agent_instance_ids = reviewers,
		})
	}
	for i in 0..<len(scaffold.tasks) {
		deps := strings.builder_make()
		first := true
		if validation_task_id != "" {
			strings.write_string(&deps, validation_task_id)
			first = false
		}
		for dep_key in scaffold.tasks[i].depends_on {
			dep_id := ""
			for j in 0..<len(built) {
				if built[j].key == dep_key {
					dep_id = built[j].task_id
					break
				}
			}
			if dep_id == "" do return false, fmt.tprintf("unknown scaffold dependency %s", dep_key)
			if !first do strings.write_string(&deps, ",")
			first = false
			strings.write_string(&deps, dep_id)
		}
		built[i].depends_on = strings.clone(strings.to_string(deps))
	}
	if cmd.wants_vcs && task_service_project_supports_vcs(cmd.project_id) {
		base_ref := task_service_project_base_ref(cmd.project_id)
		reviewer := task_service_pick_non_user_reviewer(team_id, cmd.project_id, cmd.chain_id, cmd.coordinator_agent_instance_id, members, []string{"reviewer"})
		if reviewer == "" do reviewer = task_service_pick_non_user_reviewer(team_id, cmd.project_id, cmd.chain_id, cmd.coordinator_agent_instance_id, members, []string{})
		if reviewer == "" do return false, "missing non-user reviewer for VCS finalize scaffold task"
		append(&built, Task_Scaffold_Build_Task{
			key = "vcs_finalize",
			task_id = task_service_next_scaffold_task_id(task_id_base, built[:]),
			title = fmt.tprintf("Merge and push finalized changes to %s", base_ref),
			description = task_service_scaffold_vcs_finalize_description(cmd.title, cmd.project_id, base_ref, team_id, chain_id),
			assignee_agent_instance_id = cmd.coordinator_agent_instance_id,
			reviewer_agent_instance_ids = []string{reviewer},
			depends_on = task_service_scaffold_terminal_task_depends_on(built[:]),
		})
	}
	for i in 0..<len(built) {
		reviewer := ""
		if len(built[i].reviewer_agent_instance_ids) > 0 do reviewer = built[i].reviewer_agent_instance_ids[0]
		event := Task_Event{
			kind = .Task_Created,
			task_id = built[i].task_id,
			chain_id = chain_id,
			title = built[i].title,
			description = built[i].description,
			priority = "normal",
			status = "planning",
			assignee_agent_instance_id = built[i].assignee_agent_instance_id,
			reviewer_agent_instance_id = reviewer,
			depends_on = built[i].depends_on,
			created_by = cmd.author_agent_instance_id,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(event) do return false, "append scaffold task create failed"
		task_notify_event(event)
		for j in 1..<len(built[i].reviewer_agent_instance_ids) {
			p_event := Task_Event{
				kind = .Task_Participant_Added,
				task_id = built[i].task_id,
				chain_id = chain_id,
				agent_instance_id = built[i].reviewer_agent_instance_ids[j],
				role = "lgtm_required",
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if !task_store_append_event(p_event) do return false, "append scaffold reviewer failed"
			task_notify_event(p_event)
		}
	}
	return true, "ok"
}

task_service_scaffold_terminal_task_depends_on :: proc(tasks: []Task_Scaffold_Build_Task) -> string {
	deps := strings.builder_make()
	first := true
	for i in 0..<len(tasks) {
		task_id := tasks[i].task_id
		if task_service_scaffold_task_has_dependents(task_id, tasks) do continue
		if !first do strings.write_string(&deps, ",")
		first = false
		strings.write_string(&deps, task_id)
	}
	return strings.to_string(deps)
}

task_service_scaffold_task_has_dependents :: proc(task_id: string, tasks: []Task_Scaffold_Build_Task) -> bool {
	for i in 0..<len(tasks) {
		for dep in strings.split(tasks[i].depends_on, ",") {
			if strings.trim_space(dep) == task_id do return true
		}
	}
	return false
}

task_service_project_supports_vcs :: proc(project_id: string) -> bool {
	if project_id == "" do return false
	idx := project_index(project_id)
	if idx < 0 do return false
	project := project_records[idx]
	vcs_kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	return repo != "" && vcs_kind != "none"
}

task_service_project_base_ref :: proc(project_id: string, default_base_ref: string = "main") -> string {
	if project_id == "" do return strings.clone(default_base_ref)
	if idx := project_index(project_id); idx >= 0 {
		project := project_records[idx]
		base_ref := project_anchor_value(project, "base_ref", "")
		if base_ref != "" do return base_ref
	}
	return strings.clone(default_base_ref)
}

task_service_pick_non_user_reviewer :: proc(team_id, project_id, chain_id, assignee: string, members: []Team_Member_Record, preferred_roles: []string) -> string {
	for role_key in preferred_roles {
		for member in members {
			if member.role_key != role_key do continue
			if member.is_user_proxy do continue
			agent_id := task_service_member_agent_id(team_id, project_id, chain_id, member)
			if agent_id == "" || agent_id == assignee || task_runtime_agent_target(agent_id) == "" do continue
			return agent_id
		}
	}
	for member in members {
		if member.is_user_proxy do continue
		agent_id := task_service_member_agent_id(team_id, project_id, chain_id, member)
		if agent_id == "" || agent_id == assignee || task_runtime_agent_target(agent_id) == "" do continue
		return agent_id
	}
	return ""
}

task_service_member_agent_id :: proc(team_id, project_id, chain_id: string, member: Team_Member_Record) -> string {
	if member.agent_instance_id != "" do return member.agent_instance_id
	return team_service_member_agent_instance_id(project_id, chain_id, team_id, member.role_key, member.role_index)
}

task_service_scaffold_vcs_finalize_description :: proc(chain_title, project_id, base_ref, team_id, chain_id: string) -> string {
	workspace := task_service_scaffold_vcs_workspace_path(project_id, chain_id, team_id, chain_title)
	b := strings.builder_make()
	strings.write_string(&b, "Finalize this VCS chain by merging approved work into the base branch and pushing it.\n\n")
	strings.write_string(&b, "## Required action\n")
	strings.write_string(&b, "1. Confirm all implementation and validation/review tasks are completed and approved.\n")
	strings.write_string(&b, "2. Merge the approved work into the configured base ref (`")
	strings.write_string(&b, base_ref)
	strings.write_string(&b, "`) for this project.\n")
	strings.write_string(&b, "3. Push the merged result to origin for `")
	strings.write_string(&b, base_ref)
	strings.write_string(&b, "` using a command such as:\n\n")
	strings.write_string(&b, "```bash\n")
	strings.write_string(&b, "git -C ")
	strings.write_string(&b, shell_quote(workspace))
	strings.write_string(&b, " fetch origin\n")
	strings.write_string(&b, "git -C ")
	strings.write_string(&b, shell_quote(workspace))
	strings.write_string(&b, " merge --ff-only origin/")
	strings.write_string(&b, shell_quote(base_ref))
	strings.write_string(&b, "\n")
	strings.write_string(&b, "git -C ")
	strings.write_string(&b, shell_quote(workspace))
	strings.write_string(&b, " status --short --branch\n")
	strings.write_string(&b, "git -C ")
	strings.write_string(&b, shell_quote(workspace))
	strings.write_string(&b, " push origin HEAD:")
	strings.write_string(&b, shell_quote(base_ref))
	strings.write_string(&b, "\n```")
	strings.write_string(&b, "\n\n")
	strings.write_string(&b, "## Workspace cleanup\n")
	strings.write_string(&b, "After successful merge/push, clean up the temporary worktree path used for this chain.\n")
	strings.write_string(&b, "Record cleanup command(s) and any errors in a task comment before marking this task done.\n")
	strings.write_string(&b, "If cleanup fails, include the failure details and add a follow-up cleanup task; do not mark this as fully complete without explaining cleanup blockers.\n")
	return strings.to_string(b)
}

task_service_scaffold_vcs_workspace_path :: proc(project_id, chain_id, team_id, chain_title: string) -> string {
	worktree_root := fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id)
	if idx := project_index(project_id); idx >= 0 {
		worktree_root = project_anchor_value(project_records[idx], "worktree_root", worktree_root)
	}
	slug := task_chain_slug(chain_title, chain_id)
	return fmt.tprintf("%s/team/%s/%s", strings.trim_right(worktree_root, "/"), team_id, slug)
}

task_service_next_scaffold_task_id :: proc(base: i64, built: []Task_Scaffold_Build_Task) -> string {
	for i in 0..<1000 {
		candidate := fmt.tprintf("task-%x", base + i64(i))
		duplicate := false
		for j in 0..<len(built) {
			if built[j].task_id == candidate {
				duplicate = true
				break
			}
		}
		if duplicate do continue
		if !store_task_exists(candidate) do return candidate
	}
	return task_generate_id()
}

task_service_scaffold_pick_assignee :: proc(team_id, kind_key: string, cmd: Task_Chain_Create_Command, members: []Team_Member_Record, counters: ^[dynamic]Task_Scaffold_Role_Counter, role_key: string) -> (string, bool) {
	matches := [dynamic]Team_Member_Record{}
	defer delete(matches)
	for member in members {
		if member.role_key == role_key do append(&matches, member)
	}
	if len(matches) == 0 do return "", false
	counter_idx := -1
	for i in 0..<len(counters^) {
		if counters^[i].role_key == role_key {
			counter_idx = i
			break
		}
	}
	if counter_idx < 0 {
		append(counters, Task_Scaffold_Role_Counter{role_key = strings.clone(role_key)})
		counter_idx = len(counters^) - 1
	}
	pick := counters^[counter_idx].next % len(matches)
	counters^[counter_idx].next += 1
	return task_service_scaffold_member_agent_instance_id(team_id, kind_key, cmd, matches[pick]), true
}

task_service_scaffold_reviewers :: proc(team_id, kind_key: string, cmd: Task_Chain_Create_Command, members: []Team_Member_Record, role_key: string) -> []string {
	out := [dynamic]string{}
	for member in members {
		if member.role_key != role_key do continue
		agent_instance_id := task_service_scaffold_member_agent_instance_id(team_id, kind_key, cmd, member)
		duplicate := false
		for existing in out {
			if existing == agent_instance_id {
				duplicate = true
				break
			}
		}
		if !duplicate do append(&out, agent_instance_id)
	}
	return out[:]
}

task_service_scaffold_member_agent_instance_id :: proc(team_id, kind_key: string, cmd: Task_Chain_Create_Command, member: Team_Member_Record) -> string {
	if member.is_user_proxy do return "user_proxy"
	if member.agent_instance_id != "" do return member.agent_instance_id
	return team_service_member_agent_instance_id(cmd.project_id, cmd.chain_id, team_id, member.role_key, member.role_index)
}

task_service_scaffold_interpolate :: proc(template, chain_title, project_name, team_kind: string) -> string {
	out, _ := strings.replace_all(template, "{chain_title}", chain_title)
	out, _ = strings.replace_all(out, "{project_name}", project_name)
	out, _ = strings.replace_all(out, "{team_kind}", team_kind)
	return out
}

task_service_scaffold_description :: proc(description_key, task_key, chain_title, team_kind: string) -> string {
	return fmt.tprintf("Auto-generated scaffold task.\n\n- scaffold: `%s`\n- task: `%s`\n- chain: `%s`\n- team kind: `%s`", description_key, task_key, chain_title, team_kind)
}

task_service_cleanup_workspace :: proc(chain_id: string) {
	if rec, ok := vcs_db_workspace_for_chain(chain_id); ok {
		backend := vcs.vcs_backend_for(vcs_handle_from_record(rec).kind)
		_, _ = backend.workspace_remove(vcs_handle_from_record(rec), true)
		_ = vcs_db_delete_workspace(chain_id)
	}
}

task_service_error_json :: proc(message: string) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message); strings.write_string(&b, `"}`)
	return strings.to_string(b)
}

task_service_maybe_provision_workspace :: proc(project_id, chain_id, team_id, title: string) -> (Vcs_Workspace_Record, bool, string) {
	project_idx := project_index(project_id)
	if project_idx < 0 do return Vcs_Workspace_Record{}, false, "no vcs"
	project := project_records[project_idx]
	kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	if kind == "none" || repo == "" do return Vcs_Workspace_Record{}, false, "no vcs"
	backend_kind := vcs.Vcs_Kind.Git
	if kind == "jj" do backend_kind = .Jj
	if kind == "auto" {
		jj_detected := vcs.vcs_backend_for(.Jj).detect(repo)
		if jj_detected.ok do backend_kind = .Jj
		else do backend_kind = .Git
	}
	backend := vcs.vcs_backend_for(backend_kind)
	detected := backend.detect(repo)
	if !detected.ok do return Vcs_Workspace_Record{}, false, detected.message
	base_ref := project_anchor_value(project, "base_ref", detected.base_ref)
	if base_ref == "" do base_ref = detected.base_ref
	root := project_anchor_value(project, "worktree_root", fmt.tprintf("/tmp/heimdall-worktrees/%s", project_id))
	name := fmt.tprintf("team/%s/%s", team_id, task_chain_slug(title, chain_id))
	handle, ok, msg := backend.workspace_add(detected.repo_root, name, base_ref, root)
	if !ok do return Vcs_Workspace_Record{}, false, msg
	now := router_now_unix_ms()
	rec := Vcs_Workspace_Record{workspace_id=fmt.tprintf("ws_%s", chain_id), chain_id=chain_id, project_id=project_id, vcs_kind="git", path=handle.path, branch_or_change=handle.branch_or_change, base_ref=handle.base_ref, status="clean", created_unix_ms=now, updated_unix_ms=now}
	if backend_kind == .Jj do rec.vcs_kind = "jj"
	if !vcs_db_insert_workspace(rec) {
		_, _ = backend.workspace_remove(handle, true)
		return Vcs_Workspace_Record{}, false, "persist workspace failed"
	}
	return rec, true, "ok"
}

project_anchor_value :: proc(project: Project_Record, anchor_type, default_value: string) -> string {
	for i in 0..<project.anchor_count { if project.anchors[i].type == anchor_type do return project.anchors[i].value }
	return default_value
}

task_chain_project_git_repo :: proc(chain_id: string) -> (string, bool, string) {
	chain, found := store_get_chain(chain_id)
	if !found do return "", false, "chain not found"
	if _, has_workspace := vcs_db_workspace_for_chain(chain_id); has_workspace do return "", false, "chain has dedicated workspace"
	if chain.project_id == "" do return "", false, "chain has no project"
	project_idx := project_index(chain.project_id)
	if project_idx < 0 do return "", false, "project not found"
	project := project_records[project_idx]
	kind := project_anchor_value(project, "vcs_kind", "auto")
	repo := project_anchor_value(project, "directory", "")
	if repo == "" do repo = project_anchor_value(project, "git_repo", "")
	if repo == "" || kind == "none" || kind == "jj" do return "", false, "project does not support git repo diff"
	detected := vcs.vcs_backend_for(.Git).detect(repo)
	if !detected.ok do return "", false, detected.message
	return detected.repo_root, true, "git repo diff supported"
}

task_chain_repo_diff_supported :: proc(chain_id: string) -> bool {
	_, ok, _ := task_chain_project_git_repo(chain_id)
	return ok
}

task_chain_maybe_record_diff_base_sha :: proc(chain_id, reason: string) -> bool {
	_ = reason
	chain, found := store_get_chain(chain_id)
	if !found do return false
	if strings.trim_space(chain.diff_base_sha) != "" do return true
	repo, repo_ok, _ := task_chain_project_git_repo(chain_id)
	if !repo_ok do return false
	sha, sha_ok, _ := vcs.vcs_backend_for(.Git).repo_head_sha(repo)
	if !sha_ok || sha == "" do return false
	chain.diff_base_sha = strings.clone(sha)
	_ = store_upsert_chain(chain)
	if task_db_ready do return task_db_save_chain(chain)
	return true
}

task_chain_slug :: proc(title, chain_id: string) -> string {
	b := strings.builder_make()
	for r in strings.to_lower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') do strings.write_rune(&b, r)
		else if r == '-' || r == '_' || r == ' ' do strings.write_byte(&b, '-')
		if len(strings.to_string(b)) >= 40 do break
	}
	out := strings.trim(strings.to_string(b), "-")
	if out == "" {
		if len(chain_id) > 8 do return chain_id[len(chain_id)-8:]
		return chain_id
	}
	return strings.clone(out)
}

task_service_activate_chain :: proc(cmd: Task_Chain_Activate_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"activate requires chain_id"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	if chain.status != "planning" {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"only planning chains can be activated"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = cmd.chain_id,
		status                   = "in_progress",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain activate failed"}`}
	}
	task_notify_event(event)
	_ = task_autoscaler_ensure_chain_coordinator(cmd.chain_id, "chain_activate", "high")
	task_recompute_promotions(cmd.author_agent_instance_id)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_comment :: proc(task_id, chain_id, body, author: string) -> Task_Service_Result {
	return task_service_comment_command(Task_Comment_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author})
}

task_service_comment_command :: proc(cmd: Task_Comment_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.body == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task comment requires task_id and body"}`}
	}
	comment_id := fmt.tprintf("cmt_%d", router_now_unix_ms())
	event := Task_Event{
		kind                     = .Task_Comment,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = comment_id,
		body                     = cmd.body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task comment failed"}`}
	}
	task_notify_event(event)

	// Ordinary comments are informational by default. Do not regress an
	// already-approved task merely because the comment is unresolved; explicit
	// changes-requested review state is represented by an NGTM vote, which moves
	// review_ready work back to in_progress in task_service_review_vote.

	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"comment_id":"`); json_write_string(&b, comment_id); strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_comment_resolve :: proc(cmd: Task_Comment_Resolve_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"comment resolve requires task_id and comment_id"}`}
	}
	if !store_comment_exists(cmd.task_id, cmd.comment_id) {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"comment not found"}`}
	}
	event := Task_Event{
		kind                     = .Task_Comment_Resolved,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		comment_id               = cmd.comment_id,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append comment resolve failed"}`}
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_assign :: proc(task_id, chain_id, agent_instance_id, author: string) -> Task_Service_Result {
	return task_service_assign_command(Task_Assign_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, author_agent_instance_id = author})
}

task_service_assign_command :: proc(cmd: Task_Assign_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task assignment requires task_id and agent_instance_id"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if task_actor_has_role(state, cmd.agent_instance_id, "lgtm_required") || task_actor_has_role(state, cmd.agent_instance_id, "lgtm_optional") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is already a reviewer"}`}
	}
	if task_chain_default_reviewer_agent_instance_id(state.chain_id) == cmd.agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be the default reviewer"}`}
	}
	if task_agent_instance_has_chain_role(state.chain_id, cmd.agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if !task_agent_instance_allowed_for_chain(state.chain_id, cmd.agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is not an eligible agent (unknown or archived)"}`}
	}
	old_assignee := state.assignee_agent_instance_id
	queued_behind_task_id := ""
	if task_status_active_for_assignee(state) {
		if active := task_active_slot_blocker(cmd.agent_instance_id, state.task_id); active != "" {
			if active == "pending_reviews_exist" {
				return task_gating_error("assignee_active_task", "assignee already has pending reviews", active)
			}
			queued_behind_task_id = active
		}
	}
	event := Task_Event{
		kind                     = .Task_Assigned,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = cmd.agent_instance_id,
		role                     = "assignee",
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task assignment failed"}`}
	}
	task_notify_event(event)
	if old_assignee != "" && old_assignee != cmd.agent_instance_id {
		_ = task_notify_task_role_change_recipients(event, task_status_to_string(state.status), "assignee", old_assignee, "")
	}
	if task_status_active_for_assignee(state) {
		if state.assignee_agent_instance_id != "" && state.assignee_agent_instance_id != cmd.agent_instance_id {
			_ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, cmd.task_id)
		}
		if queued_behind_task_id != "" {
			block_event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = cmd.task_id,
				chain_id                 = state.chain_id,
				status                   = "blocked",
				body                     = strings.concatenate({"system_block:assignee_active_task:", queued_behind_task_id}),
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if task_store_append_event(block_event) {
				task_notify_event(block_event)
			}
		} else if state.status == .In_Progress {
			_ = agent_store_set_current_task(cmd.agent_instance_id, cmd.task_id)
			_ = task_runtime_reconcile_task(cmd.task_id, "assignment", "high")
		}
	}
	if queued_behind_task_id != "" {
		b := strings.builder_make()
		strings.write_string(&b, `{"ok":true,"queued_behind_task_id":"`); json_write_string(&b, queued_behind_task_id); strings.write_string(&b, `"}`)
		return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_add_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant requires task_id, agent_instance_id, and role"}`}
	}
	agent_instance_id := cmd.agent_instance_id
	reviewer_normalized := false
	if cmd.role == "lgtm_required" || cmd.role == "lgtm_optional" {
		agent_instance_id, reviewer_normalized = task_normalize_user_reviewer(cmd.agent_instance_id)
	}
	switch cmd.role {
	case "assignee", "lgtm_required", "lgtm_optional", "coordinator", "subscriber":
	case:
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"role must be assignee, lgtm_required, lgtm_optional, coordinator, or subscriber"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if (cmd.role == "lgtm_required" || cmd.role == "lgtm_optional") && state.assignee_agent_instance_id == agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"assignee cannot be a reviewer"}`}
	}
	if cmd.role == "assignee" && (task_actor_has_role(state, agent_instance_id, "lgtm_required") || task_actor_has_role(state, agent_instance_id, "lgtm_optional")) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer cannot be the assignee"}`}
	}
	if cmd.role == "assignee" && task_chain_default_reviewer_agent_instance_id(state.chain_id) == agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee"}`}
	}
	if cmd.role == "assignee" && task_agent_instance_has_chain_role(state.chain_id, agent_instance_id, "reviewer") {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"reviewer role agent cannot be the assignee"}`}
	}
	if !task_agent_instance_allowed_for_chain(state.chain_id, agent_instance_id) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"agent is not an eligible agent (unknown or archived)"}`}
	}
	event := Task_Event{
		kind                     = .Task_Participant_Added,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		agent_instance_id        = agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant failed"}`}
	}
	task_notify_event(event)
	if (cmd.role == "lgtm_required" || cmd.role == "lgtm_optional") && state.status == .Review_Ready {
		task_notify_review_ready_agent(state, agent_instance_id)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true`)
	task_write_user_proxy_warning_if_needed(&b, reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_agent_instance_has_chain_role :: proc(chain_id, agent_instance_id, role_key: string) -> bool {
	if chain_id == "" || agent_instance_id == "" || role_key == "" do return false
	chain, chain_found := store_get_chain(chain_id)
	if !chain_found do return false
	if chain.team_id == "" do return false
	members := team_db_list_members(team_service_db, chain.team_id)
	for member in members {
		if member.role_key != role_key do continue
		if member.agent_instance_id != "" && member.agent_instance_id == agent_instance_id do return true
		if member.route_to != "" && member.route_to == agent_instance_id do return true
	}
	return false
}

// teams-v2 Phase 3: assignment is no longer gated by chain team membership.
// Any existing, non-archived agent instance (or an allowed user-proxy reviewer)
// may be assigned/reviewed on any chain; involvement is recorded via an
// association record instead of requiring pre-existing membership.
//
// This returns whether the agent is *eligible* at all. The surrounding conflict
// checks (assignee != reviewer, default-reviewer separation, active-slot gating)
// are enforced separately by the callers and are unchanged.
task_record_agent_chain_association :: proc(chain_id, task_id, agent_instance_id, association_kind: string) -> bool {
	if chain_id == "" || task_id == "" || agent_instance_id == "" || association_kind == "" do return true
	project_id := ""
	if chain, found := store_get_chain(chain_id); found {
		project_id = chain.project_id
	}
	now := router_now_unix_ms()
	assoc := Agent_Chain_Association{
		association_id = fmt.tprintf("assoc_%s_%s_%s_%s", chain_id, task_id, agent_instance_id, association_kind),
		agent_instance_id = agent_instance_id,
		project_id = project_id,
		chain_id = chain_id,
		task_id = task_id,
		association_kind = association_kind,
		created_unix_ms = now,
		last_active_unix_ms = now,
	}
	return task_db_save_agent_chain_association(assoc)
}

task_agent_instance_allowed_for_chain :: proc(chain_id, agent_instance_id: string) -> bool {
	if agent_instance_id == "" do return false
	chain, chain_found := store_get_chain(chain_id)
	// Coordinator / default reviewer are always allowed.
	if chain_found && (agent_instance_id == chain.coordinator_agent_instance_id || agent_instance_id == chain.default_reviewer_agent_instance_id) do return true
	// Allowed user-proxy / operator reviewer identities remain permitted.
	if agent_instance_id == "user_proxy" || agent_instance_id == HUMAN_RECIPIENT_ID do return true
	// Any known, non-archived agent identity is eligible (flexible assignment).
	if idx := agent_record_index_by_instance(agent_instance_id); idx >= 0 {
		return agent_instance_records[idx].archived_at_unix_ms == 0
	}
	// Fall back to legacy team membership so pre-teams-v2 route_to aliases still
	// resolve even when no standalone agent record exists.
	if chain_found && chain.team_id != "" {
		members := team_db_list_members(team_service_db, chain.team_id)
		defer delete(members)
		for member in members {
			if task_reviewer_matches_user_proxy_member(agent_instance_id, member) do return true
			if member.agent_instance_id != "" && member.agent_instance_id == agent_instance_id do return true
			if member.route_to != "" && member.route_to == agent_instance_id do return true
		}
	}
	return false
}

task_service_remove_participant :: proc(task_id, chain_id, agent_instance_id, role, author: string) -> Task_Service_Result {
	return task_service_remove_participant_command(Task_Participant_Command{task_id = task_id, chain_id = chain_id, agent_instance_id = agent_instance_id, role = role, author_agent_instance_id = author})
}

task_service_remove_participant_command :: proc(cmd: Task_Participant_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.agent_instance_id == "" || cmd.role == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"participant removal requires task_id, agent_instance_id, and role"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	agent_instance_id := cmd.agent_instance_id
	if cmd.role == "lgtm_required" || cmd.role == "lgtm_optional" {
		agent_instance_id, _ = task_normalize_user_reviewer(cmd.agent_instance_id)
	}
	event := Task_Event{
		kind                     = .Task_Participant_Removed,
		task_id                  = cmd.task_id,
		chain_id                 = state.chain_id,
		agent_instance_id        = agent_instance_id,
		role                     = cmd.role,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append participant removal failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_update_task :: proc(cmd: Task_Update_Command) -> Task_Service_Result {
	if cmd.task_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task update requires task_id"}`}
	}
	current, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	title := cmd.title
	if title == "" do title = current.title
	description := current.description
	if cmd.description_present do description = cmd.description
	audit_body := fmt.tprintf("metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, current.description, description)
	event := Task_Event{
		kind                     = .Task_Metadata_Updated,
		task_id                  = cmd.task_id,
		chain_id                 = current.chain_id,
		title                    = title,
		description              = description,
		body                     = audit_body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task update failed"}`}
	}
	task_notify_event(event)
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","description":"`); json_write_string(&b, description)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_set_status :: proc(task_id, chain_id, status, body, author: string) -> Task_Service_Result {
	return task_service_status_command(Task_Status_Command{task_id = task_id, chain_id = chain_id, status = status, body = body, author_agent_instance_id = author})
}

task_service_status_command :: proc(cmd: Task_Status_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.status == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"task status change requires task_id, status, and non-empty body"}`}
	}
	if !task_status_allowed(cmd.status) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	status_val, ok := task_status_from_string(cmd.status)
	if !ok {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid task status"}`}
	}
	if cmd.force {
		if status_val != .Approved {
			return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"force only supports approved status"}`}
		}
		if !task_force_advance_authorized(state, cmd.author_agent_instance_id) {
			return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"force requires chain coordinator or operator"}`}
		}
	} else {
		if status_val == .In_Progress {
			if dep_blockers := task_dependency_blocking_ids(state.depends_on); dep_blockers != "" {
				return task_gating_error("dependency", "unmet task dependencies", dep_blockers)
			}
			if !task_chain_allows_execution(state.chain_id) {
				return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task chain is not in_progress","error":"chain_not_active"}`}
			}
			if state.assignee_agent_instance_id == "" {
				return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task has no assignee","error":"unassigned"}`}
			}
			if active := task_active_slot_blocker(state.assignee_agent_instance_id, state.task_id); active != "" {
				return task_gating_error("assignee_active_task", "assignee already has an active task", active)
			}
		}
		if status_val == .Review_Ready || status_val == .Approved {
			unresolved := task_unresolved_comments(cmd.task_id)
			defer delete(unresolved)
			if len(unresolved) > 0 {
				return Task_Service_Result{
					ok = false,
					status_code = 400,
					message = fmt.tprintf(`{{"ok":false,"message":"task has %d unresolved comments"}}`, len(unresolved)),
				}
			}
		}
		if !task_status_change_authorized(state, status_val, cmd.author_agent_instance_id) {
			return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not authorized for task status transition"}`}
		}
	}
	event_body := cmd.body
	if cmd.force {
		event_body = fmt.tprintf("FORCE_REVIEW_BYPASS task_id=%s chain_id=%s coordinator_id=%s prior_status=%s new_status=%s reason=%s timestamp_unix_ms=%d", cmd.task_id, state.chain_id, cmd.author_agent_instance_id, task_status_to_string(state.status), cmd.status, cmd.body, router_now_unix_ms())
	}
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = cmd.task_id,
		chain_id                 = state.chain_id,
		status                   = cmd.status,
		body                     = event_body,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task status failed"}`}
	}
	task_notify_event(event)
	if cmd.status == "in_progress" && state.assignee_agent_instance_id != "" {
		_ = task_chain_maybe_record_diff_base_sha(state.chain_id, "task_started")
		_ = agent_store_set_current_task(state.assignee_agent_instance_id, cmd.task_id)
	}
	if cmd.status == "in_progress" || cmd.status == "queued" || cmd.status == "review_ready" {
		_ = task_runtime_reconcile_task(cmd.task_id, "status_change", "high")
	}
	if state.status == .Review_Ready && cmd.status != "review_ready" {
		task_cancel_open_user_proxy_approvals(cmd.task_id, state.chain_id)
	}
	if cmd.status == "review_ready" || cmd.status == "blocked" || cmd.status == "queued" || cmd.status == "ready" || cmd.status == "approved" || cmd.status == "cancelled" {
		if state.assignee_agent_instance_id != "" do _ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, cmd.task_id)
		_ = agent_store_clear_current_task_if_matches(cmd.author_agent_instance_id, cmd.task_id)
	}

	manual_defer := (cmd.status == "queued" || cmd.status == "ready") && state.status == .In_Progress && task_actor_has_role(state, cmd.author_agent_instance_id, "assignee")
	defer_assignee := state.assignee_agent_instance_id

	task_recompute_promotions(cmd.author_agent_instance_id)
	if cmd.status == "queued" || cmd.status == "ready" {
		if manual_defer {
			if next_task := task_best_ready_task_for_assignee_excluding(defer_assignee, cmd.task_id); next_task != "" {
				task_service_auto_claim(next_task)
			}
		} else {
			task_service_auto_claim(cmd.task_id)
		}
	}
	task_service_try_auto_complete_chain(state.chain_id)
	if cmd.status == "review_ready" {
		task_notify_all_lgtm_required(cmd.task_id, state.chain_id)
		task_notify_user_proxy_review_requests(cmd.task_id, state.chain_id)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, cmd.status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_review_vote :: proc(cmd: Task_Review_Vote_Command) -> Task_Service_Result {
	if cmd.task_id == "" || cmd.comment == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"review vote requires task_id and comment"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if state.status != .Review_Ready {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"can only vote on review_ready tasks"}`}
	}
	user_review_required := cmd.author_is_user && task_requires_user_review(state)
	vote_author := cmd.author_agent_instance_id
	if user_review_required {
		vote_author = task_reviewer_agent_instance_id(state)
	}
	if proxy_reviewer, proxy_ok := task_user_proxy_reviewer_for(state, cmd.author_agent_instance_id); proxy_ok {
		vote_author = proxy_reviewer
	}
	is_required  := task_actor_has_role(state, vote_author, "lgtm_required")
	if !is_required && (user_review_required || vote_author == task_reviewer_agent_instance_id(state)) {
		is_required = true
	}
	is_optional  := task_actor_has_role(state, vote_author, "lgtm_optional")
	can_override := task_actor_can_override(state, cmd.author_agent_instance_id)
	if !is_required && !is_optional && !can_override {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"not a reviewer for this task"}`}
	}
	role := "lgtm_optional"
	if is_required do role = "lgtm_required"
	vote_approved_str := "true" if cmd.approved else "false"
	event := Task_Event{
		kind                     = .Task_Review_Vote,
		task_id                  = cmd.task_id,
		chain_id                 = cmd.chain_id,
		vote_approved            = vote_approved_str,
		role                     = role,
		body                     = cmd.comment,
		author_agent_instance_id = vote_author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append review vote failed"}`}
	}
	task_notify_event(event)
	_ = agent_store_clear_current_task(cmd.author_agent_instance_id)
	task_cancel_open_user_proxy_approvals(cmd.task_id, cmd.chain_id)
	if !cmd.approved {
		back_event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = cmd.task_id,
			chain_id                 = cmd.chain_id,
			status                   = "in_progress",
			body                     = fmt.tprintf("ngtm by %s: %s", vote_author, cmd.comment),
			author_agent_instance_id = "system-review-vote",
		}
		if task_store_append_event(back_event) {
			if state.assignee_agent_instance_id != "" do _ = agent_store_set_current_task(state.assignee_agent_instance_id, cmd.task_id)
			task_notify_event(back_event)
			_ = task_runtime_reconcile_task(cmd.task_id, "status_change", "high")
		}
	} else if task_all_required_lgtms_approved(cmd.task_id) {
		task_service_auto_approve(cmd.task_id, cmd.chain_id)
	}
	task_recompute_promotions(vote_author)
	task_notify_reviewer_rotation(vote_author)
	result_status := "review_ready"
	if updated_state, updated_found := store_get_task_in_chain(cmd.task_id, cmd.chain_id); updated_found {
		result_status = task_status_to_string(updated_state.status)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"task_id":"`); json_write_string(&b, cmd.task_id)
	strings.write_string(&b, `","status":"`); json_write_string(&b, result_status)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_user_proxy_reviewer_for :: proc(state: Task_State, user_id: string) -> (string, bool) {
	if user_id == "" do return "", false
	chain, chain_found := store_get_chain(state.chain_id)
	if !chain_found do return "", false
	team_id := chain.team_id
	if team_id == "" {
		team, ok := team_db_get_team_by_chain_id(team_service_db, state.chain_id)
		if !ok do return "", false
		team_id = team.team_id
	}
	members := team_db_list_members(team_service_db, team_id)
	parts := store_participants_of(state.task_id)
	defer delete(parts)
	for member in members {
		if !member.is_user_proxy do continue
		if member.route_to != user_id do continue
		default_rev := task_reviewer_agent_instance_id(state)
		if default_rev != "" && task_reviewer_matches_user_proxy_member(default_rev, member) {
			return default_rev, true
		}
		for p in parts {
			if p.role != "lgtm_required" && p.role != "lgtm_optional" do continue
			if p.agent_instance_id == member.role_key || p.agent_instance_id == member.route_to || (member.agent_record_id != "" && p.agent_instance_id == member.agent_record_id) {
				return p.agent_instance_id, true
			}
		}
	}
	return "", false
}

task_notify_user_proxy_review_requests :: proc(task_id, chain_id: string) {
	state, found := store_get_task_in_chain(task_id, chain_id)
	if !found do return
	chain, chain_found := store_get_chain(state.chain_id)
	if !chain_found do return
	team_id := chain.team_id
	if team_id == "" {
		team, ok := team_db_get_team_by_chain_id(team_service_db, state.chain_id)
		if !ok do return
		team_id = team.team_id
	}
	if !task_requires_user_review(state) do return
	members := team_db_list_members(team_service_db, team_id)
	for member in members {
		if !member.is_user_proxy || member.route_to == "" do continue
		sender := chain.coordinator_agent_instance_id
		if sender == "" do sender = "user_proxy"
		body := task_user_proxy_review_card_json(state)
		message_id, ok := chat_store_append_message_with_chain(member.route_to, sender, "agent_to_user", body, true, state.chain_id)
		if ok {
			chat_event_fanout(member.route_to, sender, message_id, "agent_to_user", state.chain_id)
			if det := chat_approval_detect_payload(body); det.matched {
				_, _ = chat_approval_service_record(det, message_id, state.chain_id, member.route_to, sender)
			}
		}
	}
}

// Called when a task exits review_ready (approved / regressed to in_progress /
// cancelled). Any open user_proxy approvals bound to the chain that reference
// this task_id must be cancelled so the operator inbox is not stranded.
task_cancel_open_user_proxy_approvals :: proc(task_id, chain_id: string) {
	if chain_id == "" do return
	rows := chat_approval_db_list_open_for_chain(chain_id)
	for rec in rows {
		if !strings.contains(rec.options_json, task_id) do continue
		_ = chat_approval_service_terminal(rec.approval_id, "cancelled", "", "system-task-service", "task_left_review_ready", "")
	}
}

task_user_proxy_review_card_json :: proc(state: Task_State) -> string {
	b := strings.builder_make()
	strings.write_string(&b, `{"type":"smart_answer","body":"Review task `)
	json_write_string(&b, state.task_id)
	strings.write_string(&b, `: `)
	json_write_string(&b, state.title)
	strings.write_string(&b, `","suggested_replies":[`)
	strings.write_string(&b, `"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"lgtm\"}"`)
	strings.write_string(&b, `,"{\"action\":\"user_proxy_review\",\"task_id\":\"`); json_write_string(&b, state.task_id); strings.write_string(&b, `\",\"result\":\"ngtm\"}"`)
	strings.write_string(&b, `]}`)
	return strings.to_string(b)
}

task_service_user_proxy_review_reply :: proc(user_id, coordinator_agent_instance_id, reply: string) -> Task_Service_Result {
	if extract_json_string(reply, "action", "") != "user_proxy_review" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"not a user_proxy review reply"}`}
	}
	task_id := extract_json_string(reply, "task_id", "")
	result := extract_json_string(reply, "result", "")
	approved := result == "lgtm"
	rejected := result == "ngtm"
	if task_id == "" || (!approved && !rejected) {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid user_proxy review reply"}`}
	}
	state, found := store_get_task_in_chain(task_id, "")
	if !found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	if state.status != .Review_Ready do return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"task is not pending review"}`}
	chain, chain_found := store_get_chain(state.chain_id)
	if !chain_found do return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	if coordinator_agent_instance_id != "" && chain.coordinator_agent_instance_id != coordinator_agent_instance_id {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"reply coordinator mismatch"}`}
	}
	if _, ok := task_user_proxy_reviewer_for(state, user_id); !ok {
		return Task_Service_Result{ok = false, status_code = 403, message = `{"ok":false,"message":"user is not the user_proxy reviewer"}`}
	}
	comment := "operator user_proxy LGTM"
	if rejected do comment = "operator user_proxy NGTM"
	return task_service_review_vote(Task_Review_Vote_Command{task_id = state.task_id, chain_id = state.chain_id, approved = approved, comment = comment, author_agent_instance_id = user_id, author_is_user = true})
}

task_service_auto_approve :: proc(task_id, chain_id: string) {
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = chain_id,
		status                   = "approved",
		body                     = "system_auto:all_lgtm_required_approved",
		author_agent_instance_id = "system-auto-approve",
	}
	if task_store_append_event(event) {
		if state, found := store_get_task_in_chain(task_id, chain_id); found && state.assignee_agent_instance_id != "" {
			_ = agent_store_clear_current_task_if_matches(state.assignee_agent_instance_id, task_id)
		}
		task_notify_event(event)
		task_recompute_promotions("system-auto-approve")
		task_service_try_auto_complete_chain(chain_id)
	}
}

task_service_auto_claim :: proc(task_id: string) {
	state, found := store_get_task_in_chain(task_id, "")
	if !found do return
	if state.status != .Queued do return
	if !task_dependencies_satisfied(state.depends_on) do return
	if !task_ready_allows_auto_claim(state) do return
	if !task_chain_allows_execution(state.chain_id) do return
	assignee := state.assignee_agent_instance_id
	if assignee == "" do return
	if best_ready := task_best_ready_task_for_assignee(assignee); best_ready != "" && best_ready != task_id do return
	if task_active_slot_blocker(assignee, task_id) != "" do return
	event := Task_Event{
		kind                     = .Task_Status_Changed,
		task_id                  = task_id,
		chain_id                 = state.chain_id,
		status                   = "in_progress",
		body                     = "system_auto:auto_claimed",
		author_agent_instance_id = "system-auto-claim",
	}
	if task_store_append_event(event) {
		_ = task_chain_maybe_record_diff_base_sha(state.chain_id, "task_auto_claimed")
		_ = agent_store_set_current_task(assignee, task_id)
		task_notify_event(event)
		_ = task_runtime_reconcile_task(task_id, "auto_claim", "high")
	}
}

task_service_try_auto_complete_chain :: proc(chain_id: string) {
	if chain_id == "" do return
	chain, found := store_get_chain(chain_id)
	if !found do return
	if chain.status == "reviewing" || chain.status == "paused" || chain.status == "completed" || chain.status == "archived" do return
	if !task_all_chain_tasks_terminal(chain_id) do return
	event := Task_Event{
		kind                     = .Chain_Status_Changed,
		chain_id                 = chain_id,
		status                   = "reviewing",
		body                     = "system_auto:all_tasks_terminal_review_required",
		author_agent_instance_id = "system-auto-complete",
	}
	if task_store_append_event(event) {
		task_notify_event(event)
		task_service_ping_coordinator_for_chain_completion(chain_id)
	}
}

task_service_ping_coordinator_for_chain_completion :: proc(chain_id: string) {
	chain, found := store_get_chain(chain_id)
	if !found do return
	if chain.coordinator_agent_instance_id == "" do return

	message_body := fmt.tprintf(
		"All tasks in your task chain '%s' (ID: %s) have been completed!\n\n" +
		"As the designated coordinator, you must now review the results and move the task chain to 'completed' using the 'ham-ctl task-chains status --status completed --final-summary \"...\"' command.\n\n" +
		"Your final summary must strictly comply with the Task Chain Best Practices below:\n\n%s",
		chain.title,
		chain.chain_id,
		TASK_CHAIN_BEST_PRACTICES,
	)

	_, ok := chat_store_append_message_with_chain(HUMAN_RECIPIENT_ID, chain.coordinator_agent_instance_id, "user_to_agent", message_body, false, chain_id)
	if !ok {
		fmt.println("WARNING: Failed to append completion ping message to coordinator agent:", chain.coordinator_agent_instance_id)
	} else {
		fmt.println("INFO: Successfully pinged coordinator agent", chain.coordinator_agent_instance_id, "for chain completion of", chain_id)
	}
}

task_service_nudge :: proc(task_id, chain_id, body, author: string, interrupt: bool) -> Task_Service_Result {
	return task_service_nudge_command(Task_Nudge_Command{task_id = task_id, chain_id = chain_id, body = body, author_agent_instance_id = author, interrupt = interrupt})
}

task_service_nudge_command :: proc(cmd: Task_Nudge_Command) -> Task_Service_Result {
	if cmd.task_id == "" || strings.trim_space(cmd.body) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"nudge requires task_id and non-empty body"}`}
	}
	state, found := store_get_task_in_chain(cmd.task_id, cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"task not found"}`}
	}
	if task_status_terminal(state.status) {
		return Task_Service_Result{ok = false, status_code = 409, message = `{"ok":false,"message":"terminal task cannot be nudged"}`}
	}
	target := task_nudge_target_for_status(state, state.status)
	if target == "" {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"no nudge target for task status"}`}
	}
	event := Task_Event{
		kind                     = .Task_Nudged,
		task_id                  = state.task_id,
		chain_id                 = state.chain_id,
		status                   = task_status_to_string(state.status),
		body                     = cmd.body,
		agent_instance_id        = target,
		author_agent_instance_id = cmd.author_agent_instance_id,
		interrupt                = cmd.interrupt,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append task nudge failed"}`}
	}
	_ = task_runtime_reconcile_task(state.task_id, "manual_nudge", "high")
	delivery := task_notify_nudge_delivery(event)
	delivery_state := "skipped"
	if delivery.live_delivered {
		delivery_state = "delivered"
	} else if delivery.durable_queued {
		delivery_state = "queued"
	} else if delivery.failed {
		delivery_state = "failed"
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":`); strings.write_string(&b, "false" if delivery.failed else "true")
	strings.write_string(&b, `,"target_agent_instance_id":"`); json_write_string(&b, target)
	strings.write_string(&b, `","sent":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"live_delivered":`); strings.write_string(&b, "true" if delivery.live_delivered else "false")
	strings.write_string(&b, `,"durable_queued":`); strings.write_string(&b, "true" if delivery.durable_queued else "false")
	strings.write_string(&b, `,"failed":`); strings.write_string(&b, "true" if delivery.failed else "false")
	strings.write_string(&b, `,"delivery_state":"`); json_write_string(&b, delivery_state)
	strings.write_string(&b, `"}`)
	return Task_Service_Result{ok = !delivery.failed, status_code = 200 if !delivery.failed else 500, message = strings.to_string(b)}
}

task_service_update_chain :: proc(cmd: Task_Chain_Update_Command) -> Task_Service_Result {
	if cmd.chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain update requires chain_id"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	old_coordinator := chain.coordinator_agent_instance_id
	old_default_reviewer := chain.default_reviewer_agent_instance_id
	new_coordinator := cmd.coordinator_agent_instance_id
	if new_coordinator == "" do new_coordinator = old_coordinator
	new_default_reviewer, default_reviewer_normalized := task_normalize_user_reviewer(cmd.default_reviewer_agent_instance_id)
	if new_default_reviewer == "" do new_default_reviewer = old_default_reviewer
	if new_default_reviewer != "" && new_default_reviewer == new_coordinator {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot equal coordinator"}`}
	}
	if new_default_reviewer != "" {
		for state in store_tasks_in_chain(cmd.chain_id) {
			if task_status_terminal(state.status) do continue
			if state.assignee_agent_instance_id == new_default_reviewer {
				return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"default reviewer cannot be the assignee of an active task in the chain"}`}
			}
		}
	}
	event_default_reviewer := ""
	if cmd.default_reviewer_agent_instance_id != "" do event_default_reviewer = new_default_reviewer
	audit_body := fmt.tprintf("chain metadata updated by %s; old_description=%s; new_description=%s", cmd.author_agent_instance_id, chain.description, cmd.description)
	event := Task_Event{
		kind                          = .Chain_Metadata_Updated,
		chain_id                      = cmd.chain_id,
		title                         = cmd.title,
		description                   = cmd.description,
		body                          = audit_body,
		coordinator_agent_instance_id = cmd.coordinator_agent_instance_id,
		reviewer_agent_instance_id    = event_default_reviewer,
		author_agent_instance_id      = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain update failed"}`}
	}
	task_notify_event(event)
	coordinator_changed := cmd.coordinator_agent_instance_id != "" && old_coordinator != new_coordinator
	default_reviewer_changed := cmd.default_reviewer_agent_instance_id != "" && old_default_reviewer != new_default_reviewer
	if coordinator_changed {
		_ = task_notify_chain_role_change_recipients(event, chain.status, "coordinator", old_coordinator, new_coordinator)
		_ = task_runtime_reconcile_chain_coordinator(cmd.chain_id, "coordinator_changed", "high")
	}
	if default_reviewer_changed {
		_ = task_notify_chain_role_change_recipients(event, chain.status, "default_reviewer", old_default_reviewer, new_default_reviewer)
	}
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		if !task_store_append_event(summary_event) {
			return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain summary failed"}`}
		}
		task_notify_event(summary_event)
	}
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true`)
	task_write_user_proxy_warning_if_needed(&b, default_reviewer_normalized)
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_service_set_chain_status :: proc(chain_id, status, final_summary, author: string) -> Task_Service_Result {
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = status, final_summary = final_summary, author_agent_instance_id = author})
}

task_service_chain_status_command :: proc(cmd: Task_Chain_Status_Command) -> Task_Service_Result {
	if cmd.chain_id == "" || cmd.status == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain status requires chain_id and status"}`}
	}
	chain, found := store_get_chain(cmd.chain_id)
	if !found {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	stored_summary := chain.final_summary
	if cmd.status == "completed" && strings.trim_space(cmd.final_summary) == "" && stored_summary == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"final_summary required for completed status"}`}
	}
	if cmd.final_summary != "" {
		summary_event := Task_Event{
			kind                     = .Chain_Final_Summary_Set,
			chain_id                 = cmd.chain_id,
			body                     = cmd.final_summary,
			author_agent_instance_id = cmd.author_agent_instance_id,
		}
		task_store_append_event(summary_event)
		task_notify_event(summary_event)
	}
	kind := Task_Event_Kind.Chain_Status_Changed
	if cmd.status == "completed" do kind = .Chain_Completed
	status_event := Task_Event{
		kind                     = kind,
		chain_id                 = cmd.chain_id,
		status                   = cmd.status,
		body                     = cmd.final_summary,
		author_agent_instance_id = cmd.author_agent_instance_id,
	}
	if !task_store_append_event(status_event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain status failed"}`}
	}
	task_notify_event(status_event)
	if cmd.status == "in_progress" {
		_ = task_chain_maybe_record_diff_base_sha(cmd.chain_id, "chain_status_in_progress")
		_ = task_autoscaler_ensure_chain_coordinator(cmd.chain_id, "chain_status_in_progress", "high")
	}

	// Orchestrate member tasks based on the new chain status
	if cmd.status == "completed" || cmd.status == "archived" || cmd.status == "planning" || cmd.status == "paused" {
		for state in store_tasks_in_chain(cmd.chain_id) {
			if task_status_terminal(state.status) do continue

			next_status := ""
			body_text := ""
			if cmd.status == "completed" || cmd.status == "archived" {
				next_status = "cancelled"
				body_text = "system_auto:chain_completed"
			} else if cmd.status == "planning" || cmd.status == "paused" {
				if state.status == .In_Progress {
					next_status = "queued"
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				} else if state.status == .Queued {
					body_text = "system_auto:chain_moved_to_planning" if cmd.status == "planning" else "system_auto:chain_paused"
				}
			}
			if next_status == "" do continue
			next_status_val, _ := task_status_from_string(next_status)
			if state.status == next_status_val && body_text == "" do continue

			event := Task_Event{
				kind                     = .Task_Status_Changed,
				task_id                  = state.task_id,
				chain_id                 = state.chain_id,
				status                   = next_status,
				body                     = body_text,
				author_agent_instance_id = cmd.author_agent_instance_id,
			}
			if task_store_append_event(event) {
				task_notify_event(event)
			}
		}
		task_recompute_promotions(cmd.author_agent_instance_id)
	} else if cmd.status == "in_progress" || cmd.status == "queued" || cmd.status == "ready" {
		task_recompute_promotions(cmd.author_agent_instance_id)
	}

	// Task 16: on completion, archive team immediately for non-VCS chains or
	// surface a merge decision for VCS chains (docs/teams-v1/03-lifecycle.md §3.4/§3.5).
	if cmd.status == "completed" {
		merge_lifecycle_on_chain_completed(cmd.chain_id, cmd.author_agent_instance_id)
	}
	if cmd.status == "completed" || cmd.status == "archived" || cmd.status == "cancelled" || cmd.status == "abandoned" {
		_ = task_autoscaler_stop_chain_agents(cmd.chain_id, strings.concatenate({"chain_status_", cmd.status}))
	}

	archive_ok := true
	if cmd.status == "completed" || cmd.status == "archived" {
		archive_ok = task_archive_chain_to_hub(cmd.chain_id)
	}
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true,"archive_ok":true}` if archive_ok else `{"ok":true,"archive_ok":false,"archive_pending":true}`}
}

task_service_complete_chain :: proc(chain_id, final_summary, author: string) -> Task_Service_Result {
	if chain_id == "" || strings.trim_space(final_summary) == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain complete requires chain_id and non-empty summary"}`}
	}
	return task_service_chain_status_command(Task_Chain_Status_Command{chain_id = chain_id, status = "completed", final_summary = final_summary, author_agent_instance_id = author})
}

task_service_retry_pending_archives :: proc() -> Task_Service_Result {
	retried := task_store_retry_pending_archives()
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":true,"retried":`)
	strings.write_string(&b, fmt.tprintf("%d", retried))
	strings.write_string(&b, `}`)
	return Task_Service_Result{ok = true, status_code = 200, message = strings.to_string(b)}
}

task_gating_error :: proc(error_kind, message, blocking_task_ids: string) -> Task_Service_Result {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message)
	strings.write_string(&b, `","error":"`);             json_write_string(&b, error_kind)
	strings.write_string(&b, `","blocking_task_ids":[`)
	ids   := strings.split(blocking_task_ids, ",")
	first := true
	for id_raw in ids {
		id := strings.trim_space(id_raw)
		if id == "" do continue
		if !first do strings.write_string(&b, `,`)
		first = false
		strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
	}
	strings.write_string(&b, `]}`)
	return Task_Service_Result{ok = false, status_code = 409, message = strings.to_string(b)}
}

task_dependency_validation_error :: proc(message, error_kind, dependency_task_ids: string) -> Task_Service_Result {
	b := strings.builder_make()
	strings.write_string(&b, `{"ok":false,"message":"`); json_write_string(&b, message)
	strings.write_string(&b, `","error":"`);             json_write_string(&b, error_kind)
	strings.write_string(&b, `","dependency_task_ids":[`)
	ids   := strings.split(dependency_task_ids, ",")
	first := true
	for id_raw in ids {
		id := strings.trim_space(id_raw)
		if id == "" do continue
		if !first do strings.write_string(&b, `,`)
		first = false
		strings.write_string(&b, `"`); json_write_string(&b, id); strings.write_string(&b, `"`)
	}
	strings.write_string(&b, `]}`)
	return Task_Service_Result{ok = false, status_code = 400, message = strings.to_string(b)}
}

task_validate_dependency_ids :: proc(depends_on, chain_id, self_task_id: string) -> (message: string, error_kind: string, dependency_task_ids: string, ok: bool) {
	deps := strings.split(depends_on, ",")
	for dep in deps {
		id := strings.trim_space(dep)
		if id == "" do continue
		if id == self_task_id {
			return "task cannot depend on itself", "self_dependency", id, false
		}
		state, found := store_get_task(id)
		if !found {
			return "dependency task not found", "dependency_not_found", id, false
		}
		if chain_id != "" && state.chain_id != chain_id {
			return "dependency task must be in the same chain", "dependency_cross_chain", id, false
		}
	}
	return "", "", "", true
}

task_service_evaluate_chain :: proc(chain_id, evaluation, author: string) -> Task_Service_Result {
	if chain_id == "" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"chain evaluation requires chain_id"}`}
	}
	if evaluation != "good" && evaluation != "bad" && evaluation != "unreviewed" {
		return Task_Service_Result{ok = false, status_code = 400, message = `{"ok":false,"message":"invalid evaluation value. Expected: good, bad, unreviewed"}`}
	}
	if !store_chain_exists(chain_id) {
		return Task_Service_Result{ok = false, status_code = 404, message = `{"ok":false,"message":"chain not found"}`}
	}
	event := Task_Event{
		kind                     = .Chain_Evaluated,
		chain_id                 = chain_id,
		body                     = evaluation,
		author_agent_instance_id = author,
	}
	if !task_store_append_event(event) {
		return Task_Service_Result{ok = false, status_code = 500, message = `{"ok":false,"message":"append chain evaluation failed"}`}
	}
	task_notify_event(event)
	return Task_Service_Result{ok = true, status_code = 200, message = `{"ok":true}`}
}

task_service_halt_active_tasks_for_agent :: proc(agent_id: string) {
	if agent_id == "" do return
	for state in store_tasks_for_assignee(agent_id) {
		if state.status != .In_Progress do continue
		
		event := Task_Event{
			kind                     = .Task_Status_Changed,
			task_id                  = state.task_id,
			chain_id                 = state.chain_id,
			status                   = "blocked",
			body                     = "system_block:assignee_active_task:pending_reviews_exist",
			author_agent_instance_id = "system-reviewer-gate",
		}
		if task_store_append_event(event) {
			task_notify_event(event)
		}
	}
}

