package sqlite

import "core:fmt"
import "core:strconv"
import "core:strings"
import domain "odin_test:hub/domain"
import iface "odin_test:hub/repository/iface"

Content_Repo_SQLite :: struct { conn: ^Conn }

new_content_repository :: proc(impl: ^Content_Repo_SQLite, conn: ^Conn) -> iface.Content_Repository {
	return iface.Content_Repository{ctx=rawptr(impl), save_memory=content_save_memory_sqlite, get_memory=content_get_memory_sqlite, list_memories=content_list_memories_sqlite, save_conversation=content_save_conversation_sqlite, get_conversation=content_get_conversation_sqlite, list_conversations=content_list_conversations_sqlite, save_message=content_save_message_sqlite, get_message=content_get_message_sqlite, update_message=content_update_message_sqlite, list_messages=content_list_messages_sqlite, list_user_visible_messages=content_list_user_visible_messages_sqlite, list_agent_inbox_messages=content_list_agent_inbox_messages_sqlite, mark_messages_read=content_mark_messages_read_sqlite, save_artifact=content_save_artifact_sqlite, get_artifact=content_get_artifact_sqlite, list_artifacts=content_list_artifacts_sqlite, delete_artifact=content_delete_artifact_sqlite, save_template=content_save_template_sqlite, get_template=content_get_template_sqlite, list_templates=content_list_templates_sqlite}
}

content_save_memory_sqlite :: proc(ctx: rawptr, m: domain.Memory) -> (domain.Memory, bool, domain.Domain_Error) {
	impl := (^Content_Repo_SQLite)(ctx); stmt: sqlite3_stmt=nil
	q := "INSERT INTO memories (memory_id, owner_user_id, agent_id, project_id, template_id, bridge_id, type, status, title, body, evidence, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(memory_id) DO UPDATE SET agent_id=excluded.agent_id, project_id=excluded.project_id, template_id=excluded.template_id, bridge_id=excluded.bridge_id, type=excluded.type, status=excluded.status, title=excluded.title, body=excluded.body, evidence=excluded.evidence, updated_at=excluded.updated_at;"
	if sqlite3_prepare_v2(impl.conn.db, cstring(raw_data(q)), -1, &stmt, nil) != SQLITE_OK do return {}, false, domain.domain_error(.Internal_Error,"failed to prepare memory save")
	defer sqlite3_finalize(stmt); bind_memory(stmt,m)
	if sqlite3_step(stmt) != SQLITE_DONE do return {}, false, domain.domain_error(.Conflict,"memory could not be saved")
	return m,true,{}
}
content_get_memory_sqlite :: proc(ctx: rawptr, id: string) -> (domain.Memory,bool,domain.Domain_Error) { impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT memory_id, owner_user_id, agent_id, project_id, template_id, bridge_id, type, status, title, body, evidence, created_at, updated_at FROM memories WHERE memory_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed memory lookup"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); if sqlite3_step(stmt)!=SQLITE_ROW do return {},false,domain.domain_error(.Not_Found,"memory not found"); return memory_from_stmt(stmt),true,{} }
content_list_memories_sqlite :: proc(ctx: rawptr, owner: domain.User_ID) -> ([]domain.Memory,domain.Domain_Error) { impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT memory_id, owner_user_id, agent_id, project_id, template_id, bridge_id, type, status, title, body, evidence, created_at, updated_at FROM memories WHERE owner_user_id=? OR owner_user_id='system' ORDER BY updated_at DESC;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed memory list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,string(owner)); out:=make([dynamic]domain.Memory); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,memory_from_stmt(stmt)); return out[:],{} }

content_save_conversation_sqlite :: proc(ctx: rawptr, c: domain.Chat_Conversation) -> (domain.Chat_Conversation,bool,domain.Domain_Error) { impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="INSERT INTO chat_conversations (conversation_id, owner_user_id, agent_id, agent_instance_id, project_id, chain_id, title, unread_count, last_message_preview, last_message_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(conversation_id) DO UPDATE SET title=excluded.title, unread_count=excluded.unread_count, last_message_preview=excluded.last_message_preview, last_message_at=excluded.last_message_at, updated_at=excluded.updated_at;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed conversation save"); defer sqlite3_finalize(stmt); bind_conversation(stmt,c); if sqlite3_step(stmt)!=SQLITE_DONE do return {},false,domain.domain_error(.Conflict,"conversation could not be saved"); return c,true,{} }
content_get_conversation_sqlite :: proc(ctx: rawptr, id:string)->(domain.Chat_Conversation,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT conversation_id, owner_user_id, agent_id, agent_instance_id, project_id, chain_id, title, unread_count, last_message_preview, last_message_at, created_at, updated_at FROM chat_conversations WHERE conversation_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed conversation lookup"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); if sqlite3_step(stmt)!=SQLITE_ROW do return {},false,domain.domain_error(.Not_Found,"conversation not found"); return conversation_from_stmt(stmt),true,{} }
content_list_conversations_sqlite :: proc(ctx:rawptr, owner:domain.User_ID, limit:int, cursor:string)->([]domain.Chat_Conversation,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q := "SELECT conversation_id, owner_user_id, agent_id, agent_instance_id, project_id, chain_id, title, unread_count, last_message_preview, last_message_at, created_at, updated_at FROM chat_conversations WHERE owner_user_id=? ORDER BY updated_at DESC LIMIT ?;"; if cursor!="" do q="SELECT conversation_id, owner_user_id, agent_id, agent_instance_id, project_id, chain_id, title, unread_count, last_message_preview, last_message_at, created_at, updated_at FROM chat_conversations WHERE owner_user_id=? AND updated_at < ? ORDER BY updated_at DESC LIMIT ?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed conversation list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,string(owner)); if cursor!="" {bind_text(stmt,2,cursor); bind_text(stmt,3,int_s(limit))} else {bind_text(stmt,2,int_s(limit))}; out:=make([dynamic]domain.Chat_Conversation); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,conversation_from_stmt(stmt)); return out[:],{} }

CHAT_MESSAGE_SELECT :: "message_id, conversation_id, owner_user_id, direction, sender_agent_id, sender_agent_instance_id, body, artifact_ids_json, COALESCE(message_type, 'text'), COALESCE(message_status, 'complete'), COALESCE(metadata_json, '{}'), created_at, delivered_at, read_at"

content_save_message_sqlite :: proc(ctx:rawptr, m:domain.Chat_Message)->(domain.Chat_Message,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="INSERT INTO chat_messages (message_id, conversation_id, owner_user_id, direction, sender_agent_id, sender_agent_instance_id, body, artifact_ids_json, message_type, message_status, metadata_json, created_at, delivered_at, read_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(message_id) DO UPDATE SET delivered_at=excluded.delivered_at, read_at=excluded.read_at;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed message save"); defer sqlite3_finalize(stmt); bind_message(stmt,m); if sqlite3_step(stmt)!=SQLITE_DONE do return {},false,domain.domain_error(.Conflict,"message could not be saved"); return normalize_message_defaults(m),true,{} }
content_get_message_sqlite :: proc(ctx:rawptr, id:string)->(domain.Chat_Message,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE message_id=?;"}); if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed message lookup"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); if sqlite3_step(stmt)!=SQLITE_ROW do return {},false,domain.domain_error(.Not_Found,"message not found"); return message_from_stmt(stmt),true,{} }
content_update_message_sqlite :: proc(ctx:rawptr, owner:domain.User_ID, cid,id,body,status,metadata_json:string)->(domain.Chat_Message,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="UPDATE chat_messages SET body=?, message_status=?, metadata_json=? WHERE owner_user_id=? AND conversation_id=? AND message_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed message update"); defer sqlite3_finalize(stmt); bind_text(stmt,1,body); bind_text(stmt,2,normalize_message_status(status)); bind_text(stmt,3,json_object_or_empty(metadata_json)); bind_text(stmt,4,string(owner)); bind_text(stmt,5,cid); bind_text(stmt,6,id); if sqlite3_step(stmt)!=SQLITE_DONE do return {},false,domain.domain_error(.Conflict,"message could not be updated"); return content_get_message_sqlite(ctx,id) }
content_list_messages_sqlite :: proc(ctx:rawptr, cid:string, owner:domain.User_ID, limit:int, cursor:string)->([]domain.Chat_Message,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE conversation_id=? AND owner_user_id=? ORDER BY created_at DESC LIMIT ?;"}); if cursor!="" do q=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE conversation_id=? AND owner_user_id=? AND created_at < ? ORDER BY created_at DESC LIMIT ?;"}); if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed message list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,cid); bind_text(stmt,2,string(owner)); if cursor!="" {bind_text(stmt,3,cursor); bind_text(stmt,4,int_s(limit))} else {bind_text(stmt,3,int_s(limit))}; out:=make([dynamic]domain.Chat_Message); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,message_from_stmt(stmt)); return out[:],{} }
content_list_user_visible_messages_sqlite :: proc(ctx:rawptr, cid:string, owner:domain.User_ID, limit:int, cursor:string)->([]domain.Chat_Message,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE conversation_id=? AND owner_user_id=? AND direction != 'agent_to_agent' ORDER BY created_at DESC LIMIT ?;"}); if cursor!="" do q=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE conversation_id=? AND owner_user_id=? AND direction != 'agent_to_agent' AND created_at < ? ORDER BY created_at DESC LIMIT ?;"}); if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed visible message list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,cid); bind_text(stmt,2,string(owner)); if cursor!="" {bind_text(stmt,3,cursor); bind_text(stmt,4,int_s(limit))} else {bind_text(stmt,3,int_s(limit))}; out:=make([dynamic]domain.Chat_Message); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,message_from_stmt(stmt)); return out[:],{} }

content_list_agent_inbox_messages_sqlite :: proc(ctx:rawptr, cid:string, owner:domain.User_ID, unread_only, receiver_only, include_outgoing, include_debug: bool, limit:int, cursor:string)->([]domain.Chat_Message,domain.Domain_Error){
	impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil
	
	filters := make([dynamic]string)
	append(&filters, "conversation_id=? AND owner_user_id=?")
	if unread_only do append(&filters, "read_at=''")
	if !include_outgoing {
		append(&filters, "direction != 'agent_to_user'")
	}
	if receiver_only {
		// Receiver only generally means we exclude agent_to_user always.
		// Wait, if it's agent_to_agent, we know it's bound for this conv. So just exclude agent_to_user.
		append(&filters, "direction != 'agent_to_user'")
	}
	if !include_debug do append(&filters, "message_type NOT IN ('pane_capture', 'status_update', 'pane_capture_result')")
	
	if cursor != "" do append(&filters, "created_at < ?")
	
	filter_str := strings.join(filters[:], " AND ")
	
	q:=strings.concatenate({"SELECT ",CHAT_MESSAGE_SELECT," FROM chat_messages WHERE ", filter_str, " ORDER BY created_at DESC LIMIT ?;"})
	
	if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed agent inbox list")
	defer sqlite3_finalize(stmt)
	
	bind_text(stmt,1,cid)
	bind_text(stmt,2,string(owner))
	
	bind_idx := 3
	if cursor != "" {
		bind_text(stmt,bind_idx,cursor)
		bind_idx += 1
	}
	bind_text(stmt,bind_idx,int_s(limit))
	
	out:=make([dynamic]domain.Chat_Message)
	for sqlite3_step(stmt)==SQLITE_ROW do append(&out,message_from_stmt(stmt))
	return out[:],{}
}

content_mark_messages_read_sqlite :: proc(ctx:rawptr, owner:domain.User_ID, message_ids:[]string, updated_at:string)->(int,domain.Domain_Error){
	if len(message_ids) == 0 do return 0, {}
	impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil
	
	// Create an IN clause with enough ?'s
	qs := make([dynamic]string)
	for _ in message_ids { append(&qs, "?") }
	in_clause := strings.join(qs[:], ",")
	
	q:=strings.concatenate({"UPDATE chat_messages SET read_at=? WHERE owner_user_id=? AND message_id IN (", in_clause, ");"})
	if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return 0,domain.domain_error(.Internal_Error,"failed mark messages read")
	defer sqlite3_finalize(stmt)
	
	bind_text(stmt, 1, updated_at)
	bind_text(stmt, 2, string(owner))
	for id, i in message_ids {
		bind_text(stmt, 3 + i, id)
	}
	
	if sqlite3_step(stmt)!=SQLITE_DONE do return 0,domain.domain_error(.Internal_Error,"failed mark messages read exec")
	return len(message_ids), {}
}

content_save_artifact_sqlite :: proc(ctx:rawptr, a:domain.Artifact)->(domain.Artifact,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="INSERT INTO artifacts (artifact_id, owner_user_id, kind, name, description, content_type, size_bytes, blob_ref, content, agent_id, agent_instance_id, chain_id, task_id, project_id, mime, ext, sha256, origin_kind, origin_ref, deleted_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(artifact_id) DO UPDATE SET kind=excluded.kind, name=excluded.name, description=excluded.description, content_type=excluded.content_type, size_bytes=excluded.size_bytes, blob_ref=excluded.blob_ref, content=excluded.content, mime=excluded.mime, ext=excluded.ext, sha256=excluded.sha256, origin_kind=excluded.origin_kind, origin_ref=excluded.origin_ref, deleted_at=excluded.deleted_at, updated_at=excluded.updated_at;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed artifact save"); defer sqlite3_finalize(stmt); bind_artifact(stmt,a); if sqlite3_step(stmt)!=SQLITE_DONE do return {},false,domain.domain_error(.Conflict,"artifact could not be saved"); return a,true,{} }
content_get_artifact_sqlite :: proc(ctx:rawptr,id:string)->(domain.Artifact,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT artifact_id, owner_user_id, kind, name, description, content_type, size_bytes, blob_ref, content, agent_id, agent_instance_id, chain_id, task_id, project_id, mime, ext, sha256, origin_kind, origin_ref, deleted_at, created_at, updated_at FROM artifacts WHERE artifact_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed artifact lookup"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); if sqlite3_step(stmt)!=SQLITE_ROW do return {},false,domain.domain_error(.Not_Found,"artifact not found"); return artifact_from_stmt(stmt),true,{} }
content_list_artifacts_sqlite :: proc(ctx:rawptr, owner:domain.User_ID)->([]domain.Artifact,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT artifact_id, owner_user_id, kind, name, description, content_type, size_bytes, blob_ref, content, agent_id, agent_instance_id, chain_id, task_id, project_id, mime, ext, sha256, origin_kind, origin_ref, deleted_at, created_at, updated_at FROM artifacts WHERE owner_user_id=? ORDER BY updated_at DESC;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed artifact list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,string(owner)); out:=make([dynamic]domain.Artifact); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,artifact_from_stmt(stmt)); return out[:],{} }
content_delete_artifact_sqlite :: proc(ctx:rawptr,id:string,owner:domain.User_ID)->(bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="DELETE FROM artifacts WHERE artifact_id=? AND owner_user_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return false,domain.domain_error(.Internal_Error,"failed artifact delete"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); bind_text(stmt,2,string(owner)); if sqlite3_step(stmt)!=SQLITE_DONE do return false,domain.domain_error(.Internal_Error,"artifact could not be deleted"); return true,{} }

content_save_template_sqlite :: proc(ctx:rawptr,t:domain.Template)->(domain.Template,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="INSERT INTO templates (template_id, owner_user_id, is_system, name, description, persona, instructions, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(template_id) DO UPDATE SET name=excluded.name, description=excluded.description, persona=excluded.persona, instructions=excluded.instructions, updated_at=excluded.updated_at;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed template save"); defer sqlite3_finalize(stmt); bind_template(stmt,t); if sqlite3_step(stmt)!=SQLITE_DONE do return {},false,domain.domain_error(.Conflict,"template could not be saved"); return t,true,{} }
content_get_template_sqlite :: proc(ctx:rawptr,id:string)->(domain.Template,bool,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT template_id, owner_user_id, is_system, name, description, persona, instructions, created_at, updated_at FROM templates WHERE template_id=?;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return {},false,domain.domain_error(.Internal_Error,"failed template lookup"); defer sqlite3_finalize(stmt); bind_text(stmt,1,id); if sqlite3_step(stmt)!=SQLITE_ROW do return {},false,domain.domain_error(.Not_Found,"template not found"); return template_from_stmt(stmt),true,{} }
content_list_templates_sqlite :: proc(ctx:rawptr, owner:domain.User_ID)->([]domain.Template,domain.Domain_Error){ impl:=(^Content_Repo_SQLite)(ctx); stmt:sqlite3_stmt=nil; q:="SELECT template_id, owner_user_id, is_system, name, description, persona, instructions, created_at, updated_at FROM templates WHERE owner_user_id=? OR is_system='1' ORDER BY is_system DESC, name ASC;"; if sqlite3_prepare_v2(impl.conn.db,cstring(raw_data(q)),-1,&stmt,nil)!=SQLITE_OK do return nil,domain.domain_error(.Internal_Error,"failed template list"); defer sqlite3_finalize(stmt); bind_text(stmt,1,string(owner)); out:=make([dynamic]domain.Template); for sqlite3_step(stmt)==SQLITE_ROW do append(&out,template_from_stmt(stmt)); return out[:],{} }

bind_memory :: proc(s:sqlite3_stmt,m:domain.Memory){ bind_text(s,1,m.memory_id);bind_text(s,2,string(m.owner_user_id));bind_text(s,3,m.agent_id);bind_text(s,4,string(m.project_id));bind_text(s,5,m.template_id);bind_text(s,6,m.bridge_id);bind_text(s,7,domain.memory_type_string(m.type));bind_text(s,8,m.status);bind_text(s,9,m.title);bind_text(s,10,m.body);bind_text(s,11,m.evidence);bind_text(s,12,m.created_at);bind_text(s,13,m.updated_at) }
memory_from_stmt :: proc(s:sqlite3_stmt)->domain.Memory { return domain.Memory{memory_id=column_text(s,0),owner_user_id=domain.User_ID(column_text(s,1)),agent_id=column_text(s,2),project_id=domain.Project_ID(column_text(s,3)),template_id=column_text(s,4),bridge_id=column_text(s,5),type=domain.memory_type_from_string(column_text(s,6)),status=column_text(s,7),title=column_text(s,8),body=column_text(s,9),evidence=column_text(s,10),created_at=column_text(s,11),updated_at=column_text(s,12)} }
bind_conversation :: proc(s:sqlite3_stmt,c:domain.Chat_Conversation){ bind_text(s,1,c.conversation_id);bind_text(s,2,string(c.owner_user_id));bind_text(s,3,c.agent_id);bind_text(s,4,c.agent_instance_id);bind_text(s,5,string(c.project_id));bind_text(s,6,c.chain_id);bind_text(s,7,c.title);bind_text(s,8,int_s(c.unread_count));bind_text(s,9,c.last_message_preview);bind_text(s,10,c.last_message_at);bind_text(s,11,c.created_at);bind_text(s,12,c.updated_at) }
conversation_from_stmt :: proc(s:sqlite3_stmt)->domain.Chat_Conversation { return domain.Chat_Conversation{conversation_id=column_text(s,0),owner_user_id=domain.User_ID(column_text(s,1)),agent_id=column_text(s,2),agent_instance_id=column_text(s,3),project_id=domain.Project_ID(column_text(s,4)),chain_id=column_text(s,5),title=column_text(s,6),unread_count=int_v(column_text(s,7)),last_message_preview=column_text(s,8),last_message_at=column_text(s,9),created_at=column_text(s,10),updated_at=column_text(s,11)} }
bind_message :: proc(s:sqlite3_stmt,m:domain.Chat_Message){ n:=normalize_message_defaults(m); bind_text(s,1,n.message_id);bind_text(s,2,n.conversation_id);bind_text(s,3,string(n.owner_user_id));bind_text(s,4,n.direction);bind_text(s,5,n.sender_agent_id);bind_text(s,6,n.sender_agent_instance_id);bind_text(s,7,n.body);bind_text(s,8,n.artifact_ids_json);bind_text(s,9,n.message_type);bind_text(s,10,n.message_status);bind_text(s,11,n.metadata_json);bind_text(s,12,n.created_at);bind_text(s,13,n.delivered_at);bind_text(s,14,n.read_at) }
message_from_stmt :: proc(s:sqlite3_stmt)->domain.Chat_Message { return normalize_message_defaults(domain.Chat_Message{message_id=column_text(s,0),conversation_id=column_text(s,1),owner_user_id=domain.User_ID(column_text(s,2)),direction=column_text(s,3),sender_agent_id=column_text(s,4),sender_agent_instance_id=column_text(s,5),body=column_text(s,6),artifact_ids_json=column_text(s,7),message_type=column_text(s,8),message_status=column_text(s,9),metadata_json=column_text(s,10),created_at=column_text(s,11),delivered_at=column_text(s,12),read_at=column_text(s,13)}) }
normalize_message_defaults :: proc(m:domain.Chat_Message)->domain.Chat_Message{ n:=m; if strings.trim_space(n.artifact_ids_json)=="" do n.artifact_ids_json="[]"; if strings.trim_space(n.message_type)=="" do n.message_type="text"; if strings.trim_space(n.message_status)=="" do n.message_status="complete"; if strings.trim_space(n.metadata_json)=="" do n.metadata_json="{}"; return n }
normalize_message_status :: proc(status:string)->string{ if strings.trim_space(status)=="" do return "complete"; return status }
json_object_or_empty :: proc(value:string)->string{ if strings.trim_space(value)=="" do return "{}"; return value }
bind_artifact :: proc(s:sqlite3_stmt,a:domain.Artifact){ bind_text(s,1,a.artifact_id);bind_text(s,2,string(a.owner_user_id));bind_text(s,3,a.kind);bind_text(s,4,a.name);bind_text(s,5,a.description);bind_text(s,6,a.content_type);bind_text(s,7,int_s(a.size_bytes));bind_text(s,8,a.blob_ref);bind_text(s,9,a.content);bind_text(s,10,a.agent_id);bind_text(s,11,a.agent_instance_id);bind_text(s,12,a.chain_id);bind_text(s,13,a.task_id);bind_text(s,14,string(a.project_id));bind_text(s,15,a.mime);bind_text(s,16,a.ext);bind_text(s,17,a.sha256);bind_text(s,18,a.origin_kind);bind_text(s,19,a.origin_ref);bind_text(s,20,a.deleted_at);bind_text(s,21,a.created_at);bind_text(s,22,a.updated_at) }
artifact_from_stmt :: proc(s:sqlite3_stmt)->domain.Artifact { return domain.Artifact{artifact_id=column_text(s,0),owner_user_id=domain.User_ID(column_text(s,1)),kind=column_text(s,2),name=column_text(s,3),description=column_text(s,4),content_type=column_text(s,5),size_bytes=int_v(column_text(s,6)),blob_ref=column_text(s,7),content=column_text(s,8),agent_id=column_text(s,9),agent_instance_id=column_text(s,10),chain_id=column_text(s,11),task_id=column_text(s,12),project_id=domain.Project_ID(column_text(s,13)),mime=column_text(s,14),ext=column_text(s,15),sha256=column_text(s,16),origin_kind=column_text(s,17),origin_ref=column_text(s,18),deleted_at=column_text(s,19),created_at=column_text(s,20),updated_at=column_text(s,21)} }
bind_template :: proc(s:sqlite3_stmt,t:domain.Template){ bind_text(s,1,t.template_id);bind_text(s,2,string(t.owner_user_id));bind_text(s,3,"1" if t.is_system else "0");bind_text(s,4,t.name);bind_text(s,5,t.description);bind_text(s,6,t.persona);bind_text(s,7,t.instructions);bind_text(s,8,t.created_at);bind_text(s,9,t.updated_at) }
template_from_stmt :: proc(s:sqlite3_stmt)->domain.Template { return domain.Template{template_id=column_text(s,0),owner_user_id=domain.User_ID(column_text(s,1)),is_system=column_text(s,2)=="1",name=column_text(s,3),description=column_text(s,4),persona=column_text(s,5),instructions=column_text(s,6),created_at=column_text(s,7),updated_at=column_text(s,8)} }
int_s :: proc(v:int)->string { return fmt.tprintf("%d",v) }
int_v :: proc(v:string)->int { p,ok:=strconv.parse_int(v); if !ok do return 0; return int(p) }
