// gen_static_skills — build-time codegen for the static SKILL set (BT-6 §7.2).
//
// Odin `#load` needs literal, compile-time paths, so a folder of skills cannot
// be loaded by a runtime loop. This generator scans a skills directory of the
// shape <skills_dir>/<slug>/SKILL.md and emits an Odin source file declaring:
//
//   package agent
//   Static_Skill :: struct { slug: string, content: string }
//   STATIC_SKILLS := []Static_Skill{
//       {"<slug>", #load("<rel>/<slug>/SKILL.md", string)},
//       ...
//   }
//
// The hub iterates STATIC_SKILLS instead of the old hardcoded per-role skill
// procs; the same static set goes to every agent (no role gating).
//
// Usage:
//   gen_static_skills <skills_dir> <out_file> [--load-prefix <rel>]
//
//   skills_dir   : directory containing <slug>/SKILL.md subdirectories
//                  (e.g. src/prompts/skills)
//   out_file     : Odin file to write
//                  (e.g. src/hub/service/agent/static_skills_gen.odin)
//   --load-prefix: path prefix used in the emitted #load(...) strings, relative
//                  to the OUT FILE's location. Defaults to a prefix computed for
//                  the canonical layout (out in src/hub/service/agent, skills in
//                  src/prompts/skills => "../../../prompts/skills").
//
// The generated file is committed to the repo (reviewable diffs) and the flake
// regenerates + verifies-clean before each hub build so it can never drift.
package main

import "core:fmt"
import "core:os"
import "core:slice"
import "core:strings"

DEFAULT_LOAD_PREFIX :: "../../../prompts/skills"

main :: proc() {
	args := os.args
	if len(args) < 3 {
		fmt.eprintln("usage: gen_static_skills <skills_dir> <out_file> [--load-prefix <rel>]")
		os.exit(2)
	}
	skills_dir := args[1]
	out_file := args[2]
	load_prefix := DEFAULT_LOAD_PREFIX
	for i := 3; i < len(args); i += 1 {
		if args[i] == "--load-prefix" && i + 1 < len(args) {
			load_prefix = args[i + 1]
			i += 1
		}
	}

	slugs, ok := collect_slugs(skills_dir)
	if !ok do os.exit(1)
	if len(slugs) == 0 {
		fmt.eprintfln("gen_static_skills: no <slug>/SKILL.md found under %s", skills_dir)
		os.exit(1)
	}
	// Deterministic output: sort slugs so the generated file is stable regardless
	// of directory read order.
	slice.sort(slugs[:])

	b := strings.builder_make()
	defer strings.builder_destroy(&b)
	strings.write_string(&b, "// Code generated by tools/gen_static_skills. DO NOT EDIT.\n")
	strings.write_string(&b, "//\n")
	strings.write_string(&b, "// Regenerate with:\n")
	strings.write_string(&b, "//   odin run tools/gen_static_skills -- src/prompts/skills src/hub/service/agent/static_skills_gen.odin\n")
	strings.write_string(&b, "//\n")
	strings.write_string(&b, "// One entry per src/prompts/skills/<slug>/SKILL.md. The static set is served\n")
	strings.write_string(&b, "// to EVERY agent (no role gating); each entry is hashed + cached + listed in\n")
	strings.write_string(&b, "// the manifest skills[] array by render_agent_manifest.\n")
	strings.write_string(&b, "package agent\n\n")
	strings.write_string(&b, "Static_Skill :: struct {\n\tslug:    string,\n\tcontent: string,\n}\n\n")
	strings.write_string(&b, "STATIC_SKILLS := []Static_Skill{\n")
	for slug in slugs {
		strings.write_string(&b, "\t{\"")
		strings.write_string(&b, slug)
		strings.write_string(&b, "\", #load(\"")
		strings.write_string(&b, load_prefix)
		strings.write_string(&b, "/")
		strings.write_string(&b, slug)
		strings.write_string(&b, "/SKILL.md\", string)},\n")
	}
	strings.write_string(&b, "}\n")

	if werr := os.write_entire_file(out_file, transmute([]byte)strings.to_string(b)); werr != nil {
		fmt.eprintfln("gen_static_skills: failed to write %s", out_file)
		os.exit(1)
	}
	fmt.printfln("gen_static_skills: wrote %s (%d skills: %v)", out_file, len(slugs), slugs)
}

// collect_slugs returns the subdirectory names of skills_dir that contain a
// SKILL.md file. Each such subdirectory name is a skill slug.
collect_slugs :: proc(skills_dir: string) -> ([dynamic]string, bool) {
	out := make([dynamic]string)
	fd, oerr := os.open(skills_dir)
	if oerr != nil {
		fmt.eprintfln("gen_static_skills: cannot open %s", skills_dir)
		return out, false
	}
	defer os.close(fd)
	infos, rerr := os.read_dir(fd, -1, context.allocator)
	if rerr != nil {
		fmt.eprintfln("gen_static_skills: cannot read %s", skills_dir)
		return out, false
	}
	defer os.file_info_slice_delete(infos, context.allocator)
	for info in infos {
		if info.type != .Directory do continue
		skill_path := strings.concatenate({skills_dir, "/", info.name, "/SKILL.md"})
		defer delete(skill_path)
		if os.exists(skill_path) {
			append(&out, strings.clone(info.name))
		}
	}
	return out, true
}
