#!/usr/bin/env bash
# One-click installer, launcher, and manager for Heimdall Agent Manager on Google Cloudtop
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$SCRIPT_DIR"
if [ -f "$SCRIPT_DIR/../package.json" ]; then
  ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
elif [ -f "$SCRIPT_DIR/package.json" ]; then
  ROOT_DIR="$SCRIPT_DIR"
fi

DATA_DIR="${HEIMDALL_DATA_DIR:-$HOME/.local/share/heimdall}"
BIN_DIR="$DATA_DIR/bin"
LIB_DIR="$DATA_DIR/lib"
SHARE_DIR="$DATA_DIR/share/migrations"
RUN_DIR="$DATA_DIR/run"
LOG_DIR="$DATA_DIR/logs"
LOCAL_BIN="$HOME/.local/bin"

MODE="full" # "full", "standalone", or "uninstall"
HUB_URL=""
ENROLLMENT_TOKEN=""
PURGE_DATA=false

show_help() {
  cat << 'HELPEOF'
Usage: ./install.sh [OPTIONS]

Heimdall Cloudtop One-Click Installer & Manager

Modes:
  (default)                Install and launch full single-node stack (Hub, Bridge, Dev-Proxy, UI)
  --standalone             Install and launch bridge-only mode (connects to remote Central Hub)
  --uninstall              Stop running Heimdall services and remove binaries and systemd units

Options for --standalone:
  --hub, --hub-url URL     Central Hub URL (e.g. http://my-host.c.googlers.com:49322)
  --token, --enrollment-token TOKEN
                           Enrollment token generated by the Central Hub
                           (In UI: Settings -> Bridges -> Add Bridge)

Options for --uninstall:
  --purge                  Also delete data directory, databases, and logs ($DATA_DIR)

General Options:
  -h, --help               Show this help message

Examples:
  # 1. Full Single-Node Stack (Local Hub + UI on port 8989 + Local Bridge)
  ./install.sh

  # 2. Standalone Remote Bridge (Interactive prompt for Hub URL and Token)
  ./install.sh --standalone

  # 3. Standalone Remote Bridge (Non-interactive scripted installation)
  ./install.sh --standalone --hub http://my-hub.c.googlers.com:49322 --token <token>

  # 4. Uninstall Heimdall and stop all processes
  ./install.sh --uninstall
HELPEOF
}

MODE_EXPLICIT=false

# Parse CLI arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --full)
      MODE="full"
      MODE_EXPLICIT=true
      shift
      ;;
    --standalone)
      MODE="standalone"
      MODE_EXPLICIT=true
      shift
      ;;
    --hub|--hub-url)
      HUB_URL="${2:-}"
      shift 2 || true
      ;;
    --token|--enrollment-token)
      ENROLLMENT_TOKEN="${2:-}"
      shift 2 || true
      ;;
    --uninstall)
      MODE="uninstall"
      MODE_EXPLICIT=true
      shift
      ;;
    --purge)
      PURGE_DATA=true
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "[-] Unknown option: $1"
      show_help
      exit 1
      ;;
  esac
done

# If no explicit mode was specified and running in an interactive terminal, prompt the user
if [ "$MODE_EXPLICIT" = false ] && [ -t 0 ]; then
  echo ""
  echo "========================================================================"
  echo "         Heimdall Cloudtop Setup & Operations Manager"
  echo "========================================================================"
  echo ""
  echo "  Welcome to Heimdall for Google Cloudtop workstations."
  echo "  Please select an operation mode:"
  echo ""
  echo "    [1] Full Single-Node Stack (Recommended)"
  echo "        Runs Central Hub, Web UI (port 8989), Dev-Proxy, and Local Bridge"
  echo "        on this workstation."
  echo ""
  echo "    [2] Standalone Remote Bridge (Worker-Only)"
  echo "        Runs only the Bridge worker and connects back to a Central Hub"
  echo "        on another Cloudtop."
  echo ""
  echo "    [3] Uninstall Heimdall"
  echo "        Stops running services and removes installed binaries."
  echo ""
  read -rp "  Select an option [1-3, default: 1]: " USER_SELECTION
  case "$USER_SELECTION" in
    2)
      MODE="standalone"
      ;;
    3)
      MODE="uninstall"
      echo ""
      read -rp "  Are you sure you want to stop and remove Heimdall? [y/N]: " CONFIRM_UNINSTALL
      if [[ ! "$CONFIRM_UNINSTALL" =~ ^[Yy]$ ]]; then
        echo "  Uninstallation cancelled."
        exit 0
      fi
      read -rp "  Also purge all databases, tokens, and logs in $DATA_DIR? [y/N]: " CONFIRM_PURGE
      if [[ "$CONFIRM_PURGE" =~ ^[Yy]$ ]]; then
        PURGE_DATA=true
      fi
      ;;
    *)
      MODE="full"
      ;;
  esac
fi

# =============================================================================
# UNINSTALL MODE
# =============================================================================
if [ "$MODE" = "uninstall" ]; then
  echo "========================================================"
  echo "         Heimdall Cloudtop Uninstaller"
  echo "========================================================"

  # 1. Stop systemd user service if active
  if command -v systemctl >/dev/null 2>&1; then
    echo "[uninstall] Stopping and disabling systemd user service..."
    systemctl --user stop heimdall.service 2>/dev/null || true
    systemctl --user disable heimdall.service 2>/dev/null || true
  fi

  # 2. Run stop.sh if it exists
  if [ -f "$DATA_DIR/stop.sh" ]; then
    echo "[uninstall] Running $DATA_DIR/stop.sh..."
    bash "$DATA_DIR/stop.sh" 2>/dev/null || true
  elif [ -f "$BIN_DIR/stop.sh" ]; then
    echo "[uninstall] Running $BIN_DIR/stop.sh..."
    bash "$BIN_DIR/stop.sh" 2>/dev/null || true
  fi

  # 3. Terminate any lingering Heimdall processes
  echo "[uninstall] Ensuring all Heimdall processes are terminated..."
  pkill -f "ham-hub" 2>/dev/null || true
  pkill -f "ham-bridge" 2>/dev/null || true
  pkill -f "ham-dev-proxy" 2>/dev/null || true
  pkill -f "ham-pty-host.*heimdall" 2>/dev/null || true
  pkill -f "vite.*--port 5173" 2>/dev/null || true

  # 4. Remove systemd service unit
  SYSTEMD_UNIT="$HOME/.config/systemd/user/heimdall.service"
  if [ -f "$SYSTEMD_UNIT" ]; then
    echo "[uninstall] Removing systemd unit $SYSTEMD_UNIT..."
    rm -f "$SYSTEMD_UNIT"
    if command -v systemctl >/dev/null 2>&1; then
      systemctl --user daemon-reload 2>/dev/null || true
    fi
  fi

  # 5. Remove CLI symlink
  if [ -L "$LOCAL_BIN/ham-ctl" ] || [ -f "$LOCAL_BIN/ham-ctl" ]; then
    echo "[uninstall] Removing CLI symlink $LOCAL_BIN/ham-ctl..."
    rm -f "$LOCAL_BIN/ham-ctl"
  fi

  # 6. Remove binaries, libraries, and runtime scripts
  echo "[uninstall] Removing installed binaries and runtime files..."
  rm -rf "$BIN_DIR" "$LIB_DIR" "$SHARE_DIR" "$DATA_DIR/ui" "$DATA_DIR/start.sh" "$DATA_DIR/stop.sh" "$DATA_DIR/standalone.env" "$RUN_DIR"

  if [ "$PURGE_DATA" = true ]; then
    echo "[uninstall] Purging data directory ($DATA_DIR)..."
    rm -rf "$DATA_DIR"
  else
    echo "[uninstall] Retained database, tokens, and logs in $DATA_DIR (use --purge to delete completely)."
  fi

  echo ""
  echo "========================================================"
  echo "    Heimdall Successfully Uninstalled!"
  echo "========================================================"
  exit 0
fi

# =============================================================================
# INSTALL / LAUNCH MODES (Standalone or Full)
# =============================================================================

# 1. Determine Bundle Directory
BUNDLE_DIR=""
if [ -d "$SCRIPT_DIR/bin" ] && [ -f "$SCRIPT_DIR/start.sh" ]; then
  BUNDLE_DIR="$SCRIPT_DIR"
elif [ -d "$ROOT_DIR/dist/heimdall-cloudtop/bin" ] && [ -f "$ROOT_DIR/dist/heimdall-cloudtop/start.sh" ]; then
  BUNDLE_DIR="$ROOT_DIR/dist/heimdall-cloudtop"
elif [ -f "$ROOT_DIR/scripts/package-cloudtop-bundle.sh" ]; then
  echo "[install] Building standalone bundle..."
  "$ROOT_DIR/scripts/package-cloudtop-bundle.sh"
  BUNDLE_DIR="$ROOT_DIR/dist/heimdall-cloudtop"
fi

if [ -z "$BUNDLE_DIR" ] || [ ! -d "$BUNDLE_DIR" ]; then
  echo "[-] Could not locate or build Heimdall Cloudtop bundle."
  exit 1
fi

if [ "$MODE" = "standalone" ]; then
  echo "========================================================"
  echo "    Heimdall Cloudtop Remote Bridge Installer & Launcher"
  echo "========================================================"

  # Prompt interactively if missing
  if [ -z "$HUB_URL" ]; then
    if [ -t 0 ]; then
      echo ""
      echo "Standalone Remote Bridge mode connects this Cloudtop to a Central Heimdall Hub."
      read -rp "Enter Central Hub URL (e.g. http://my-host.c.googlers.com:49322): " HUB_URL
    else
      echo "[-] Error: --hub <url> is required in non-interactive standalone mode."
      exit 1
    fi
  fi

  if [ -z "$ENROLLMENT_TOKEN" ]; then
    if [ -t 0 ]; then
      echo "An enrollment token is required to authenticate with the Central Hub."
      echo "(Find this in the Central Hub UI: Settings -> Bridges -> Add bridge -> Copy Token)"
      read -rp "Enter Hub Enrollment Token: " ENROLLMENT_TOKEN
    else
      echo "[-] Error: --token <token> is required in non-interactive standalone mode."
      exit 1
    fi
  fi

  # Clean whitespace and trailing slashes
  HUB_URL="$(echo "$HUB_URL" | sed -e "s/^[[:space:]]*//" -e "s/[[:space:]]*$//" -e "s:/*$::")"
  ENROLLMENT_TOKEN="$(echo "$ENROLLMENT_TOKEN" | sed -e "s/^[[:space:]]*//" -e "s/[[:space:]]*$//")"

  if [ -z "$HUB_URL" ] || [ -z "$ENROLLMENT_TOKEN" ]; then
    echo "[-] Error: Hub URL and enrollment token must not be empty."
    exit 1
  fi
else
  echo "========================================================"
  echo "    Heimdall Cloudtop Single-Node Installer & Launcher"
  echo "========================================================"
fi

echo "[install] Preparing destination $DATA_DIR..."
mkdir -p "$DATA_DIR" "$BIN_DIR" "$LIB_DIR" "$SHARE_DIR" "$RUN_DIR" "$LOG_DIR" "$LOCAL_BIN"
chmod 0700 "$DATA_DIR"

# 2. Copy binaries and runtime libraries
echo "[install] Copying binaries..."
rm -f "$BIN_DIR/"* 2>/dev/null || true
cp -R -p "$BUNDLE_DIR/bin/"* "$BIN_DIR/"
chmod u+w "$BIN_DIR/"* 2>/dev/null || true
chmod +x "$BIN_DIR/"*

if [ -d "$BUNDLE_DIR/lib" ]; then
  echo "[install] Copying runtime libraries..."
  rm -f "$LIB_DIR/"* 2>/dev/null || true
  cp -R -p "$BUNDLE_DIR/lib/"* "$LIB_DIR/" 2>/dev/null || true
  chmod -R u+w "$LIB_DIR/" 2>/dev/null || true
fi

# 3. Copy management scripts
cp "$BUNDLE_DIR/start.sh" "$BIN_DIR/start.sh"
cp "$BUNDLE_DIR/stop.sh" "$BIN_DIR/stop.sh"
cp "$BUNDLE_DIR/start.sh" "$DATA_DIR/start.sh"
cp "$BUNDLE_DIR/stop.sh" "$DATA_DIR/stop.sh"
chmod +x "$BIN_DIR/start.sh" "$BIN_DIR/stop.sh" "$DATA_DIR/start.sh" "$DATA_DIR/stop.sh"

# 4. Symlink CLI to ~/.local/bin
echo "[install] Symlinking ham-ctl into $LOCAL_BIN/ham-ctl..."
ln -sf "$BIN_DIR/ham-ctl" "$LOCAL_BIN/ham-ctl"

HOST_FQDN="$(hostname | sed 's/\.c\.googlers\.com$//').c.googlers.com"

# 5. Mode-specific configuration
if [ "$MODE" = "standalone" ]; then
  # Write standalone configuration file
  cat << CONFFILE > "$DATA_DIR/standalone.env"
# Heimdall Standalone Remote Bridge Configuration
HEIMDALL_STANDALONE=true
HEIMDALL_HUB_URL=$HUB_URL
CONFFILE
  chmod 0600 "$DATA_DIR/standalone.env"

  # Enroll Bridge with Central Hub
  echo "[install] Enrolling remote bridge with Central Hub at $HUB_URL..."
  BRIDGE_TOKEN_FILE="$DATA_DIR/bridge_token_cloudtop"
  export HEIMDALL_HAM_PTY_HOST_BIN="$BIN_DIR/ham-pty-host"
  export HEIMDALL_HAM_CTL_BIN="$BIN_DIR/ham-ctl"
  "$BIN_DIR/ham-bridge" enroll     --hub "$HUB_URL"     --enrollment-token "$ENROLLMENT_TOKEN"     --name "$(hostname -s)"     --user "${USER:-$(whoami)}"     --bridge-token-file "$BRIDGE_TOKEN_FILE"

  # Configure systemd user unit
  if [ -f "$BUNDLE_DIR/scripts/install-systemd-service.sh" ]; then
    echo "[install] Configuring systemd --user service..."
    bash "$BUNDLE_DIR/scripts/install-systemd-service.sh" || true
  elif [ -f "$ROOT_DIR/scripts/install-systemd-service.sh" ]; then
    echo "[install] Configuring systemd --user service..."
    bash "$ROOT_DIR/scripts/install-systemd-service.sh" || true
  fi

  # Launch Bridge
  echo "[install] Launching Heimdall Remote Bridge..."
  if command -v systemctl >/dev/null 2>&1 && [ -f "$HOME/.config/systemd/user/heimdall.service" ]; then
    echo "[install] Starting via systemd user service..."
    systemctl --user daemon-reload || true
    systemctl --user restart heimdall.service || systemctl --user start heimdall.service || "$BIN_DIR/start.sh"
  else
    "$BIN_DIR/start.sh"
  fi

  HUB_UI_URL="$(echo "$HUB_URL" | sed -e 's/:49322/:8989/')"
  echo ""
  echo "========================================================================"
  echo "    Heimdall Remote Bridge Successfully Installed & Running!"
  echo "========================================================================"
  echo ""
  echo "  Connected to Central Hub:"
  echo "    $HUB_URL"
  echo ""
  echo "  👉 Open Central Web UI to manage agents & tasks:"
  echo "    $HUB_UI_URL"
  echo ""
  echo "  Local Bridge Status: http://127.0.0.1:49323"
  echo "  Data Directory:      $DATA_DIR"
  echo "  CLI Tool:            $LOCAL_BIN/ham-ctl (or 'ham-ctl' in PATH)"
  echo ""
  echo "  Management Commands:"
  echo "    Start:             $DATA_DIR/start.sh (or systemctl --user start heimdall.service)"
  echo "    Stop:              $DATA_DIR/stop.sh  (or systemctl --user stop heimdall.service)"
  echo "    Logs:              journalctl --user -u heimdall.service -f"
  echo "    Uninstall:         $0 --uninstall"
  echo "========================================================================"

else
  # Full Single-Node Mode: Remove any leftover standalone configuration
  rm -f "$DATA_DIR/standalone.env"

  # Copy migrations
  if [ -d "$BUNDLE_DIR/share/migrations" ]; then
    echo "[install] Copying database migrations..."
    cp -R -p "$BUNDLE_DIR/share/migrations/"* "$SHARE_DIR/"
  fi

  # Copy pre-built static UI
  if [ -d "$BUNDLE_DIR/ui" ] && [ -f "$BUNDLE_DIR/ui/index.html" ]; then
    echo "[install] Copying pre-built static UI..."
    mkdir -p "$DATA_DIR/ui"
    cp -R -p "$BUNDLE_DIR/ui/"* "$DATA_DIR/ui/"
  fi

  # Pre-seed bridge token upfront for full single-node mode (REQ-CT-12a)
  TOKEN_VAL=""
  if [ -s "$DATA_DIR/bridge_token" ]; then
    TOKEN_VAL="$(tr -d '[:space:]' < "$DATA_DIR/bridge_token")"
  elif [ -s "$DATA_DIR/bridge_token_cloudtop" ]; then
    TOKEN_VAL="$(tr -d '[:space:]' < "$DATA_DIR/bridge_token_cloudtop")"
  else
    TOKEN_VAL="hbr_$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  printf "%s\n" "$TOKEN_VAL" > "$DATA_DIR/bridge_token"
  printf "%s\n" "$TOKEN_VAL" > "$DATA_DIR/bridge_token_cloudtop"
  chmod 0600 "$DATA_DIR/bridge_token" "$DATA_DIR/bridge_token_cloudtop"
  echo "[install] Pre-seeded bridge credentials at $DATA_DIR/bridge_token"

  # Configure systemd user unit
  if [ -f "$BUNDLE_DIR/scripts/install-systemd-service.sh" ]; then
    echo "[install] Configuring systemd --user service..."
    bash "$BUNDLE_DIR/scripts/install-systemd-service.sh" || true
  elif [ -f "$ROOT_DIR/scripts/install-systemd-service.sh" ]; then
    echo "[install] Configuring systemd --user service..."
    bash "$ROOT_DIR/scripts/install-systemd-service.sh" || true
  fi

  # Start the stack
  echo "[install] Launching Heimdall Single-Node Stack (Hub, Bridge, Dev-Proxy, UI)..."
  if command -v systemctl >/dev/null 2>&1 && [ -f "$HOME/.config/systemd/user/heimdall.service" ]; then
    echo "[install] Starting via systemd user service..."
    systemctl --user daemon-reload || true
    systemctl --user restart heimdall.service || systemctl --user start heimdall.service || "$BIN_DIR/start.sh"
  else
    "$BIN_DIR/start.sh"
  fi

  # Health verification: wait up to 15s for port 8989 to respond
  echo "[install] Verifying Edge Gateway on port 8989..."
  deadline=$((SECONDS + 15))
  gw_ok=false
  while [ $SECONDS -lt $deadline ]; do
    if curl -s "http://127.0.0.1:8989/api/v1/health" >/dev/null 2>&1 || curl -s -I "http://127.0.0.1:8989/" >/dev/null 2>&1; then
      gw_ok=true
      break
    fi
    sleep 0.5
  done

  if [ "$gw_ok" = false ]; then
    echo "[-] Warning: Edge gateway not yet responding on port 8989."
    if command -v systemctl >/dev/null 2>&1 && [ -f "$HOME/.config/systemd/user/heimdall.service" ]; then
      systemctl --user status heimdall.service --no-pager || true
    fi
    echo "[-] Check logs: $LOG_DIR/proxy.log, $LOG_DIR/hub.log, $LOG_DIR/bridge.log"
  else
    echo "[install] Edge Gateway verified active on port 8989."
  fi

  # Verify bridge port 49323 (or fallback port 49325) (REQ-CT-12b)
  echo "[install] Verifying local Bridge on port 49323..."
  B_PORT=49323
  if ! curl -s "http://127.0.0.1:49323/api/v1/health" >/dev/null 2>&1 && curl -s "http://127.0.0.1:49325/api/v1/health" >/dev/null 2>&1; then
    B_PORT=49325
  fi
  deadline=$((SECONDS + 10))
  bridge_ok=false
  while [ $SECONDS -lt $deadline ]; do
    if curl -s "http://127.0.0.1:$B_PORT/api/v1/health" >/dev/null 2>&1; then
      bridge_ok=true
      break
    fi
    sleep 0.5
  done
  if [ "$bridge_ok" = true ]; then
    echo "[install] Local Bridge verified active on port $B_PORT."
  else
    echo "[-] Warning: Bridge on port $B_PORT did not respond in time. Check $LOG_DIR/bridge.log"
  fi

  echo ""
  echo "========================================================================"
  echo "    Heimdall Cloudtop Stack Successfully Installed & Running!"
  echo "========================================================================"
  echo ""
  echo "  👉 Open Web UI:      http://${HOST_FQDN}:8989"
  echo "                       (or http://127.0.0.1:8989)"
  echo ""
  echo "  Hub API:             http://127.0.0.1:49322"
  echo "  Bridge Status:       http://127.0.0.1:49323"
  echo "  Data Directory:      $DATA_DIR"
  echo "  CLI Tool:            $LOCAL_BIN/ham-ctl (or 'ham-ctl' in PATH)"
  echo ""
  echo "  Management Commands:"
  echo "    Start:             $DATA_DIR/start.sh (or systemctl --user start heimdall.service)"
  echo "    Stop:              $DATA_DIR/stop.sh  (or systemctl --user stop heimdall.service)"
  echo "    Logs:              journalctl --user -u heimdall.service -f"
  echo "    Uninstall:         $0 --uninstall"
  echo "========================================================================"
fi
