package http

// REQ-PANE-INPUT-1/2/6 -- golden vector: a REAL armored keystroke frame, produced by the
// UI's own shipped crypto, carried through the Hub exactly as the composer sends it.
//
// WHY A GOLDEN VECTOR AND NOT A HAND-WRITTEN STRING. Every other test in this package
// builds its own frame, which proves the decoder self-consistent but cannot catch the two
// panes and the browser drifting apart on the wire format -- which is precisely the bug
// C1 fixed (the agent pane understood neither `vault:v1:` nor `enc_b64`). The payload below
// was generated by calling `encryptShellStreamPayload` from
// src/ui/components/shells/useShellStream.ts:157 -- the same function useAgentStream.ts:396
// calls -- under Node's WebCrypto, with the frame assembled exactly as
// useAgentStream.ts:398 assembles it:
//
//     s.send(JSON.stringify({ type: 'input', enc_b64, data_b64: `${VAULT_ARMOR_PREFIX}${enc_b64}` }))
//
// Layout is base64(12B IV || 16B GCM tag || ciphertext) per useShellStream.ts:156-181.
// The bridge's own production decrypt (`bridge_decrypt_vault_ciphertext_hex`, the call at
// src/bridge/hub_runtime_client.odin:1375) turns the `enc_b64` relayed below back into
// exactly C1_GOLDEN_PLAINTEXT, so this vector pins the whole browser->Hub->bridge contract
// to one set of bytes. If any layer changes its framing, this test fails instead of the
// user silently losing every keystroke again.

import "core:strings"
import "core:testing"
import agent_service "odin_test:hub/service/agent"

C1_GOLDEN_KEY_HEX :: "4f1c2a9d8e7b6a5c4d3e2f10112233445566778899aabbccddeeff0011223344"
C1_GOLDEN_PLAINTEXT :: "ls -la\n"
C1_GOLDEN_ENC_B64 :: "vFQrdD8pfrvPMg80AH82Q+0Ryd+5fD++WZUYiGUzlU+BsSo="
C1_GOLDEN_FRAME :: `{"type":"input","enc_b64":"vFQrdD8pfrvPMg80AH82Q+0Ryd+5fD++WZUYiGUzlU+BsSo=","data_b64":"vault:v1:vFQrdD8pfrvPMg80AH82Q+0Ryd+5fD++WZUYiGUzlU+BsSo="}`

@(test)
test_agent_pane_relays_real_browser_armored_frame :: proc(t: ^testing.T) {
	frame := shell_stream_decode_input_frame(C1_GOLDEN_FRAME)
	defer shell_stream_input_destroy(&frame)

	testing.expect_value(t, frame.kind, Shell_Stream_Input_Kind.Armored)
	testing.expect_value(t, frame.armored, C1_GOLDEN_ENC_B64)
	// REQ-PANE-INPUT-6: the Hub holds no vault key, so it must never claim a plaintext.
	testing.expect_value(t, frame.plain, "")

	cmd := agent_service.agent_pty_input_command_json("cmd_golden", "inst_golden", frame.plain, frame.armored)
	defer delete(cmd)

	testing.expect(t, strings.contains(cmd, "\"type\":\"shell_pty_input\""), "bridge command type")
	// The bridge resolves the pty from shell_id, falling back to agent_instance_id
	// (src/bridge/hub_runtime_client.odin:1334-1337); the agent pane supplies both.
	testing.expect(t, strings.contains(cmd, "\"agent_instance_id\":\"inst_golden\""), "pty addressed by agent_instance_id")
	testing.expect(
		t,
		strings.contains(cmd, strings.concatenate({"\"enc_b64\":\"", C1_GOLDEN_ENC_B64, "\""}, context.temp_allocator)),
		"ciphertext relayed byte-for-byte",
	)
	testing.expect(
		t,
		strings.contains(cmd, strings.concatenate({"\"data_b64\":\"vault:v1:", C1_GOLDEN_ENC_B64, "\""}, context.temp_allocator)),
		"armored data_b64 accompanies enc_b64 for older bridges",
	)
	testing.expect(t, strings.contains(cmd, "\"data\":\"\""), "no plaintext may ride alongside ciphertext")
	testing.expect(t, !strings.contains(cmd, "vault:v1:vault:v1:"), "armor prefix must not be doubled")
}
