// Code generated by tools/gen_static_skills. DO NOT EDIT.
//
// Regenerate with:
//   odin run tools/gen_static_skills -- src/prompts/skills src/hub/service/agent/static_skills_gen.odin
//
// One entry per src/prompts/skills/<slug>/SKILL.md. The static set is served
// to EVERY agent (no role gating); each entry is hashed + cached + listed in
// the manifest skills[] array by render_agent_manifest.
package agent

Static_Skill :: struct {
	slug:    string,
	content: string,
}

STATIC_SKILLS := []Static_Skill{
	{"coordinator-task-management", #load("../../../prompts/skills/coordinator-task-management/SKILL.md", string)},
	{"heimdall-ctl-communication", #load("../../../prompts/skills/heimdall-ctl-communication/SKILL.md", string)},
	{"odin-style-guide", #load("../../../prompts/skills/odin-style-guide/SKILL.md", string)},
	{"worker-task-management", #load("../../../prompts/skills/worker-task-management/SKILL.md", string)},
}
